"""Deterministic invariants for Nolane UI Intelligence."""

from .validators import (
    mandatory_routes_for_profile,
    validate_bounded_saturation,
    validate_completion_packet,
    validate_industry_atlas,
    validate_mandatory_routes,
    validate_repository,
    validate_research_radar,
    validate_research_saturation,
    validate_skill_graph,
    validate_source_ledger,
    validate_state_matrix,
    validate_tokens,
    validate_v3_completion_evidence,
    validate_v4_completion_evidence,
    validate_v5_completion_evidence,
    validate_v6_completion_evidence,
    validate_v7_completion_evidence,
    validate_v8_completion_evidence,
    validate_v9_completion_evidence,
)
from .product_v9 import (
    validate_account_workspace_lifecycle,
    validate_capability_envelope,
    validate_domain_audience_fit,
    validate_interface_residue_audit,
    validate_render_critique,
    validate_render_fidelity,
    validate_settings_architecture,
    validate_taste_comparison,
    validate_v9_product_system,
)
from .scope_v9 import validate_scope_adequacy
from .behavior_v10 import validate_hypothesis_registry
from .benchmark_v10 import validate_task_corpus, materialize_task_for_generation, materialize_task_for_judge
from .mutation_v10 import validate_mutation_registry, expected_mutation_effects
from .experiment_v10 import validate_experiment_manifest, validate_run_record, pairing_key
from .judging_v10 import blind_run_for_judge, pair_orientation, detect_leakage, validate_judgment
from .stats_v10 import paired_delta, bootstrap_ci, summarize_paired, evaluate_ablation_recovery, aggregate_dimension
from .claims_v10 import promote_claim, validate_claim
from .external_ui_execution import (
    PHASE_STAGE_REQUIREMENTS,
    compile_reference_execution_contract,
    infer_reference_pack_ids,
    record_reference_checkpoint,
    task_profile_fingerprint,
    validate_reference_completion,
    validate_reference_execution_contract,
    validate_reference_stage_checkpoint,
)
from .external_ui_intelligence import (
    PERMISSIVE_LICENSES,
    RECONSULT_STAGES,
    load_external_ui_network,
    rank_reference_candidates,
    resolve_reference_pack,
    validate_external_ui_network,
)
from .runtime_v11 import (
    accept_live_visual_preview as accept_runtime_live_visual_preview,
    adjudicate_findings as adjudicate_runtime_findings,
    aggregate_taste_court as aggregate_runtime_taste_court,
    append_live_event as append_runtime_live_event,
    assess_design_memory_staleness as assess_runtime_design_memory_staleness,
    assess_evidence_staleness as assess_runtime_evidence_staleness,
    assess_genericity as assess_runtime_genericity,
    assess_preview_freshness as assess_runtime_preview_freshness,
    assess_quality_residue_closure as assess_runtime_quality_residue_closure,
    assess_visual_observation_capabilities as assess_runtime_visual_observation_capabilities,
    browser_observation_findings as browser_runtime_findings,
    build_browser_transport_capability as build_runtime_browser_transport,
    build_design_memory as build_runtime_design_memory,
    build_evidence_binding as build_runtime_evidence_binding,
    build_hook_capability as build_runtime_hook_capability,
    build_overlay_packet as build_runtime_overlay_packet,
    build_preview_candidate as build_runtime_preview_candidate,
    collect_playwright_observation as collect_runtime_playwright_observation,
    commit_direction as commit_runtime_direction,
    compare_runtime_observations,
    compile_aesthetic_intent as compile_runtime_aesthetic_intent,
    create_live_session as create_runtime_live_session,
    diagnose_runtime_state,
    evaluate_direction_candidates as evaluate_runtime_direction_candidates,
    inject_playwright_preview as inject_runtime_playwright_preview,
    load_rule_registry as load_runtime_rule_registry,
    normalize_browser_observation as normalize_runtime_browser_observation,
    plan_quality_residue_pass as plan_runtime_quality_residue_pass,
    playwright_available as runtime_playwright_available,
    playwright_capability as runtime_playwright_capability,
    prepare_blinded_candidates as prepare_runtime_blinded_candidates,
    prepare_live_visual_preview as prepare_runtime_live_visual_preview,
    prepare_live_visual_selection as prepare_runtime_live_visual_selection,
    prepare_preview_application as prepare_runtime_preview_application,
    product_substitution_assessment as runtime_product_substitution_assessment,
    record_preview_observation as record_runtime_preview_observation,
    refresh_playwright_preview as refresh_runtime_playwright_preview,
    require_transport_capabilities as require_runtime_transport_capabilities,
    resolve_source_attribution as resolve_runtime_source_attribution,
    route_runtime_finding,
    route_runtime_findings,
    scan_path as scan_runtime_path,
    scan_text as scan_runtime_text,
    select_source_candidate as select_runtime_source_candidate,
    sha256_file as sha256_runtime_file,
    sha256_text as sha256_runtime_text,
    transactional_replace as transactional_runtime_replace,
    validate_aesthetic_intent as validate_runtime_aesthetic_intent,
    validate_browser_observation as validate_runtime_browser_observation,
    validate_browser_transport_capability as validate_runtime_browser_transport,
    validate_design_memory as validate_runtime_design_memory,
    validate_evidence_binding as validate_runtime_evidence_binding,
    validate_live_session as validate_runtime_live_session,
    validate_overlay_packet as validate_runtime_overlay_packet,
    validate_preview_candidate as validate_runtime_preview_candidate,
    validate_rule_registry as validate_runtime_rule_registry,
    validate_source_attribution as validate_runtime_source_attribution,
    validate_taste_judgment as validate_runtime_taste_judgment,
    validate_trend_registry as validate_runtime_trend_registry,
)

__all__ = [
    "validate_completion_packet", "validate_repository", "validate_skill_graph",
    "validate_state_matrix", "validate_tokens", "validate_industry_atlas",
    "validate_source_ledger", "validate_research_saturation", "validate_bounded_saturation",
    "validate_research_radar", "validate_mandatory_routes", "mandatory_routes_for_profile",
    "validate_v3_completion_evidence", "validate_v4_completion_evidence", "validate_v5_completion_evidence", "validate_v6_completion_evidence", "validate_v7_completion_evidence", "validate_v8_completion_evidence", "validate_v9_completion_evidence",
    "validate_capability_envelope", "validate_scope_adequacy", "validate_settings_architecture",
    "validate_account_workspace_lifecycle", "validate_interface_residue_audit", "validate_taste_comparison",
    "validate_render_critique", "validate_domain_audience_fit", "validate_render_fidelity", "validate_v9_product_system",
    "validate_hypothesis_registry", "validate_task_corpus", "materialize_task_for_generation", "materialize_task_for_judge",
    "validate_mutation_registry", "expected_mutation_effects", "validate_experiment_manifest", "validate_run_record", "pairing_key",
    "blind_run_for_judge", "pair_orientation", "detect_leakage", "validate_judgment",
    "paired_delta", "bootstrap_ci", "summarize_paired", "evaluate_ablation_recovery", "aggregate_dimension",
    "promote_claim", "validate_claim",
    "PERMISSIVE_LICENSES", "RECONSULT_STAGES", "PHASE_STAGE_REQUIREMENTS",
    "load_external_ui_network", "rank_reference_candidates", "resolve_reference_pack", "validate_external_ui_network",
    "task_profile_fingerprint", "infer_reference_pack_ids", "compile_reference_execution_contract",
    "record_reference_checkpoint", "validate_reference_execution_contract", "validate_reference_stage_checkpoint",
    "validate_reference_completion",
    "query_ui_ecosystem", "validate_ui_ecosystem_registry", "validate_reference_ledger",
    "validate_source_selection", "validate_rich_interaction_contract", "validate_ui_integration_audit",
    "adjudicate_runtime_findings", "append_runtime_live_event", "assess_runtime_evidence_staleness",
    "browser_runtime_findings", "build_runtime_evidence_binding", "build_runtime_hook_capability",
    "compare_runtime_observations", "create_runtime_live_session", "diagnose_runtime_state",
    "load_runtime_rule_registry", "normalize_runtime_browser_observation", "route_runtime_finding",
    "route_runtime_findings", "scan_runtime_path", "scan_runtime_text", "sha256_runtime_file",
    "sha256_runtime_text", "transactional_runtime_replace", "validate_runtime_browser_observation",
    "validate_runtime_evidence_binding", "validate_runtime_live_session", "validate_runtime_rule_registry",
    "compile_runtime_aesthetic_intent", "validate_runtime_aesthetic_intent",
    "evaluate_runtime_direction_candidates", "commit_runtime_direction",
    "assess_runtime_genericity", "validate_runtime_trend_registry",
    "runtime_product_substitution_assessment", "build_runtime_design_memory",
    "validate_runtime_design_memory", "assess_runtime_design_memory_staleness",
    "prepare_runtime_blinded_candidates", "validate_runtime_taste_judgment",
    "aggregate_runtime_taste_court", "plan_runtime_quality_residue_pass",
    "assess_runtime_quality_residue_closure",
    "accept_runtime_live_visual_preview", "assess_runtime_preview_freshness",
    "assess_runtime_visual_observation_capabilities", "build_runtime_browser_transport",
    "build_runtime_overlay_packet", "build_runtime_preview_candidate",
    "collect_runtime_playwright_observation", "inject_runtime_playwright_preview",
    "prepare_runtime_live_visual_preview", "prepare_runtime_live_visual_selection",
    "prepare_runtime_preview_application", "record_runtime_preview_observation",
    "refresh_runtime_playwright_preview", "require_runtime_transport_capabilities",
    "resolve_runtime_source_attribution", "runtime_playwright_available",
    "runtime_playwright_capability", "select_runtime_source_candidate",
    "validate_runtime_browser_transport", "validate_runtime_overlay_packet",
    "validate_runtime_preview_candidate", "validate_runtime_source_attribution",
]

from .ecosystem import (
    query_ui_ecosystem, validate_reference_ledger, validate_rich_interaction_contract,
    validate_source_selection, validate_ui_ecosystem_registry, validate_ui_integration_audit,
)
