"""Built-in V12 reality-grounded UI rule catalog.

Rules are deliberately operational rather than stylistic slogans. Each entry
states applicability, a concrete failure, observable evidence, repair, valid
exceptions, and a verification action. External citations are optional and are
not used as a substitute for these operational fields.
"""
from __future__ import annotations

from typing import Any


def _rule(
    rule_id: str,
    title: str,
    when: str,
    failure: str,
    repair: str,
    verify: str,
    *,
    observable: str | None = None,
    exception: str | None = None,
    rule_class: str = "behavioral",
    severity: str = "major",
    enforcement: str = "block",
) -> dict[str, Any]:
    parts = rule_id.split(".")
    if len(parts) < 3 or parts[0] != "ui":
        raise ValueError(f"invalid reality rule id: {rule_id}")
    return {
        "rule_id": rule_id,
        "domain": parts[1],
        "class": rule_class,
        "severity": severity,
        "enforcement": enforcement,
        "title": title,
        "statement": f"Requirement: {title}.",
        "applies_when": when,
        "failure_mode": failure,
        "observables": [observable or failure],
        "repair": [repair],
        "exceptions": [exception] if exception else [],
        "verification": [verify],
    }


R = _rule
REALITY_RULES_V12 = [
    # Accessibility: operability and perceivable state.
    R("ui.accessibility.keyboard-reachability", "Interactive functionality must be keyboard reachable", "A pointer can invoke, change, dismiss, select, or submit an action.", "Keyboard-only users cannot reach or operate functionality available to pointer users.", "Expose a semantic focusable control or an equivalent keyboard command.", "Complete the affected workflow using keyboard input only.", exception="Free-form spatial input whose meaning intrinsically depends on a continuous pointer path.", rule_class="mechanical"),
    R("ui.accessibility.focus-not-obscured", "Keyboard focus must not be hidden by authored UI", "Focus can move behind sticky, fixed, drawer, banner, or overlay layers.", "The focused component becomes completely hidden by authored content.", "Adjust layer geometry, scrolling, or focus movement so the focused component remains visible.", "Tab through representative states with all persistent overlays present.", rule_class="mechanical"),
    R("ui.accessibility.visible-focus", "Keyboard focus must have a visible indicator", "A component can receive keyboard focus.", "Users cannot visually locate where the next keyboard action will occur.", "Render a clearly perceivable focus treatment across every supported component state.", "Tab through every interactive component state and compare focused versus unfocused rendering.", rule_class="mechanical"),
    R("ui.accessibility.accessible-name", "Actionable controls need an accessible name matching purpose", "A control is icon-only, custom-rendered, or lacks durable visible text.", "Assistive-technology users encounter unnamed, generic, or misleading actions.", "Provide a programmatic name aligned with the visible purpose and label.", "Inspect the accessibility tree and operate the control with assistive technology.", rule_class="mechanical"),
    R("ui.accessibility.status-announcement", "Material asynchronous status must be programmatically exposed", "Success, failure, progress, or completion changes without moving focus.", "Screen-reader users miss a state change visible to sighted users.", "Expose the material status through an appropriate status/live-region or focused-message pattern.", "Trigger the asynchronous state and confirm the material update is announced once at the right time."),

    # Pointer/touch: acquisition, cancellation, and modality independence.
    R("ui.pointer.minimum-target-separation", "Pointer targets must be large enough or sufficiently separated", "Compact pointer targets are adjacent or frequently used.", "Users with limited dexterity can trigger the wrong nearby action or fail to acquire the target.", "Reach at least 24 by 24 CSS pixels or satisfy the spacing/equivalent-control exception.", "Measure rendered target boxes and spacing in supported compact layouts.", exception="Inline text, user-agent controls, essential spatial presentations, or a same-page equivalent control can satisfy recognized exceptions.", rule_class="mechanical"),
    R("ui.pointer.no-hover-only-action", "Required actions cannot exist only on hover", "Hover reveals a control or information needed to complete a task.", "Touch, keyboard, switch, or coarse-pointer users cannot discover or operate the feature.", "Provide a persistent or focus/tap-accessible path; keep hover only as an enhancement.", "Complete the same workflow on touch/coarse-pointer and keyboard-only input."),
    R("ui.pointer.destructive-target-separation", "Destructive actions must not be easy to mis-hit", "Delete, revoke, reset, discard, or similarly destructive actions sit beside common actions.", "A small acquisition error can cause disproportionate loss.", "Separate or strongly differentiate the destructive action and add undo/confirmation when needed.", "Exercise rapid pointer use at supported densities and verify accidental activation has a safe recovery path.", rule_class="contextual"),
    R("ui.pointer.touch-scroll-not-hijacked", "Custom gestures must not unnecessarily hijack touch scrolling", "Swipe, drag, canvas, or carousel handlers run inside a scrollable view.", "Touch users become trapped or cannot scroll the primary surface naturally.", "Constrain gesture capture to the necessary axis/handle and leave ordinary scrolling available elsewhere.", "Scroll the full surface on touch while exercising the custom gesture."),
    R("ui.pointer.pointer-cancel-safety", "Consequential pointer actions must allow cancellation before commit", "A control triggers a destructive, financial, or irreversible operation.", "A slip or accidental press commits before the user can move away or cancel.", "Commit on a normal activation/release path or provide an equivalent cancellation mechanism.", "Press the target, move away before release, and confirm the action does not commit.", exception="Immediate press behavior can be used only when essential and separately safeguarded.", rule_class="mechanical"),

    # Forms: durable labels, error recovery, and submission truth.
    R("ui.forms.error-identification", "Validation errors must identify the problem in text", "Validation rejects user input or submission.", "Users cannot determine what failed or how to correct it.", "Attach concise textual errors to affected fields/operations; preserve a summary for multiple failures.", "Submit representative invalid values with color cues removed and verify every failure remains understandable.", rule_class="mechanical"),
    R("ui.forms.preserve-input-on-validation-error", "Recoverable validation must not erase valid user input", "A populated form fails validation or a recoverable server check.", "Users must re-enter unrelated data the product already possessed.", "Preserve valid form state and clear only unsafe or explicitly invalid transient values.", "Populate several fields, trigger one validation failure, and confirm unrelated values remain intact.", exception="Sensitive values may be cleared when security or platform policy requires it."),
    R("ui.forms.label-not-placeholder-only", "Inputs need durable labels", "Placeholder text communicates an input's purpose.", "The field purpose disappears after entry or is unavailable programmatically.", "Provide a persistent label; reserve placeholder text for examples or optional hints.", "Enter values, review the completed form, and inspect programmatic labels.", rule_class="mechanical"),
    R("ui.forms.validation-timing", "Validation timing must not punish normal entry", "Validation runs while typing, on blur, or during submit.", "Premature errors appear while a user is still composing an eventually valid value.", "Delay blocking errors until the value is clearly impossible, blur is appropriate, or submit occurs.", "Type valid values slowly and with composition/IME behavior; confirm false blocking errors do not appear."),
    R("ui.forms.submit-idempotency", "Repeated submission must not duplicate consequential operations", "Submit creates, sends, charges, books, or mutates consequential state.", "Rapid activation or retry creates duplicate side effects.", "Use an idempotent operation contract and truthful in-progress state.", "Rapidly activate submit and simulate a retry; verify only the intended single side effect occurs.", rule_class="mechanical", severity="critical"),

    # Navigation: orientation, restoration, stable routing.
    R("ui.navigation.back-preserves-context", "Back navigation must preserve meaningful context", "A user opens a child/detail from filtered, sorted, paginated, selected, or scrolled context.", "Back returns to an unrelated default and forces users to reconstruct their place.", "Persist and restore meaningful context unless underlying truth invalidates it.", "Set filters and scroll, open detail, go back, and verify the same meaningful context returns."),
    R("ui.navigation.current-location-visible", "Persistent navigation must reveal current location", "Tabs, sidebar routes, steps, or other persistent destinations are present.", "Users cannot orient themselves or predict adjacent navigation.", "Mark exactly the active destination visually and programmatically without relying on color alone.", "Navigate every destination and verify the intended current item is identified.", rule_class="mechanical"),
    R("ui.navigation.deep-link-resolves", "Advertised deep links must reopen their durable target", "The product exposes copy-link, bookmark, browser-history, or externally addressable routes.", "A shared route opens a generic home, loses resource identity, or errors unexpectedly.", "Encode durable route identity and resolve authorization/loading explicitly.", "Open the link in a fresh session and verify the intended resource or an explicit access state appears."),
    R("ui.navigation.no-dead-end", "Reachable non-terminal views need a valid continuation or exit", "Users can enter nested, empty, error, permission, or transient states.", "The user becomes trapped and must refresh, kill the app, or edit the URL.", "Provide the appropriate continue, retry, back/close, or stable-navigation path.", "Enter every defined exceptional state and recover without restarting the product.", rule_class="mechanical"),
    R("ui.navigation.redirect-loop-free", "Route guards and redirects must converge", "Authentication, onboarding, permission, locale, or canonicalization guards can chain.", "The product reloads, flickers, pollutes history, or never reaches a stable destination.", "Give each guard one authority and make transitions monotonic toward a stable state.", "Exercise guard combinations from fresh sessions and confirm bounded convergence.", rule_class="mechanical"),

    # State and feedback: pending, disabled, optimistic, refresh, success.
    R("ui.state.async-action-feedback", "Async actions need immediate truthful feedback", "An operation has perceptible network, upload, compute, save, or generation latency.", "Users cannot tell whether activation registered and may repeat or abandon it.", "Show a prompt pending state tied to the action and resolve it to material success/failure.", "Throttle the operation and verify pending state appears promptly and resolves correctly."),
    R("ui.state.disabled-control-reason", "Prominent unavailable actions need a discoverable reason", "A primary action is disabled by validation, permissions, prerequisites, limits, or state.", "Users cannot determine what must change to proceed.", "Expose the unmet prerequisite near the action or use an operable action that explains the constraint.", "Enter each disabled state and verify the next required step is discoverable.", rule_class="contextual", severity="moderate", enforcement="warn"),
    R("ui.state.optimistic-rollback", "Optimistic UI must reconcile or roll back on authoritative failure", "Create, update, delete, reorder, reaction, or toggle is shown before authoritative success.", "The screen presents a state that never became true.", "Track pending state and roll back or mark conflict when the authoritative operation fails.", "Force failure after optimistic rendering and verify the UI returns to authoritative truth."),
    R("ui.state.loading-preserves-known-content", "Refreshing should preserve still-valid known content", "A list, dashboard, document, or detail refreshes after useful content already loaded.", "Every refresh erases context into a blank loading surface even though prior data remains usable.", "Keep prior content visible, mark refreshing, and replace it only at the correct truth boundary.", "Throttle repeated refreshes and verify reading/selection context remains stable.", rule_class="behavioral", severity="moderate", enforcement="warn"),
    R("ui.state.success-feedback-linked", "Success feedback must correspond to a committed outcome", "The UI reports success for saves, sends, uploads, purchases, bookings, or mutations.", "Users are told work succeeded while it is still pending or has failed downstream.", "Define the real success boundary and use pending/queued wording before it.", "Force failures around the commit boundary and confirm success is never shown for failed outcomes.", rule_class="mechanical"),

    # Recovery: retry, undo, irreversible scope, partial failure, offline truth.
    R("ui.recovery.retry-preserves-user-work", "Retry must preserve valid user work", "A transient network, service, validation, or compute failure offers retry.", "Retry clears input, attachments, selections, or intent unrelated to the failure.", "Persist recoverable intent and replay only the failed operation.", "Populate a workflow, force failure, retry, and verify valid work remains.", exception="Secrets or expired values may require deliberate re-entry."),
    R("ui.recovery.undo-reversible-destructive", "Cheaply reversible destructive changes should expose recovery", "Delete, archive, remove, or hide can be restored safely without external side effects.", "A slip causes avoidable loss or every action is slowed by confirmation dialogs.", "Offer time-bounded undo or an equivalently cheap recovery path.", "Perform the destructive action, invoke recovery, and verify the exact prior state returns.", exception="Irreversible external effects and security revocations may require confirmation instead.", rule_class="contextual"),
    R("ui.recovery.confirm-irreversible-destructive", "Irreversible destructive actions require explicit consequence awareness", "An action permanently deletes, revokes, spends, publishes, resets, or causes other material irreversible effects.", "A user can commit a high-cost action without understanding its object, scope, or consequence.", "Use an explicit final step naming the action and affected scope; strengthen confirmation at exceptional consequence.", "Exercise every irreversible flow and verify scope is unambiguous before commitment.", rule_class="mechanical", severity="critical"),
    R("ui.recovery.partial-failure-visible", "Partial failures must identify what succeeded and what failed", "One action can affect multiple items, files, recipients, steps, or services independently.", "Users repeat successful work or overlook failed work because mixed outcomes collapse into one status.", "Report successful and failed scope separately and retry only failed work when safe.", "Force one sub-operation to fail and verify every material outcome is distinguishable."),
    R("ui.recovery.offline-state-explicit", "Disconnected state must be explicit when it changes capability", "Network loss changes read freshness, write commitment, or available operations.", "Users assume data is current or committed when it is stale, local, or queued.", "Expose connectivity state and distinguish queued/stale work from authoritative server state.", "Disconnect during read/write workflows and verify the UI never claims unavailable freshness or commitment."),

    # Performance: responsiveness, stability, bounded work, stale request races.
    R("ui.performance.no-input-blocking-work", "Long work must not monopolize the interaction-critical thread", "Interaction triggers expensive compute, parsing, rendering, serialization, or preparation.", "Typing, scrolling, pointer feedback, or cancellation visibly freezes.", "Split, defer, virtualize, stream, or move appropriate work off the interaction-critical path.", "Profile representative worst-case input while actively typing and scrolling.", rule_class="mechanical"),
    R("ui.performance.reserve-media-space", "Predictable late media must reserve layout space", "Images, embeds, charts, or asynchronous media load after surrounding content is usable.", "Content shifts under the pointer or reading position, causing mis-clicks and lost context.", "Declare dimensions/aspect constraints or stable placeholders matching eventual footprint.", "Throttle media loading and verify surrounding interactive content does not jump.", rule_class="mechanical"),
    R("ui.performance.virtualize-unbounded-collections", "Potentially large collections need bounded rendering cost", "Lists, grids, tables, trees, or timelines can substantially exceed the viewport.", "Render, update, memory, or scrolling cost grows with the full collection unnecessarily.", "Paginate, window, progressively render, or otherwise bound active view complexity while preserving semantics.", "Test near the supported high-volume boundary and profile initial render, scrolling, and updates.", rule_class="contextual"),
    R("ui.performance.cancel-stale-requests", "Stale async responses must not overwrite newer intent", "Search, filters, navigation, previews, or dependent requests can overlap.", "A late older response replaces a newer state and makes the UI appear to go backward.", "Cancel superseded work or gate state commits by request/version identity.", "Artificially reorder overlapping responses and verify only the newest applicable result becomes current.", rule_class="mechanical"),
    R("ui.performance.progressive-noncritical-work", "Non-critical work must not gate primary task readiness", "A screen loads multiple independent primary and secondary dependencies.", "Users wait for analytics, recommendations, decorative media, or secondary panels before the main task works.", "Separate readiness boundaries and defer secondary work until the primary interaction path is usable.", "Throttle secondary dependencies and verify the primary task becomes operable independently.", severity="moderate", enforcement="warn"),

    # Motion: preference, meaning, blocking, automatic movement, flashing.
    R("ui.motion.respect-reduced-motion", "Non-essential motion must respect reduced-motion preference", "The UI animates movement, scale, parallax, auto-scroll, or looping decoration.", "Users who request reduced motion still receive substantial non-essential motion.", "Provide a reduced-motion path that removes or materially simplifies spatial motion while preserving meaning.", "Enable reduced-motion at platform level and exercise every animated workflow.", rule_class="mechanical"),
    R("ui.motion.motion-not-only-meaning", "Motion cannot be the only carrier of required meaning", "Animation explains where content moved, what changed, or whether an action succeeded.", "Removing, skipping, or not perceiving animation hides required state or causality.", "Add persistent visual/textual/state cues so motion enhances rather than owns meaning.", "Disable animation and verify the workflow remains understandable and operable."),
    R("ui.motion.animation-does-not-block-input", "Non-essential transitions must not unnecessarily block input", "Navigation, expansion, modal opening, or rearrangement uses animation.", "Valid user input is ignored solely because decorative transition timing has not finished.", "Accept safe input during the transition or shorten/remove its blocking portion.", "Rapidly continue the workflow during transitions and verify valid input is accepted or explicitly queued.", severity="moderate", enforcement="warn"),
    R("ui.motion.auto-motion-pausable", "Long-running automatic motion must be controllable", "Material content auto-advances, pans, scrolls, or moves without direct initiation.", "Users lose reading position or cannot interact before content moves.", "Provide pause/stop, suspend on interaction/focus, or remove automatic motion.", "Focus/read the moving content long enough to verify it can be paused and remains stable.", rule_class="mechanical"),
    R("ui.motion.avoid-dangerous-flash", "Product-authored effects must avoid dangerous flashing", "The UI includes strobe, flash, rapid contrast alternation, or repeated luminance changes.", "Photosensitive users can be exposed to a serious health hazard.", "Remove the effect or replace it with non-flashing emphasis unless a rigorous safety assessment proves it safe.", "Review animated assets/effects with an appropriate flash-analysis process before release.", rule_class="mechanical", severity="critical"),

    # Layout/responsive truth.
    R("ui.layout.no-document-horizontal-overflow", "Ordinary views must not create accidental page-level horizontal overflow", "The product is used at a supported narrow viewport or with enlarged content.", "Required content becomes horizontally unreachable because authored layout exceeds the viewport.", "Remove brittle width constraints, allow reflow/wrapping, or isolate intentional panning to a local spatial surface.", "Check supported narrow widths and enlarged content for document-level overflow.", exception="Explicit canvases, timelines, editors, or spatial data surfaces may intentionally pan when operable.", rule_class="mechanical"),
    R("ui.layout.text-expansion-survives", "Layout must survive realistic text expansion", "Text can be localized, dynamic, or enlarged by user settings.", "Longer text clips, overlaps, disappears, or pushes essential actions out of reach.", "Allow wrapping/flexible sizing and avoid fixed heights tied to one example language.", "Run pseudo-localized/expanded text through key screens and inspect clipping and overlap.", rule_class="mechanical"),
    R("ui.layout.sticky-ui-not-cover-content", "Sticky and fixed chrome must not permanently cover required content", "Headers, footers, toolbars, banners, or floating controls overlay scrollable content.", "Required content or focus targets remain covered and unreachable.", "Reserve space, use scroll offsets, constrain sticky regions, or make obstructive chrome dismissible.", "Scroll and focus first/last content at supported viewports with all persistent layers present.", rule_class="mechanical"),
    R("ui.layout.long-content-wraps", "Long valid strings must not destroy layout", "URLs, identifiers, filenames, tokens, or user-generated strings can exceed design examples.", "One long value expands containers, pushes controls away, or creates document overflow.", "Wrap, locally scroll, or truncate with an accessible full-value recovery path.", "Inject extreme valid strings and verify layout and full-value access remain usable.", rule_class="mechanical"),
    R("ui.layout.visual-order-matches-interaction", "Visual and keyboard reading order must not contradict", "CSS reordering, portals, responsive moves, or custom positioning change visual order.", "Tab/reading order conflicts with visible task order and becomes unpredictable.", "Align semantic/DOM order with the intended reading and task sequence.", "Compare visual traversal with keyboard and accessibility-tree order at each breakpoint.", rule_class="mechanical"),

    # Content/copy truth.
    R("ui.content.no-shipping-placeholders", "Shipping UI must not expose unresolved placeholder content", "A surface is reachable in a production/release path.", "Users encounter lorem ipsum, TODO copy, fake identities/metrics, placeholder URLs, or knowingly dead demo actions as if real.", "Replace placeholders with real content/state handling or label the surface explicitly as sample/demo content.", "Search and traverse release surfaces for placeholder markers and exercise demo-looking actions.", rule_class="mechanical"),
    R("ui.content.action-label-specific", "Consequential action labels should describe the result", "A control commits, deletes, purchases, publishes, saves, sends, or advances meaningful workflow state.", "Generic wording leaves multiple materially different outcomes plausible.", "Name the action using the user-visible verb/object or outcome; keep destructive wording explicit.", "Review the control with minimal surrounding copy and verify its consequence remains predictable.", rule_class="contextual", severity="moderate", enforcement="warn"),
    R("ui.content.errors-give-next-action", "Recoverable errors must help the user recover", "A failure can be retried, corrected, reconnected, reauthenticated, or routed around safely.", "The error is visible but the user cannot determine a useful next step.", "State what failed at user level and expose the valid recovery action; keep diagnostics separate.", "Trigger representative recoverable failures and verify each message enables recovery."),
    R("ui.content.units-and-basis-visible", "Decision-relevant numbers need visible unit and basis", "A number can plausibly be interpreted under different units, currencies, rates, or time bases.", "Users make wrong comparisons because the numeric basis is hidden.", "Display or tightly associate the unit/basis and keep conversions explicit.", "Review representative values in isolation and confirm their unit/basis is unambiguous.", rule_class="mechanical"),
    R("ui.content.date-time-unambiguous", "Decision-relevant dates and times need sufficient context", "Timestamps affect deadlines, schedules, logs, bookings, or cross-region coordination.", "Supported locale/time-zone interpretations can map the display to materially different moments.", "Use locale-appropriate formatting and surface timezone/absolute-date context where decisions require it.", "Render the same record under supported locale/time-zone settings and verify the intended instant stays clear.", rule_class="contextual"),

    # Data truth: precision, freshness, missingness, transformations, visual semantics.
    R("ui.data.no-fake-precision", "Displayed precision must not exceed underlying information", "The UI reports measured, estimated, sampled, modeled, or aggregated quantities.", "Extra decimals, exact ranks, or exact-looking percentages imply certainty the source cannot support.", "Round/bucket to defensible precision and expose uncertainty/range when decision-relevant.", "Trace displayed values to source precision and verify the UI does not invent certainty.", rule_class="contextual"),
    R("ui.data.stale-data-labelled", "Known stale decision-relevant data must not masquerade as current", "Cached, delayed, offline, or eventually consistent data is shown where freshness matters.", "Users act on old information believing it is current.", "Expose last-updated/stale state or block actions whose correctness requires fresher data.", "Simulate delayed/offline refresh and verify freshness truth is visible at decision points."),
    R("ui.data.missing-distinct-from-zero", "Missing and unavailable values must remain distinct from zero", "A metric can legitimately be zero and can also be missing, unavailable, or not applicable.", "Users interpret absence as a real zero and make incorrect comparisons.", "Represent missing/unavailable state distinctly and explain it when decision-relevant.", "Render genuine zero and missing cases side by side and verify they cannot be confused.", rule_class="mechanical"),
    R("ui.data.filter-sort-state-visible", "Active data transformations must be visible and resettable", "Filters, sorts, scopes, grouping, or search materially change a collection.", "Users believe records are absent or naturally ordered when the view is transformed.", "Expose active transformations near the data and provide a clear reset/remove path.", "Apply multiple transformations and verify active state remains visible and resettable."),
    R("ui.data.visual-encoding-has-meaning", "Data-like visual channels must map to real semantics", "Size, position, length, saturation, hue, area, or similar channels vary across data marks.", "Users infer magnitude, category, or priority from decoration that is not actually data-bound.", "Bind varying channels to explicit meaning/data or remove systematic variation.", "Trace each varying visual channel to its semantic/data source.", rule_class="contextual"),

    # Modal/overlay behavior.
    R("ui.modal.restore-focus-on-close", "Closing a modal must restore a sensible focus destination", "A modal interrupts an existing keyboard workflow.", "Closing sends focus to document/root or an unrelated control and users lose their place.", "Return focus to the invoker or a logical surviving fallback.", "Open and close by every supported path with keyboard input and inspect resulting focus.", rule_class="mechanical"),
    R("ui.modal.modal-focus-contained", "True modal interaction must not leak to background controls", "A dialog blocks interaction with the underlying application.", "Keyboard or assistive-technology users can still operate background UI.", "Use native modal semantics or correctly manage inertness and focus containment.", "Tab forward/backward and attempt background activation while the modal is open.", rule_class="mechanical"),
    R("ui.modal.explicit-close-path", "Blocking transient overlays need a discoverable close path", "Dialog, drawer, popover, or lightbox can remain open and obscure work.", "Users cannot dismiss it without an outside precision click or undiscoverable gesture.", "Provide explicit close/cancel and appropriate keyboard dismissal for the pattern.", "Dismiss the overlay by keyboard and touch without relying on outside-click precision.", rule_class="mechanical"),
    R("ui.modal.initial-focus-purposeful", "Modal initial focus must support comprehension and safe action", "A modal opens during keyboard or assistive-technology use.", "Focus remains behind the modal, lands arbitrarily, or primes a destructive action without reason.", "Place focus on the dialog/heading or first logical safe control according to task semantics.", "Open each modal with keyboard input and inspect the first focused element."),
    R("ui.modal.background-state-preserved", "Transient overlays must not silently destroy background work", "A user opens a picker, drawer, dialog, or popover while editing parent state.", "Inspecting or canceling the overlay resets unrelated parent work.", "Isolate transient overlay state and commit only at its defined apply/confirm boundary.", "Enter parent changes, open and cancel the overlay, and verify parent work remains unchanged."),

    # Drag/reorder: alternative operation and trustworthy commit.
    R("ui.drag.provide-non-drag-alternative", "Dragging must have a non-drag alternative", "Users reorder, move, resize, connect, or place items through drag movements.", "Users who cannot perform precise dragging cannot complete the task.", "Add an equivalent click, keyboard, menu, position-control, or stepper operation.", "Achieve the same outcome without any dragging movement.", exception="Free-form drawing or spatial manipulation may require drag when path/position itself is essential.", rule_class="mechanical"),
    R("ui.drag.drop-target-visible", "Valid drag destinations must be perceivable before drop", "A drag can end in multiple destinations or insertion positions.", "Users cannot predict whether or where an item will be accepted.", "Expose valid targets/insertion markers and invalid-state feedback without relying on color alone.", "Drag across valid and invalid destinations and verify outcome is predictable before release."),
    R("ui.drag.drag-cancel-restores", "Canceling drag must restore pre-drag persistent state", "A drag operation can be canceled or interrupted.", "Canceled movement persists as unintended authoritative state.", "Keep persistence behind the drop/commit boundary or explicitly roll back on cancellation.", "Begin a drag, move tentatively, cancel, and verify authoritative state matches pre-drag state.", rule_class="mechanical"),
    R("ui.drag.reorder-announced", "Reordering must expose the resulting position", "Users reorder items in a list, grid, or tree.", "Users cannot confirm where the item moved, especially without visual drag feedback.", "Update semantic order and expose/announce the resulting position when appropriate.", "Reorder through the non-drag path and verify visual, semantic, and programmatic order agree."),
    R("ui.drag.autoscroll-controllable", "Drag autoscroll must remain controllable", "Dragging can extend beyond the current scroll viewport.", "Autoscroll runs away, causing unintended drops or loss of spatial context.", "Use bounded edge zones/speed and stop autoscroll immediately when the trigger condition ends.", "Drag slowly near every scroll edge and verify start, speed, and stop behavior are predictable.", rule_class="contextual", severity="moderate", enforcement="warn"),

    # Selection/bulk actions: scope and identity.
    R("ui.selection.selection-scope-visible", "Selection scope must be explicit", "Selection can span pages, filters, groups, or hidden rows.", "Users apply actions to more or fewer items than intended.", "Show selected count and scope and make scope escalation explicit.", "Select across pagination/filter states and verify pending bulk scope is unambiguous."),
    R("ui.selection.select-all-escalation-explicit", "Select-all must not silently expand beyond visible items", "A collection contains more items than currently rendered.", "One control silently selects hidden/off-page items when the user intended visible rows.", "Separate visible selection from all-matching selection or explicitly announce the escalation.", "Use select-all on a multi-page filtered set and verify selected scope is stated before actions.", rule_class="mechanical"),
    R("ui.selection.bulk-destructive-scope-confirmed", "Bulk destructive actions must restate affected scope", "A destructive operation applies to multiple selected records.", "A selection mistake becomes multiplied across many items without a final scope check.", "Show affected count/scope and an explicit destructive action label before commit.", "Create selections of different sizes/scopes and verify the final step reflects each accurately.", rule_class="mechanical", severity="critical"),
    R("ui.selection.partial-selection-distinct", "Partially selected groups need a distinct state", "Hierarchical/grouped data allows mixed child selection.", "Users mistake partially selected groups for fully selected or unselected groups.", "Use and synchronize a visible/programmatic mixed or indeterminate state.", "Toggle descendants through none/partial/all and inspect parent visual/programmatic state.", rule_class="mechanical"),
    R("ui.selection.selection-survives-nondestructive-refresh", "Refresh must preserve selection by identity or explicitly clear it", "A selected collection refreshes, resorts, inserts, or removes data.", "Selection silently moves by row position, targets different records, or disappears without reason.", "Track stable identities, reconcile removed items, and communicate any scope change.", "Select items, refresh with insertions/removals/reordering, and verify intended identities remain selected."),

    # Privacy/security UX truth.
    R("ui.privacy.sensitive-default-masking", "Sensitive values should not be needlessly exposed by default", "Credentials, full secrets, recovery codes, or payment-like data are displayed.", "Sensitive information remains visible more broadly or longer than the task requires.", "Mask/minimize by default and provide deliberate reveal/copy controls where the task needs full access.", "Open the surface in default state and confirm only the minimum necessary secret content is exposed.", exception="A surface whose explicit primary purpose is to display/export the full secret after deliberate user action.", rule_class="contextual"),
    R("ui.privacy.clipboard-secret-feedback", "Sensitive copy actions must be explicit without re-leaking the value", "Users can copy credentials, tokens, recovery codes, or similarly sensitive values.", "Ambiguous copy controls or success messages expose the full secret again unnecessarily.", "Use a specific copy label and minimal success feedback that does not echo the secret.", "Copy each sensitive value and verify clipboard content, label specificity, and feedback."),
    R("ui.privacy.permission-request-in-context", "Sensitive permissions should be requested at the point of need", "The product needs camera, microphone, location, files, contacts, notifications, or similar access.", "Users see a permission prompt before understanding why the feature needs it.", "Explain the feature-level purpose immediately before requesting the narrowest necessary system permission.", "Start from fresh permissions and verify prompts occur only after initiating the relevant feature."),
    R("ui.privacy.privacy-toggle-truthful", "Privacy controls must govern the behavior they claim", "A setting disables analytics, sharing, history, personalization, visibility, or retention.", "The UI says privacy behavior changed while the governed data path continues unchanged.", "Bind the setting to the actual policy/config authority and disclose delayed or non-retroactive effects.", "Toggle the setting and inspect governed requests/storage/visibility across restart where applicable.", rule_class="mechanical", severity="critical"),
    R("ui.privacy.destructive-account-scope", "Broad data deletion must state actual deletion and retention scope", "A user can delete an account, workspace, history, backup, or broad personal dataset.", "Users make irreversible decisions without knowing local/cloud/shared/retained consequences.", "Summarize deleted, retained, shared, and local/cloud scope before final commitment.", "Compare the final deletion copy with actual storage/retention behavior for representative cases.", rule_class="mechanical", severity="critical"),
]

REALITY_RULE_CATALOG_V12 = {
    "version": 12,
    "purpose": (
        "Reality-grounded UI rules for AI agents. External sources are optional; "
        "operational applicability, failure, observables, repair, exceptions, and verification are mandatory."
    ),
    "rules": REALITY_RULES_V12,
}

__all__ = ["REALITY_RULES_V12", "REALITY_RULE_CATALOG_V12"]
