"""First explicitly authored operational UX rule wave.

Only failures with observable consequences and meaningful falsifiers belong in
this registry. Contextual judgments remain non-blocking by construction.
"""

from __future__ import annotations


def _rule(*, rule_id, domain, mechanism_id, rule_class, severity, enforcement, title, statement,
          applies_when, failure_modes, user_impacts, observables, falsifiers, repairs,
          verification, owner_skill_ids):
    return {
        "rule_id": rule_id,
        "domain": domain,
        "mechanism_id": mechanism_id,
        "class": rule_class,
        "severity": severity,
        "enforcement": enforcement,
        "title": title,
        "statement": statement,
        "applies_when": tuple(applies_when),
        "failure_modes": tuple(failure_modes),
        "user_impacts": tuple(user_impacts),
        "observables": tuple(observables),
        "falsifiers": tuple(falsifiers),
        "repairs": tuple(repairs),
        "verification": tuple(verification),
        "owner_skill_ids": tuple(owner_skill_ids),
        "status": "active",
    }


UX_RULES = tuple(sorted((
    _rule(
        rule_id="ux.comprehension.destructive-consequence-before-commit",
        domain="comprehension",
        mechanism_id="ambiguous-consequence",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Reveal destructive consequence before commit",
        statement="A destructive action must expose its material target, scope, and permanence before the user commits it.",
        applies_when=("The user is about to commit an action that deletes, revokes, overwrites, cancels, or irreversibly changes valuable state.",),
        failure_modes=("The final commitment control can be activated before the material destructive target, scope, or permanence is available to the user.",),
        user_impacts=("The user can intentionally operate the visible control while unintentionally authorizing a materially different destructive outcome.",),
        observables=("Inspect the last pre-commit state and record whether target identity, affected scope, destructive effect, and reversibility are visible before activation.",),
        falsifiers=("The rule is falsified when the last pre-commit state clearly exposes the destructive target, material scope, effect, and recovery or irreversibility status.",),
        repairs=("Move consequence information into the pre-commit state and label the commitment control with the material action rather than generic confirmation text.",),
        verification=("Re-run the destructive path from a fresh state and verify that no commit-capable state exists before all material consequence information is exposed.",),
        owner_skill_ids=("clarifying-action-consequences",),
    ),
    _rule(
        rule_id="ux.comprehension.hidden-scope-change-visible",
        domain="comprehension",
        mechanism_id="state-without-explanation",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Expose material scope changes",
        statement="A task-relevant scope change must be surfaced before subsequent actions are interpreted under the new scope.",
        applies_when=("The system can change the object set, audience, account, workspace, time range, filter scope, or other material action scope during an active task.",),
        failure_modes=("The interface continues to accept task actions after a material scope change without exposing that the user's effective working scope has changed.",),
        user_impacts=("The user can apply a correct action to the wrong effective scope because the interface preserves the appearance of the previous working context.",),
        observables=("Trigger the scope transition and compare the visible pre-transition context with the first state in which an action can operate under the new scope.",),
        falsifiers=("The rule is falsified when the changed scope is visibly identified or the task is safely paused until the user re-establishes the new working context.",),
        repairs=("Surface the new scope at the transition boundary and require revalidation before consequential actions continue when prior intent may no longer apply.",),
        verification=("Exercise each supported scope-changing transition and verify that subsequent actionable states cannot silently inherit invalid intent from the previous scope.",),
        owner_skill_ids=("designing-contextual-explanations", "tracing-cross-step-state"),
    ),
    _rule(
        rule_id="ux.comprehension.no-false-completion",
        domain="comprehension",
        mechanism_id="false-completion",
        rule_class="behavioral",
        severity="critical",
        enforcement="block",
        title="Do not signal completion before authoritative completion",
        statement="Success or completion language must not outrun the authoritative state required by the promised outcome.",
        applies_when=("The interface communicates success for an operation whose authoritative completion can still be pending, rejected, rolled back, or dependent on required work.",),
        failure_modes=("A success state is rendered while the authoritative operation is still pending, has failed, or has not satisfied a required completion dependency.",),
        user_impacts=("The user can stop monitoring, leave the task, or make downstream decisions based on an outcome that the system has not actually achieved.",),
        observables=("Hold or fail the authoritative completion step and inspect every visible status, notification, route transition, and completion affordance exposed to the user.",),
        falsifiers=("The rule is falsified when pending states remain explicitly pending and success appears only after the authoritative completion condition is satisfied.",),
        repairs=("Represent submitted, processing, partially completed, failed, and completed states separately and bind success language to authoritative completion evidence.",),
        verification=("Inject pending and failure outcomes at each asynchronous completion boundary and verify that none of them can render a final success state.",),
        owner_skill_ids=("evaluating-task-success", "clarifying-action-consequences"),
    ),
    _rule(
        rule_id="ux.convergence.product-architecture-not-generic-template",
        domain="convergence",
        mechanism_id="goal-displacement",
        rule_class="convergence",
        severity="observation",
        enforcement="review",
        title="Challenge generic product architecture convergence",
        statement="Major product surfaces should be justified by recurring user goals rather than by a generic dashboard, sidebar, card, tab, or entity-management template.",
        applies_when=("A generated or redesigned product architecture introduces major destinations, dashboards, panels, or entity groupings without explicit task evidence for their role.",),
        failure_modes=("The architecture can be transferred to an unrelated product by renaming entities while preserving nearly the same navigation, dashboard, and workflow structure.",),
        user_impacts=("The product may look complete while forcing real work through generic feature containers that do not match task priority, sequence, or domain mental models.",),
        observables=("Map each major destination to a recurring user goal and test whether the architecture remains equally plausible after substituting an unrelated product domain.",),
        falsifiers=("The review concern is falsified when major surfaces have product-specific task rationale and substitution materially breaks the information architecture or workflow logic.",),
        repairs=("Re-derive major surfaces from recurring goals, decisions, object relationships, and task transitions before selecting a navigation or dashboard presentation pattern.",),
        verification=("Repeat the goal mapping and cross-domain substitution review with independent human judgment because product-specific plausibility is contextual evidence.",),
        owner_skill_ids=("architecting-goal-oriented-navigation", "identifying-user-goals"),
    ),
    _rule(
        rule_id="ux.flow.interruption-preserves-resumable-context",
        domain="journey-flow",
        mechanism_id="context-loss",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Preserve resumable context across predictable interruption",
        statement="Predictable interruption must not erase the context required to safely resume valuable in-progress work.",
        applies_when=("A multi-step or authored task can predictably be interrupted by reload, navigation, authentication expiry, temporary disconnection, or a supported session boundary.",),
        failure_modes=("After a predictable interruption the product restores some data but loses the active object, step, selection, scope, or intent required for safe continuation.",),
        user_impacts=("The user must reconstruct context from memory or can unknowingly resume work against a different object or scope than before interruption.",),
        observables=("Interrupt the task at each meaningful checkpoint and compare restored object identity, step position, selections, scope, authored data, and freshness state.",),
        falsifiers=("The rule is falsified when resumable checkpoints restore all still-valid task context or explicitly invalidate and explain context that cannot safely be restored.",),
        repairs=("Persist the minimal resumable context alongside authored progress and revalidate any state whose authority or freshness can change while interrupted.",),
        verification=("Run an interruption matrix covering reload, leave-and-return, expiry, and temporary connectivity loss at every critical resumable checkpoint.",),
        owner_skill_ids=("designing-cross-session-continuity", "verifying-interruption-recovery"),
    ),
    _rule(
        rule_id="ux.flow.no-cross-step-contradiction",
        domain="journey-flow",
        mechanism_id="cross-step-inconsistency",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Keep shared workflow state coherent across steps",
        statement="Steps in one workflow must not present contradictory values for shared task state without a visible state-changing event.",
        applies_when=("Two or more workflow steps display, derive, summarize, or commit the same user choice, object property, quantity, scope, or outcome-relevant state.",),
        failure_modes=("A later or revisited step presents shared state that conflicts with an earlier confirmed value without exposing an event that legitimately changed it.",),
        user_impacts=("The user cannot know which representation is authoritative and may commit an outcome different from the state they previously reviewed.",),
        observables=("Set distinctive shared values, traverse forward and backward through the workflow, and compare every representation and summary of those values.",),
        falsifiers=("The rule is falsified when shared values remain coherent or every legitimate change is surfaced with updated dependent state before commitment.",),
        repairs=("Bind shared representations to a single authoritative state model and explicitly invalidate or recompute dependent values when that state changes.",),
        verification=("Exercise forward, backward, edit, retry, and refresh transitions with distinctive values and verify that no contradictory actionable state is reachable.",),
        owner_skill_ids=("tracing-cross-step-state",),
    ),
    _rule(
        rule_id="ux.flow.stale-task-context-revalidated",
        domain="journey-flow",
        mechanism_id="state-without-explanation",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Revalidate stale task context before consequential continuation",
        statement="A resumed task must revalidate context that may have become stale before using it for consequential continuation.",
        applies_when=("A task can resume after time or external activity may change availability, authority, price, membership, version, permissions, or another outcome-relevant dependency.",),
        failure_modes=("The product restores previously valid task context and allows consequential continuation without checking dependencies that can become invalid while paused.",),
        user_impacts=("The user can act confidently on a context that was valid when captured but is no longer authoritative at the moment of continuation.",),
        observables=("Pause the task, mutate an outcome-relevant dependency externally, then resume and observe whether old context remains actionable without revalidation.",),
        falsifiers=("The rule is falsified when stale-capable dependencies are revalidated before consequential continuation and material changes are exposed to the user.",),
        repairs=("Tag stale-capable context with freshness requirements and revalidate it at resume boundaries before allowing dependent consequential actions.",),
        verification=("Change each modeled stale-capable dependency during interruption and verify that resumed actions cannot proceed under obsolete assumptions.",),
        owner_skill_ids=("designing-cross-session-continuity", "assessing-recovery-completeness"),
    ),
    _rule(
        rule_id="ux.friction.no-semantically-redundant-reentry",
        domain="cognitive-friction",
        mechanism_id="unnecessary-recall",
        rule_class="contextual",
        severity="moderate",
        enforcement="warn",
        title="Challenge semantically redundant re-entry",
        statement="Do not require users to reconstruct known information unless fresh entry provides meaningful verification, security, intent, or freshness evidence.",
        applies_when=("The product already possesses information needed by a later step and asks the same user to type or reconstruct equivalent information again.",),
        failure_modes=("Repeated entry creates no new proof, consent, freshness, security, or disambiguation and exists only because workflow surfaces do not share known state.",),
        user_impacts=("The user spends attention reproducing known state and may introduce discrepancies between values that should represent the same task information.",),
        observables=("Trace each repeated input to its earlier authoritative source and identify what new semantic evidence, if any, the repeated entry creates.",),
        falsifiers=("The concern is falsified when fresh entry intentionally creates necessary proof, security, freshness, consent, or disambiguation that safe reuse cannot provide.",),
        repairs=("Reuse or visibly pre-populate still-valid known state while preserving explicit fresh confirmation where that confirmation has a documented semantic purpose.",),
        verification=("Review the repaired path with the repeated field's authority and security requirements and confirm that removed re-entry did not remove necessary evidence.",),
        owner_skill_ids=("reducing-redundant-input",),
    ),
    _rule(
        rule_id="ux.ia.navigation-preserves-object-identity",
        domain="information-architecture",
        mechanism_id="navigation-disorientation",
        rule_class="structural",
        severity="major",
        enforcement="block",
        title="Preserve active object identity across navigation",
        statement="Navigation inside an object-centered task must preserve enough identity evidence to prevent acting on the wrong object.",
        applies_when=("A user navigates among views that can display or mutate different instances of the same object type during one continuing task.",),
        failure_modes=("A destination becomes actionable without a persistent identity cue that distinguishes the active object from other plausible objects in the same task.",),
        user_impacts=("The user can perform the intended action correctly but apply it to a different object because navigation obscured the active object's identity.",),
        observables=("Open two similar objects with deliberately distinct identities and traverse all task navigation paths while recording identity cues at actionable destinations.",),
        falsifiers=("The rule is falsified when every actionable object view exposes stable identity cues sufficient to distinguish the active instance within the task context.",),
        repairs=("Carry stable object identity through routes and state, and expose discriminating identity cues near actions whose outcome depends on the active object.",),
        verification=("Repeat the navigation test using visually similar object instances and verify that a user can distinguish the active target before every consequential action.",),
        owner_skill_ids=("modeling-object-continuity", "preserving-location-awareness"),
    ),
    _rule(
        rule_id="ux.mental-model.product-terms-match-user-concepts",
        domain="mental-model",
        mechanism_id="mental-model-mismatch",
        rule_class="contextual",
        severity="moderate",
        enforcement="review",
        title="Challenge terminology that exposes the wrong conceptual model",
        statement="Primary product terminology should preserve distinctions users need to predict behavior rather than expose unexplained implementation concepts.",
        applies_when=("User-facing labels introduce domain entities, state names, actions, or relationships that materially influence how users predict product behavior.",),
        failure_modes=("Primary terminology maps poorly to established user concepts or collapses distinctions needed to predict scope, ownership, state, or consequences.",),
        user_impacts=("Users may form a plausible but incorrect model of product behavior and repeatedly make errors even when individual controls function correctly.",),
        observables=("Compare product terminology with representative task language and ask users or domain evidence what behavior each key term predicts before interaction.",),
        falsifiers=("The review concern is falsified when intended users consistently map the terminology to the product's actual conceptual distinctions and predicted behavior.",),
        repairs=("Rename or explain concepts around user-domain distinctions while retaining specialized terminology where it is established and useful to the intended audience.",),
        verification=("Repeat prediction-oriented comprehension review with representative users or authoritative domain evidence rather than relying on designer familiarity alone.",),
        owner_skill_ids=("aligning-conceptual-models", "writing-domain-aligned-language"),
    ),
    _rule(
        rule_id="ux.recovery.dead-end-has-recovery-path",
        domain="recovery",
        mechanism_id="workflow-fragmentation",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Recoverable failures must expose a viable next path",
        statement="A recoverable failure state must not strand the user without a route to retry, revise, return, or otherwise reach a valid task state.",
        applies_when=("A task enters an error, unavailable, rejected, conflict, expired, or partial state that the product considers recoverable by user or system action.",),
        failure_modes=("The failure state explains or displays the problem but exposes no viable action or route that can reach a valid continuation or safe exit state.",),
        user_impacts=("The user must abandon the task, reconstruct navigation manually, or guess an undocumented recovery sequence despite the failure being recoverable.",),
        observables=("Force each modeled recoverable failure and enumerate visible actions, keyboard routes, links, automatic transitions, and preserved context from that state.",),
        falsifiers=("The rule is falsified when every recoverable failure exposes at least one viable, comprehensible route to continuation, revision, retry, or safe exit.",),
        repairs=("Add a recovery action tied to the actual failure cause and preserve enough task context for that action to return to a valid continuation state.",),
        verification=("Trigger every supported recoverable failure and execute each offered recovery path through to a valid state without relying on hidden navigation knowledge.",),
        owner_skill_ids=("designing-error-recovery-paths",),
    ),
    _rule(
        rule_id="ux.recovery.progress-not-silently-destroyed",
        domain="recovery",
        mechanism_id="unrecoverable-progress-loss",
        rule_class="behavioral",
        severity="critical",
        enforcement="block",
        title="Do not silently destroy valuable in-progress work",
        statement="Predictable transitions must not discard valuable user-authored progress without explicit discard intent or a viable restoration path.",
        applies_when=("The user has created task state that is costly to reconstruct and a predictable navigation, expiry, retry, close, refresh, or failure transition can discard it.",),
        failure_modes=("A predictable transition destroys valuable in-progress state without explicit discard authorization, adequate consequence warning, or recoverable preservation.",),
        user_impacts=("The user loses authored work or completed task progress despite not choosing to abandon it and must reproduce effort that the product could preserve.",),
        observables=("Create distinctive in-progress state and execute every modeled navigation, expiry, retry, close, refresh, and recoverable failure transition that can discard it.",),
        falsifiers=("The rule is falsified when valuable progress survives, is restorable, or is discarded only after an explicit action whose consequence was visible beforehand.",),
        repairs=("Persist valuable progress across predictable interruption boundaries or introduce an explicit consequence-aware discard decision before irreversible destruction.",),
        verification=("Repeat each destructive transition with distinctive authored progress and verify preservation, restoration, or explicit authorized discard behavior end to end.",),
        owner_skill_ids=("designing-progress-preservation", "verifying-interruption-recovery"),
    ),
    _rule(
        rule_id="ux.recovery.recovery-path-is-reachable",
        domain="recovery",
        mechanism_id="workflow-fragmentation",
        rule_class="structural",
        severity="major",
        enforcement="block",
        title="Recovery paths must be reachable from the failure state",
        statement="A documented recovery capability does not count unless the affected user can reach it from the actual failure context.",
        applies_when=("The product claims a recovery route for a failure but navigation, permissions, modality, or lost context can prevent the affected user from reaching it.",),
        failure_modes=("Recovery exists elsewhere in the product but the failure state provides no reachable route, required context is lost, or the affected permission state blocks access.",),
        user_impacts=("A nominally recoverable failure becomes practically unrecoverable for the user experiencing it because recovery depends on inaccessible product knowledge or state.",),
        observables=("Enter the failure as the affected user and attempt recovery using only routes and context that remain available from that exact failure state.",),
        falsifiers=("The rule is falsified when the affected user can reach and complete a viable recovery path directly from the failure context with required state preserved.",),
        repairs=("Connect the failure state to the recovery surface, carry required identifiers and context, and ensure the affected permission state can perform the intended recovery.",),
        verification=("Test recovery from the real failure state under each relevant role, navigation mode, and context-loss boundary rather than deep-linking directly to recovery.",),
        owner_skill_ids=("assessing-recovery-completeness", "designing-error-recovery-paths"),
    ),
    _rule(
        rule_id="ux.task.hidden-dependency-before-commit",
        domain="goal-task",
        mechanism_id="hidden-dependency",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Expose knowable blocking dependencies before commitment",
        statement="A knowable prerequisite that can invalidate a consequential commitment must be surfaced before the user commits dependent work.",
        applies_when=("A consequential action depends on permission, availability, prerequisite state, external resource, required configuration, or another dependency knowable before commit.",),
        failure_modes=("The interface presents the dependent commitment as viable even though a known unmet prerequisite will necessarily reject or materially change the outcome.",),
        user_impacts=("The user invests or commits effort under a false assumption of viability and discovers a deterministic blocker only after the costly decision point.",),
        observables=("Arrange each known unmet prerequisite and inspect whether the dependent action remains apparently viable through the final pre-commit state.",),
        falsifiers=("The rule is falsified when known unmet prerequisites are surfaced early enough to change the user's plan or safely resolved before dependent commitment.",),
        repairs=("Evaluate knowable blockers before commitment and expose the prerequisite, affected outcome, and viable resolution path at the earliest decision-relevant point.",),
        verification=("Test every modeled knowable prerequisite in unmet and satisfied states and verify that viability claims and commit affordances track the dependency accurately.",),
        owner_skill_ids=("designing-contextual-explanations", "structuring-complex-decisions"),
    ),
    _rule(
        rule_id="ux.task.no-premature-commitment",
        domain="goal-task",
        mechanism_id="premature-commitment",
        rule_class="contextual",
        severity="moderate",
        enforcement="warn",
        title="Challenge commitments made before decision-relevant information exists",
        statement="Avoid forcing costly or constraining choices before the information that materially differentiates those choices can naturally be known.",
        applies_when=("A workflow asks the user to choose an irreversible, expensive, long-lived, or strongly constraining option before later steps expose decision-relevant information.",),
        failure_modes=("The user must commit before seeing information that predictably changes which option is appropriate, while safe deferral or reversibility is feasible.",),
        user_impacts=("Users can make rational decisions with the information available at the time yet still be locked into avoidably poor outcomes once later information appears.",),
        observables=("Trace when each decision-relevant fact becomes available and compare that point with the earliest state where the constraining choice becomes committed.",),
        falsifiers=("The concern is falsified when early commitment is necessary for later information to exist, remains safely reversible, or does not precede material differentiating evidence.",),
        repairs=("Defer commitment until material evidence is available, make the early choice reversible, or expose representative consequence information before the commitment point.",),
        verification=("Walk the full decision sequence with contrasting scenarios and verify that material evidence appears before the point at which changing course becomes costly.",),
        owner_skill_ids=("analyzing-task-frequency-criticality", "structuring-complex-decisions"),
    ),
    _rule(
        rule_id="ux.task.same-goal-navigation-preserves-context",
        domain="goal-task",
        mechanism_id="context-loss",
        rule_class="behavioral",
        severity="major",
        enforcement="block",
        title="Preserve still-relevant context inside one user goal",
        statement="Navigation between surfaces serving one continuing goal must not silently discard still-relevant task context.",
        applies_when=("The user moves between surfaces, steps, tabs, detail views, or supporting information while still pursuing the same identifiable task outcome.",),
        failure_modes=("A within-goal navigation transition clears selection, entered criteria, working scope, position, comparison state, or other context still needed to continue.",),
        user_impacts=("The user must reconstruct work after ordinary exploration or can continue under reset defaults that no longer represent the intent established earlier.",),
        observables=("Set distinctive task context, traverse each supporting navigation path, return or continue, and compare preserved state with the context still required by the goal.",),
        falsifiers=("The rule is falsified when relevant context survives within-goal navigation or any reset is explicit because the user actually started a new independent task.",),
        repairs=("Carry still-relevant task context across within-goal navigation and define explicit semantic boundaries where a new task intentionally resets prior context.",),
        verification=("Exercise within-goal navigation with non-default state and verify that task-relevant context persists until an explicit new-task or discard boundary is crossed.",),
        owner_skill_ids=("distinguishing-goals-from-interface-actions", "minimizing-context-switching"),
    ),
), key=lambda item: item["rule_id"]))


__all__ = ["UX_RULES"]
