"""Canonical UX cognitive operations.

A skill is a reasoning operation an agent can perform. It is not a rule and
must not be interpreted as evidence that a product is good or bad.
"""

from __future__ import annotations


UX_SKILLS = tuple(sorted((
    # goal-task
    {"skill_id": "identifying-user-goals", "domain": "goal-task", "title": "Identify user goals", "purpose": "Separate the outcome a user seeks from the controls and screens used to reach it.", "questions": ("What outcome would still matter if the current interface disappeared?",), "outputs": ("A goal statement with actor, desired outcome, context, and success evidence.",), "anti_patterns": ("Restating navigation destinations or product features as user goals.",), "related_mechanisms": ("goal-displacement",)},
    {"skill_id": "distinguishing-goals-from-interface-actions", "domain": "goal-task", "title": "Distinguish goals from interface actions", "purpose": "Detect when a proposed journey optimizes clicks or screens instead of the real outcome.", "questions": ("Is each action necessary for the goal, or only necessary for the current implementation?",), "outputs": ("A goal-to-action map separating essential task work from interface ceremony.",), "anti_patterns": ("Treating completion of a form or wizard as the user's underlying goal.",), "related_mechanisms": ("goal-displacement", "workflow-fragmentation")},
    {"skill_id": "analyzing-task-frequency-criticality", "domain": "goal-task", "title": "Analyze task frequency and criticality", "purpose": "Reason differently about frequent operational tasks, rare setup tasks, and consequential exceptional tasks.", "questions": ("How often is the task performed, how costly is failure, and how much expertise is expected?",), "outputs": ("A frequency-criticality profile that informs prioritization and interaction cost trade-offs.",), "anti_patterns": ("Applying the same friction and guidance strategy to every task regardless of consequence.",), "related_mechanisms": ("decision-overload", "premature-commitment")},
    {"skill_id": "modeling-expert-novice-workflows", "domain": "goal-task", "title": "Model expert and novice workflows", "purpose": "Preserve learnability without forcing experienced users through novice ceremony on repeated tasks.", "questions": ("Which knowledge grows with use, and where should the interface expose acceleration without hiding meaning?",), "outputs": ("A workflow model describing novice support, expert acceleration, and shared invariant states.",), "anti_patterns": ("Assuming either all users are beginners or all users already understand the domain.",), "related_mechanisms": ("decision-overload", "unnecessary-recall")},

    # mental-model
    {"skill_id": "aligning-conceptual-models", "domain": "mental-model", "title": "Align conceptual models", "purpose": "Make product concepts and relationships predictable from the user's domain understanding.", "questions": ("What objects and relationships does the user believe exist, and where does the product model diverge?",), "outputs": ("A conceptual-model map with intentional translations between user and system concepts.",), "anti_patterns": ("Exposing internal architecture as primary product vocabulary without translation.",), "related_mechanisms": ("mental-model-mismatch",)},
    {"skill_id": "modeling-object-continuity", "domain": "mental-model", "title": "Model object continuity", "purpose": "Preserve perceived identity of the same object across navigation, editing, asynchronous updates, and representations.", "questions": ("How does the user know this is still the same object after the transition?",), "outputs": ("Identity cues and continuity requirements across representations and states.",), "anti_patterns": ("Changing labels, identifiers, or interaction semantics so the same object appears unrelated.",), "related_mechanisms": ("mental-model-mismatch", "navigation-disorientation", "context-loss")},
    {"skill_id": "testing-mental-model-alignment", "domain": "mental-model", "title": "Test mental-model alignment", "purpose": "Evaluate whether users can predict interface behavior from concepts already established by the product or domain.", "questions": ("Can a representative user predict what will happen before operating the control?",), "outputs": ("Prediction mismatches tied to specific concepts and observable interaction consequences.",), "anti_patterns": ("Calling a pattern intuitive without testing what users actually predict.",), "related_mechanisms": ("mental-model-mismatch", "ambiguous-consequence")},
    {"skill_id": "writing-domain-aligned-language", "domain": "mental-model", "title": "Write domain-aligned language", "purpose": "Use terminology that preserves domain distinctions and makes consequences legible to the intended audience.", "questions": ("Does each important label mean what the intended user would reasonably infer in this domain?",), "outputs": ("A terminology map for canonical user-facing concepts, actions, states, and disambiguators.",), "anti_patterns": ("Replacing precise domain concepts with generic product or marketing vocabulary.",), "related_mechanisms": ("mental-model-mismatch", "ambiguous-consequence")},

    # information-architecture
    {"skill_id": "architecting-goal-oriented-navigation", "domain": "information-architecture", "title": "Architect goal-oriented navigation", "purpose": "Organize major destinations around recurring work and orientation needs rather than fashionable product shells.", "questions": ("Which recurring goals justify each top-level destination, and which destinations merely mirror implementation structure?",), "outputs": ("A navigation model tracing destinations to recurring user goals and return paths.",), "anti_patterns": ("Defaulting to Dashboard, Projects, Analytics, and Settings without task evidence.",), "related_mechanisms": ("goal-displacement", "navigation-disorientation")},
    {"skill_id": "grouping-information-by-user-intent", "domain": "information-architecture", "title": "Group information by user intent", "purpose": "Group information according to questions and decisions users make rather than storage schema alone.", "questions": ("What decision or task causes these pieces of information to be needed together?",), "outputs": ("Intent-based groupings with explicit rationale and conflicting grouping needs.",), "anti_patterns": ("Using database entities as the default information architecture without task validation.",), "related_mechanisms": ("goal-displacement", "decision-overload")},
    {"skill_id": "preserving-location-awareness", "domain": "information-architecture", "title": "Preserve location awareness", "purpose": "Keep users oriented to current location, active object, parent context, and meaningful exit paths.", "questions": ("After arriving here, what evidence tells the user where they are and what scope they are operating on?",), "outputs": ("Orientation cues for location, object identity, parent scope, and return path.",), "anti_patterns": ("Relying on browser history or memory as the only way to reconstruct location.",), "related_mechanisms": ("navigation-disorientation", "context-loss")},
    {"skill_id": "testing-information-findability", "domain": "information-architecture", "title": "Test information findability", "purpose": "Evaluate whether users can locate needed information from realistic starting contexts and vocabulary.", "questions": ("Where would a user look first, and does navigation scent support that prediction?",), "outputs": ("Findability paths, failed first-look locations, and ambiguous category labels.",), "anti_patterns": ("Declaring content discoverable because it exists somewhere in the hierarchy.",), "related_mechanisms": ("navigation-disorientation", "mental-model-mismatch")},

    # journey-flow
    {"skill_id": "mapping-critical-user-journeys", "domain": "journey-flow", "title": "Map critical user journeys", "purpose": "Model complete high-value journeys across entry, progress, interruption, exceptional states, and completion.", "questions": ("What must remain true from the user's initial intent through authoritative completion?",), "outputs": ("A stateful journey map including normal, interrupted, failed, and recovery paths.",), "anti_patterns": ("Mapping only the happy path between polished screens.",), "related_mechanisms": ("workflow-fragmentation", "false-completion", "unrecoverable-progress-loss")},
    {"skill_id": "optimizing-critical-task-paths", "domain": "journey-flow", "title": "Optimize critical task paths", "purpose": "Remove nonessential ceremony while preserving information, safeguards, and decisions needed for correct completion.", "questions": ("Which step changes outcome quality or safety, and which step merely reflects implementation convenience?",), "outputs": ("A critical path with necessary decisions distinguished from removable interaction cost.",), "anti_patterns": ("Optimizing solely for minimum click count or minimum screen count.",), "related_mechanisms": ("workflow-fragmentation", "premature-commitment", "decision-overload")},
    {"skill_id": "designing-cross-session-continuity", "domain": "journey-flow", "title": "Design cross-session continuity", "purpose": "Preserve task identity and meaningful progress across predictable pauses, expiry, device changes, and resumptions.", "questions": ("What context must survive for the user to resume without reconstructing the task?",), "outputs": ("A continuity contract for persisted state, freshness checks, and intentional reset boundaries.",), "anti_patterns": ("Treating every new session as a new user goal by default.",), "related_mechanisms": ("context-loss", "unrecoverable-progress-loss", "state-without-explanation")},
    {"skill_id": "tracing-cross-step-state", "domain": "journey-flow", "title": "Trace cross-step state", "purpose": "Track shared choices, derived values, and authoritative changes across multi-step workflows.", "questions": ("Which state is shared across steps, where is it authoritative, and what can invalidate it?",), "outputs": ("A cross-step state trace with invalidation and revalidation points.",), "anti_patterns": ("Treating each screen as independent when the user experiences one continuous task.",), "related_mechanisms": ("cross-step-inconsistency", "state-without-explanation", "context-loss")},

    # cognitive-friction
    {"skill_id": "auditing-decision-friction", "domain": "cognitive-friction", "title": "Audit decision friction", "purpose": "Distinguish useful deliberation from friction that consumes attention without improving the decision.", "questions": ("Which effort improves correctness, confidence, or safety, and which effort only decodes the interface?",), "outputs": ("A friction audit separating protective, informational, and wasteful effort.",), "anti_patterns": ("Assuming all friction is harmful or all confirmation is beneficial.",), "related_mechanisms": ("decision-overload", "ambiguous-consequence")},
    {"skill_id": "minimizing-context-switching", "domain": "cognitive-friction", "title": "Minimize context switching", "purpose": "Reduce unnecessary changes of surface, vocabulary, object context, or mental mode inside one task.", "questions": ("Does this transition require the user to reconstruct intent, state, or terminology before continuing?",), "outputs": ("A context-switch map identifying transitions that require avoidable reconstruction.",), "anti_patterns": ("Counting screens while ignoring whether each transition preserves task context.",), "related_mechanisms": ("context-loss", "workflow-fragmentation")},
    {"skill_id": "reducing-redundant-input", "domain": "cognitive-friction", "title": "Reduce redundant input", "purpose": "Reuse or surface known state when re-entry adds no semantic verification, freshness, or security value.", "questions": ("Why must the user provide this again, and what new evidence does re-entry create?",), "outputs": ("A redundant-input audit distinguishing justified fresh proof from needless reconstruction.",), "anti_patterns": ("Autofilling state whose freshness or authority must be actively reconfirmed.",), "related_mechanisms": ("unnecessary-recall",)},
    {"skill_id": "structuring-complex-decisions", "domain": "cognitive-friction", "title": "Structure complex decisions", "purpose": "Sequence and compare decision-relevant information without hiding material trade-offs or presenting irrelevant choices too early.", "questions": ("What distinctions materially change the decision, and when does each distinction become relevant?",), "outputs": ("A decision structure with trade-offs, dependencies, defaults, and deferrable choices.",), "anti_patterns": ("Flattening every option into an equal-weight list or hiding trade-offs behind a recommended badge.",), "related_mechanisms": ("decision-overload", "hidden-dependency", "premature-commitment")},

    # comprehension
    {"skill_id": "clarifying-action-consequences", "domain": "comprehension", "title": "Clarify action consequences", "purpose": "Ensure labels, surrounding context, and confirmations reveal material outcomes before commitment.", "questions": ("Can the user state what will change, for whom, and whether it can be reversed before acting?",), "outputs": ("A consequence model for material actions including scope, permanence, and authoritative outcome.",), "anti_patterns": ("Using generic labels such as Continue or Confirm where the committed consequence is material.",), "related_mechanisms": ("ambiguous-consequence", "premature-commitment")},
    {"skill_id": "designing-contextual-explanations", "domain": "comprehension", "title": "Design contextual explanations", "purpose": "Explain unexpected or consequential state changes at the moment users need causal context.", "questions": ("What changed, why does it matter now, and what can the user do next?",), "outputs": ("Explanation requirements bound to state transitions and user decisions.",), "anti_patterns": ("Moving essential explanations to documentation that users must discover after failure.",), "related_mechanisms": ("state-without-explanation", "hidden-dependency")},
    {"skill_id": "designing-recognition-over-recall", "domain": "comprehension", "title": "Design recognition over recall", "purpose": "Expose known choices and context when recognition is safer and easier than reconstructing them from memory.", "questions": ("Which known state should be visible while the user makes this decision?",), "outputs": ("Recognition cues for prior choices, comparison baselines, and active context.",), "anti_patterns": ("Hiding state merely to make a screen visually simpler while increasing memory burden.",), "related_mechanisms": ("unnecessary-recall", "context-loss")},
    {"skill_id": "validating-navigation-scent", "domain": "comprehension", "title": "Validate navigation scent", "purpose": "Check whether destination labels and surrounding cues let users predict where a route leads and what scope it affects.", "questions": ("Before following this route, can the user predict its destination and relation to the current task?",), "outputs": ("Navigation-scent findings tied to ambiguous labels, grouping, and destination expectations.",), "anti_patterns": ("Using short generic labels whose meaning depends on unexplained internal structure.",), "related_mechanisms": ("navigation-disorientation", "mental-model-mismatch")},

    # recovery
    {"skill_id": "designing-error-recovery-paths", "domain": "recovery", "title": "Design error recovery paths", "purpose": "Turn recoverable failures into states with preserved context, actionable cause, and a viable next move.", "questions": ("After this failure, what valid state can the user reach without restarting unrelated work?",), "outputs": ("Recovery routes mapped from failure states to valid continuation states.",), "anti_patterns": ("Showing an error message that explains failure but provides no viable continuation route.",), "related_mechanisms": ("workflow-fragmentation", "unrecoverable-progress-loss")},
    {"skill_id": "designing-progress-preservation", "domain": "recovery", "title": "Design progress preservation", "purpose": "Protect valuable in-progress work across expected failure, expiry, navigation, retry, and interruption boundaries.", "questions": ("Which authored state is expensive to reconstruct, and under which events may it legitimately be discarded?",), "outputs": ("A preservation policy with persistence, discard authority, and restoration behavior.",), "anti_patterns": ("Equating unsaved with disposable when the system can predict common interruption modes.",), "related_mechanisms": ("unrecoverable-progress-loss", "context-loss")},
    {"skill_id": "assessing-recovery-completeness", "domain": "recovery", "title": "Assess recovery completeness", "purpose": "Verify that recovery restores not just data but the task context required to continue correctly.", "questions": ("After recovery, are object identity, selection, scope, dependencies, and freshness still valid?",), "outputs": ("A recovery completeness assessment covering restored data and revalidated context.",), "anti_patterns": ("Calling recovery complete because text values reappeared while task scope or authority changed.",), "related_mechanisms": ("context-loss", "state-without-explanation", "cross-step-inconsistency")},
    {"skill_id": "verifying-interruption-recovery", "domain": "recovery", "title": "Verify interruption recovery", "purpose": "Exercise realistic interruption points and verify safe resumption, revalidation, and intentional reset behavior.", "questions": ("What happens if the user leaves, reloads, expires, or loses connectivity at each critical point?",), "outputs": ("An interruption matrix with resume evidence and unresolved recovery gaps.",), "anti_patterns": ("Testing only clean completion and treating refresh behavior as an implementation detail.",), "related_mechanisms": ("unrecoverable-progress-loss", "context-loss", "state-without-explanation")},

    # evaluation
    {"skill_id": "conducting-cognitive-walkthroughs", "domain": "evaluation", "title": "Conduct cognitive walkthroughs", "purpose": "Evaluate whether a user can discover, interpret, execute, and learn each required action from realistic prior knowledge.", "questions": ("Will the user know what to do, notice the control, understand its meaning, and connect feedback to progress?",), "outputs": ("Step-level learnability findings with evidence and uncertainty rather than taste judgments.",), "anti_patterns": ("Walking through as the designer who already knows the intended flow.",), "related_mechanisms": ("mental-model-mismatch", "navigation-disorientation", "workflow-fragmentation")},
    {"skill_id": "evaluating-first-value-paths", "domain": "evaluation", "title": "Evaluate first-value paths", "purpose": "Assess whether initial setup and onboarding move users toward a real first outcome rather than merely introducing features.", "questions": ("What is the earliest meaningful outcome, and does every required onboarding step help reach it safely?",), "outputs": ("A first-value path with removable setup ceremony and necessary prerequisite evidence.",), "anti_patterns": ("Measuring onboarding success by completion of tours rather than achievement of user value.",), "related_mechanisms": ("goal-displacement", "workflow-fragmentation", "decision-overload")},
    {"skill_id": "evaluating-task-success", "domain": "evaluation", "title": "Evaluate task success", "purpose": "Judge UX against observable user outcomes, correctness, recovery, and confidence rather than surface polish alone.", "questions": ("Did the user reach the intended authoritative outcome correctly, and what errors or recovery costs occurred?",), "outputs": ("Task-success evidence with completion, correctness, error, recovery, and uncertainty dimensions.",), "anti_patterns": ("Treating click completion or subjective preference as sufficient proof of UX quality.",), "related_mechanisms": ("false-completion", "cross-step-inconsistency")},
    {"skill_id": "measuring-workflow-friction", "domain": "evaluation", "title": "Measure workflow friction", "purpose": "Measure effort in relation to task value and correctness instead of assuming fewer interactions are always better.", "questions": ("Which observed effort is necessary, protective, explanatory, or avoidable for this task and audience?",), "outputs": ("A friction profile combining interaction effort, cognitive reconstruction, errors, and protective safeguards.",), "anti_patterns": ("Using click count or time-on-task alone as a universal quality score.",), "related_mechanisms": ("decision-overload", "unnecessary-recall", "workflow-fragmentation")},
), key=lambda item: item["skill_id"]))


__all__ = ["UX_SKILLS"]
