"""Independently reviewable V13 rule shards."""

from .accessibility_advanced import ACCESSIBILITY_ADVANCED_RULES_V13
from .accessibility_input import ACCESSIBILITY_INPUT_RULES_V13
from .ai_agent import AI_AGENT_RULES_V13
from .commerce import COMMERCE_RULES_V13
from .collaboration_realtime import COLLABORATION_REALTIME_RULES_V13
from .consent_controls import CONSENT_CONTROL_RULES_V13
from .data_viz import DATA_VIZ_RULES_V13
from .device_capture import DEVICE_CAPTURE_RULES_V13
from .editor_workspace import EDITOR_WORKSPACE_RULES_V13
from .file_lifecycle import FILE_LIFECYCLE_RULES_V13
from .finance_admin import FINANCE_ADMIN_RULES_V13
from .forms_auth import FORMS_AUTH_RULES_V13
from .foundation import FOUNDATION_RULES_V13
from .history_destructive import HISTORY_DESTRUCTIVE_RULES_V13
from .import_export_migration import IMPORT_EXPORT_MIGRATION_RULES_V13
from .localization_search import LOCALIZATION_SEARCH_RULES_V13
from .messaging import MESSAGING_RULES_V13
from .mobile_responsive import MOBILE_RESPONSIVE_RULES_V13
from .navigation_resilience import NAVIGATION_RESILIENCE_RULES_V13
from .notification_background import NOTIFICATION_BACKGROUND_RULES_V13
from .performance_media import PERFORMANCE_MEDIA_RULES_V13
from .privacy_security import PRIVACY_SECURITY_RULES_V13
from .scheduling_timezone import SCHEDULING_TIMEZONE_RULES_V13
from .sync_freshness import SYNC_FRESHNESS_RULES_V13

FIRST_WAVE_RULES_V13 = (
    AI_AGENT_RULES_V13
    + FORMS_AUTH_RULES_V13
    + DATA_VIZ_RULES_V13
    + EDITOR_WORKSPACE_RULES_V13
    + COMMERCE_RULES_V13
)
FIRST_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in FIRST_WAVE_RULES_V13)

SECOND_WAVE_RULES_V13 = (
    ACCESSIBILITY_INPUT_RULES_V13
    + NAVIGATION_RESILIENCE_RULES_V13
    + PRIVACY_SECURITY_RULES_V13
    + MOBILE_RESPONSIVE_RULES_V13
    + PERFORMANCE_MEDIA_RULES_V13
    + LOCALIZATION_SEARCH_RULES_V13
)
SECOND_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in SECOND_WAVE_RULES_V13)

THIRD_WAVE_RULES_V13 = (
    COLLABORATION_REALTIME_RULES_V13
    + FILE_LIFECYCLE_RULES_V13
    + NOTIFICATION_BACKGROUND_RULES_V13
    + SYNC_FRESHNESS_RULES_V13
    + HISTORY_DESTRUCTIVE_RULES_V13
    + FINANCE_ADMIN_RULES_V13
)
THIRD_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in THIRD_WAVE_RULES_V13)

FOURTH_WAVE_RULES_V13 = (
    SCHEDULING_TIMEZONE_RULES_V13
    + MESSAGING_RULES_V13
    + IMPORT_EXPORT_MIGRATION_RULES_V13
    + DEVICE_CAPTURE_RULES_V13
    + CONSENT_CONTROL_RULES_V13
    + ACCESSIBILITY_ADVANCED_RULES_V13
)
FOURTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in FOURTH_WAVE_RULES_V13)

__all__ = [
    "ACCESSIBILITY_ADVANCED_RULES_V13",
    "ACCESSIBILITY_INPUT_RULES_V13",
    "AI_AGENT_RULES_V13",
    "COMMERCE_RULES_V13",
    "CONSENT_CONTROL_RULES_V13",
    "DATA_VIZ_RULES_V13",
    "DEVICE_CAPTURE_RULES_V13",
    "EDITOR_WORKSPACE_RULES_V13",
    "FIRST_WAVE_RULE_IDS",
    "FIRST_WAVE_RULES_V13",
    "FORMS_AUTH_RULES_V13",
    "FOUNDATION_RULES_V13",
    "FOURTH_WAVE_RULE_IDS",
    "FOURTH_WAVE_RULES_V13",
    "IMPORT_EXPORT_MIGRATION_RULES_V13",
    "LOCALIZATION_SEARCH_RULES_V13",
    "MESSAGING_RULES_V13",
    "MOBILE_RESPONSIVE_RULES_V13",
    "NAVIGATION_RESILIENCE_RULES_V13",
    "PERFORMANCE_MEDIA_RULES_V13",
    "PRIVACY_SECURITY_RULES_V13",
    "SCHEDULING_TIMEZONE_RULES_V13",
    "SECOND_WAVE_RULE_IDS",
    "SECOND_WAVE_RULES_V13",
    "COLLABORATION_REALTIME_RULES_V13",
    "FILE_LIFECYCLE_RULES_V13",
    "FINANCE_ADMIN_RULES_V13",
    "HISTORY_DESTRUCTIVE_RULES_V13",
    "NOTIFICATION_BACKGROUND_RULES_V13",
    "SYNC_FRESHNESS_RULES_V13",
    "THIRD_WAVE_RULE_IDS",
    "THIRD_WAVE_RULES_V13",
]
