"""Independently reviewable V13 rule shards."""

from .accessibility_advanced import ACCESSIBILITY_ADVANCED_RULES_V13
from .accessibility_input import ACCESSIBILITY_INPUT_RULES_V13
from .ai_agent import AI_AGENT_RULES_V13
from .commerce import COMMERCE_RULES_V13
from .collaboration_realtime import COLLABORATION_REALTIME_RULES_V13
from .consent_controls import CONSENT_CONTROL_RULES_V13
from .file_lifecycle import FILE_LIFECYCLE_RULES_V13
from .finance_admin import FINANCE_ADMIN_RULES_V13
from .history_destructive import HISTORY_DESTRUCTIVE_RULES_V13
from .notification_background import NOTIFICATION_BACKGROUND_RULES_V13
from .scheduling_timezone import SCHEDULING_TIMEZONE_RULES_V13
from .sync_freshness import SYNC_FRESHNESS_RULES_V13
from .agent_runtime_authority import AGENT_RUNTIME_AUTHORITY_RULES_V13
from .comments_moderation import COMMENTS_MODERATION_RULES_V13
from .commerce_high_consequence import COMMERCE_HIGH_CONSEQUENCE_RULES_V13
from .identity_session import IDENTITY_SESSION_RULES_V13
from .map_location import MAP_LOCATION_RULES_V13
from .media_playback_access import MEDIA_PLAYBACK_ACCESS_RULES_V13
from .native_device_handoff import NATIVE_DEVICE_HANDOFF_RULES_V13
from .notification_attention import NOTIFICATION_ATTENTION_RULES_V13
from .offline_connectivity import OFFLINE_CONNECTIVITY_RULES_V13
from .onboarding_permissions import ONBOARDING_PERMISSIONS_RULES_V13
from .search_recommendation import SEARCH_RECOMMENDATION_RULES_V13
from .table_grid import TABLE_GRID_RULES_V13
from .data_viz import DATA_VIZ_RULES_V13
from .device_capture import DEVICE_CAPTURE_RULES_V13
from .editor_workspace import EDITOR_WORKSPACE_RULES_V13
from .forms_auth import FORMS_AUTH_RULES_V13
from .foundation import FOUNDATION_RULES_V13
from .import_export_migration import IMPORT_EXPORT_MIGRATION_RULES_V13
from .localization_search import LOCALIZATION_SEARCH_RULES_V13
from .messaging import MESSAGING_RULES_V13
from .mobile_responsive import MOBILE_RESPONSIVE_RULES_V13
from .navigation_resilience import NAVIGATION_RESILIENCE_RULES_V13
from .performance_media import PERFORMANCE_MEDIA_RULES_V13
from .privacy_security import PRIVACY_SECURITY_RULES_V13

from .roles_permissions import ROLES_PERMISSIONS_RULES_V13
from .settings_preferences import SETTINGS_PREFERENCES_RULES_V13
from .command_keyboard import COMMAND_KEYBOARD_RULES_V13
from .dashboard_monitoring import DASHBOARD_MONITORING_RULES_V13
from .download_export import DOWNLOAD_EXPORT_RULES_V13
from .upload_import import UPLOAD_IMPORT_RULES_V13
from .voice_audio_input import VOICE_AUDIO_INPUT_RULES_V13
from .tv_remote import TV_REMOTE_RULES_V13
from .spatial_xr import SPATIAL_XR_RULES_V13
from .wearable_glance import WEARABLE_GLANCE_RULES_V13
from .print_output import PRINT_OUTPUT_RULES_V13
from .workflow_multistep import WORKFLOW_MULTISTEP_RULES_V13
from .queue_jobs import QUEUE_JOBS_RULES_V13
from .realtime_feed import REALTIME_FEED_RULES_V13
from .design_system_runtime import DESIGN_SYSTEM_RUNTIME_RULES_V13
from .localization_content import LOCALIZATION_CONTENT_RULES_V13

from .audit_log import AUDIT_LOG_RULES_V13
from .approval_workflows import APPROVAL_WORKFLOW_RULES_V13
from .sharing_access import SHARING_ACCESS_RULES_V13
from .version_history import VERSION_HISTORY_RULES_V13
from .diff_review import DIFF_REVIEW_RULES_V13
from .operational_inbox import OPERATIONAL_INBOX_RULES_V13
from .tree_navigation import TREE_NAVIGATION_RULES_V13
from .list_navigation import LIST_NAVIGATION_RULES_V13
from .feedback_states import FEEDBACK_STATE_RULES_V13
from .overlay_systems import OVERLAY_SYSTEM_RULES_V13
from .chart_timeseries import CHART_TIMESERIES_RULES_V13
from .calendar_datetime import CALENDAR_DATETIME_RULES_V13
from .contact_entry import CONTACT_ENTRY_RULES_V13
from .verification_codes import VERIFICATION_CODE_RULES_V13
from .scanning_capture import SCANNING_CAPTURE_RULES_V13
from .document_signing import DOCUMENT_SIGNING_RULES_V13
from .link_routing import LINK_ROUTING_RULES_V13
from .file_browser import FILE_BROWSER_RULES_V13
from .incident_response import INCIDENT_RESPONSE_RULES_V13
from .preview_publish import PREVIEW_PUBLISH_RULES_V13

from .security_alert import SECURITY_ALERT_RULES_V13
from .security_case import SECURITY_CASE_RULES_V13
from .threat_hunting import THREAT_HUNT_RULES_V13
from .authentication_review import AUTH_REVIEW_RULES_V13
from .clinical_orders import CLINICAL_ORDER_RULES_V13
from .lab_results import LAB_RESULT_RULES_V13
from .medication_order import MEDICATION_RULES_V13
from .radiology import RADIOLOGY_RULES_V13
from .assessment import ASSESSMENT_RULES_V13
from .quiz_authoring import QUIZ_AUTHOR_RULES_V13
from .learning_progress import LEARNING_PROGRESS_RULES_V13
from .instructor_analytics import INSTRUCTOR_ANALYTICS_RULES_V13
from .resource_booking import BOOKING_RULES_V13
from .marketplace_operations import MARKET_OPS_RULES_V13
from .marketplace_dispute import MARKETPLACE_DISPUTE_RULES_V13
from .marketplace_inventory import MARKETPLACE_INVENTORY_RULES_V13
from .marketplace_payout import MARKETPLACE_PAYOUT_RULES_V13
from .trading_order import TRADING_RULES_V13
from .portfolio_monitoring import PORTFOLIO_RULES_V13
from .bank_reconciliation import RECONCILIATION_RULES_V13
from .live_stream import LIVE_STREAM_RULES_V13
from .conferencing import CONFERENCE_RULES_V13
from .software_pipeline import PIPELINE_RULES_V13
from .build_artifacts import BUILD_ARTIFACT_RULES_V13

FIRST_WAVE_RULES_V13 = (
    AI_AGENT_RULES_V13
    + FORMS_AUTH_RULES_V13
    + DATA_VIZ_RULES_V13
    + EDITOR_WORKSPACE_RULES_V13
    + COMMERCE_RULES_V13
)
FIRST_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in FIRST_WAVE_RULES_V13)

SECOND_WAVE_RULES_V13 = (
    ACCESSIBILITY_INPUT_RULES_V13
    + NAVIGATION_RESILIENCE_RULES_V13
    + PRIVACY_SECURITY_RULES_V13
    + MOBILE_RESPONSIVE_RULES_V13
    + PERFORMANCE_MEDIA_RULES_V13
    + LOCALIZATION_SEARCH_RULES_V13
)
SECOND_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in SECOND_WAVE_RULES_V13)

THIRD_WAVE_RULES_V13 = (
    COLLABORATION_REALTIME_RULES_V13
    + FILE_LIFECYCLE_RULES_V13
    + NOTIFICATION_BACKGROUND_RULES_V13
    + SYNC_FRESHNESS_RULES_V13
    + HISTORY_DESTRUCTIVE_RULES_V13
    + FINANCE_ADMIN_RULES_V13
)
THIRD_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in THIRD_WAVE_RULES_V13)

FOURTH_WAVE_RULES_V13 = (
    SCHEDULING_TIMEZONE_RULES_V13
    + MESSAGING_RULES_V13
    + IMPORT_EXPORT_MIGRATION_RULES_V13
    + DEVICE_CAPTURE_RULES_V13
    + CONSENT_CONTROL_RULES_V13
    + ACCESSIBILITY_ADVANCED_RULES_V13
)
FOURTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in FOURTH_WAVE_RULES_V13)

FIFTH_WAVE_RULES_V13 = (
    IDENTITY_SESSION_RULES_V13
    + TABLE_GRID_RULES_V13
    + MAP_LOCATION_RULES_V13
    + MEDIA_PLAYBACK_ACCESS_RULES_V13
    + COMMENTS_MODERATION_RULES_V13
    + SEARCH_RECOMMENDATION_RULES_V13
    + OFFLINE_CONNECTIVITY_RULES_V13
    + ONBOARDING_PERMISSIONS_RULES_V13
    + COMMERCE_HIGH_CONSEQUENCE_RULES_V13
    + AGENT_RUNTIME_AUTHORITY_RULES_V13
    + NOTIFICATION_ATTENTION_RULES_V13
    + NATIVE_DEVICE_HANDOFF_RULES_V13
)
FIFTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in FIFTH_WAVE_RULES_V13)


SIXTH_WAVE_RULES_V13 = (
    ROLES_PERMISSIONS_RULES_V13
    + SETTINGS_PREFERENCES_RULES_V13
    + COMMAND_KEYBOARD_RULES_V13
    + DASHBOARD_MONITORING_RULES_V13
    + DOWNLOAD_EXPORT_RULES_V13
    + UPLOAD_IMPORT_RULES_V13
    + VOICE_AUDIO_INPUT_RULES_V13
    + TV_REMOTE_RULES_V13
    + SPATIAL_XR_RULES_V13
    + WEARABLE_GLANCE_RULES_V13
    + PRINT_OUTPUT_RULES_V13
    + WORKFLOW_MULTISTEP_RULES_V13
    + QUEUE_JOBS_RULES_V13
    + REALTIME_FEED_RULES_V13
    + DESIGN_SYSTEM_RUNTIME_RULES_V13
    + LOCALIZATION_CONTENT_RULES_V13
)
SIXTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in SIXTH_WAVE_RULES_V13)

SEVENTH_WAVE_RULES_V13 = (
    AUDIT_LOG_RULES_V13
    + APPROVAL_WORKFLOW_RULES_V13
    + SHARING_ACCESS_RULES_V13
    + VERSION_HISTORY_RULES_V13
    + DIFF_REVIEW_RULES_V13
    + OPERATIONAL_INBOX_RULES_V13
    + TREE_NAVIGATION_RULES_V13
    + LIST_NAVIGATION_RULES_V13
    + FEEDBACK_STATE_RULES_V13
    + OVERLAY_SYSTEM_RULES_V13
    + CHART_TIMESERIES_RULES_V13
    + CALENDAR_DATETIME_RULES_V13
    + CONTACT_ENTRY_RULES_V13
    + VERIFICATION_CODE_RULES_V13
    + SCANNING_CAPTURE_RULES_V13
    + DOCUMENT_SIGNING_RULES_V13
    + LINK_ROUTING_RULES_V13
    + FILE_BROWSER_RULES_V13
    + INCIDENT_RESPONSE_RULES_V13
    + PREVIEW_PUBLISH_RULES_V13
)
SEVENTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in SEVENTH_WAVE_RULES_V13)

EIGHTH_WAVE_RULES_V13 = (
    SECURITY_ALERT_RULES_V13
    + SECURITY_CASE_RULES_V13
    + THREAT_HUNT_RULES_V13
    + AUTH_REVIEW_RULES_V13
    + CLINICAL_ORDER_RULES_V13
    + LAB_RESULT_RULES_V13
    + MEDICATION_RULES_V13
    + RADIOLOGY_RULES_V13
    + ASSESSMENT_RULES_V13
    + QUIZ_AUTHOR_RULES_V13
    + LEARNING_PROGRESS_RULES_V13
    + INSTRUCTOR_ANALYTICS_RULES_V13
    + BOOKING_RULES_V13
    + MARKET_OPS_RULES_V13
    + MARKETPLACE_DISPUTE_RULES_V13
    + MARKETPLACE_INVENTORY_RULES_V13
    + MARKETPLACE_PAYOUT_RULES_V13
    + TRADING_RULES_V13
    + PORTFOLIO_RULES_V13
    + RECONCILIATION_RULES_V13
    + LIVE_STREAM_RULES_V13
    + CONFERENCE_RULES_V13
    + PIPELINE_RULES_V13
    + BUILD_ARTIFACT_RULES_V13
)
EIGHTH_WAVE_RULE_IDS = tuple(rule["rule_id"] for rule in EIGHTH_WAVE_RULES_V13)

__all__ = [
    "ACCESSIBILITY_INPUT_RULES_V13",
    "AI_AGENT_RULES_V13",
    "COMMERCE_RULES_V13",
    "DATA_VIZ_RULES_V13",
    "EDITOR_WORKSPACE_RULES_V13",
    "FIRST_WAVE_RULE_IDS",
    "FIRST_WAVE_RULES_V13",
    "FORMS_AUTH_RULES_V13",
    "FOUNDATION_RULES_V13",
    "LOCALIZATION_SEARCH_RULES_V13",
    "MOBILE_RESPONSIVE_RULES_V13",
    "NAVIGATION_RESILIENCE_RULES_V13",
    "PERFORMANCE_MEDIA_RULES_V13",
    "PRIVACY_SECURITY_RULES_V13",
    "SECOND_WAVE_RULE_IDS",
    "SECOND_WAVE_RULES_V13",
    "COLLABORATION_REALTIME_RULES_V13",
    "FILE_LIFECYCLE_RULES_V13",
    "FINANCE_ADMIN_RULES_V13",
    "HISTORY_DESTRUCTIVE_RULES_V13",
    "NOTIFICATION_BACKGROUND_RULES_V13",
    "SYNC_FRESHNESS_RULES_V13",
    "THIRD_WAVE_RULE_IDS",
    "THIRD_WAVE_RULES_V13",
    "ACCESSIBILITY_ADVANCED_RULES_V13",
    "CONSENT_CONTROL_RULES_V13",
    "DEVICE_CAPTURE_RULES_V13",
    "FOURTH_WAVE_RULE_IDS",
    "FOURTH_WAVE_RULES_V13",
    "IMPORT_EXPORT_MIGRATION_RULES_V13",
    "MESSAGING_RULES_V13",
    "SCHEDULING_TIMEZONE_RULES_V13",
    "AGENT_RUNTIME_AUTHORITY_RULES_V13",
    "COMMENTS_MODERATION_RULES_V13",
    "COMMERCE_HIGH_CONSEQUENCE_RULES_V13",
    "FIFTH_WAVE_RULE_IDS",
    "FIFTH_WAVE_RULES_V13",
    "IDENTITY_SESSION_RULES_V13",
    "MAP_LOCATION_RULES_V13",
    "MEDIA_PLAYBACK_ACCESS_RULES_V13",
    "NATIVE_DEVICE_HANDOFF_RULES_V13",
    "NOTIFICATION_ATTENTION_RULES_V13",
    "OFFLINE_CONNECTIVITY_RULES_V13",
    "ONBOARDING_PERMISSIONS_RULES_V13",
    "SEARCH_RECOMMENDATION_RULES_V13",
    "TABLE_GRID_RULES_V13",
    "ROLES_PERMISSIONS_RULES_V13",
    "SETTINGS_PREFERENCES_RULES_V13",
    "COMMAND_KEYBOARD_RULES_V13",
    "DASHBOARD_MONITORING_RULES_V13",
    "DOWNLOAD_EXPORT_RULES_V13",
    "UPLOAD_IMPORT_RULES_V13",
    "VOICE_AUDIO_INPUT_RULES_V13",
    "TV_REMOTE_RULES_V13",
    "SPATIAL_XR_RULES_V13",
    "WEARABLE_GLANCE_RULES_V13",
    "PRINT_OUTPUT_RULES_V13",
    "WORKFLOW_MULTISTEP_RULES_V13",
    "QUEUE_JOBS_RULES_V13",
    "REALTIME_FEED_RULES_V13",
    "DESIGN_SYSTEM_RUNTIME_RULES_V13",
    "LOCALIZATION_CONTENT_RULES_V13",
    "SIXTH_WAVE_RULE_IDS",
    "SIXTH_WAVE_RULES_V13",
    "AUDIT_LOG_RULES_V13",
    "APPROVAL_WORKFLOW_RULES_V13",
    "SHARING_ACCESS_RULES_V13",
    "VERSION_HISTORY_RULES_V13",
    "DIFF_REVIEW_RULES_V13",
    "OPERATIONAL_INBOX_RULES_V13",
    "TREE_NAVIGATION_RULES_V13",
    "LIST_NAVIGATION_RULES_V13",
    "FEEDBACK_STATE_RULES_V13",
    "OVERLAY_SYSTEM_RULES_V13",
    "CHART_TIMESERIES_RULES_V13",
    "CALENDAR_DATETIME_RULES_V13",
    "CONTACT_ENTRY_RULES_V13",
    "VERIFICATION_CODE_RULES_V13",
    "SCANNING_CAPTURE_RULES_V13",
    "DOCUMENT_SIGNING_RULES_V13",
    "LINK_ROUTING_RULES_V13",
    "FILE_BROWSER_RULES_V13",
    "INCIDENT_RESPONSE_RULES_V13",
    "PREVIEW_PUBLISH_RULES_V13",
    "SEVENTH_WAVE_RULE_IDS",
    "SEVENTH_WAVE_RULES_V13",
    "SECURITY_ALERT_RULES_V13",
    "SECURITY_CASE_RULES_V13",
    "THREAT_HUNT_RULES_V13",
    "AUTH_REVIEW_RULES_V13",
    "CLINICAL_ORDER_RULES_V13",
    "LAB_RESULT_RULES_V13",
    "MEDICATION_RULES_V13",
    "RADIOLOGY_RULES_V13",
    "ASSESSMENT_RULES_V13",
    "QUIZ_AUTHOR_RULES_V13",
    "LEARNING_PROGRESS_RULES_V13",
    "INSTRUCTOR_ANALYTICS_RULES_V13",
    "BOOKING_RULES_V13",
    "MARKET_OPS_RULES_V13",
    "MARKETPLACE_DISPUTE_RULES_V13",
    "MARKETPLACE_INVENTORY_RULES_V13",
    "MARKETPLACE_PAYOUT_RULES_V13",
    "TRADING_RULES_V13",
    "PORTFOLIO_RULES_V13",
    "RECONCILIATION_RULES_V13",
    "LIVE_STREAM_RULES_V13",
    "CONFERENCE_RULES_V13",
    "PIPELINE_RULES_V13",
    "BUILD_ARTIFACT_RULES_V13",
    "EIGHTH_WAVE_RULE_IDS",
    "EIGHTH_WAVE_RULES_V13",
]
