"""V13 accessibility and alternative-input rules authored as distinct failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


ACCESSIBILITY_INPUT_RULES_V13 = [
    {
        "rule_id": "ui.accessibility.focus-visible-under-overlays",
        "domain": "accessibility", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Keyboard focus must remain visually locatable when overlays or sticky regions are present",
        "statement": "When keyboard focus moves to an interactive target, persistent headers, sheets, banners, sticky controls, or transient overlays must not cover the focused target or erase the visible focus indication needed to locate it.",
        "intent": "Keep keyboard navigation operable in the rendered composition rather than treating DOM focus alone as evidence that a user can see and understand the current interaction target.",
        "applies_when": ["A screen contains keyboard-focusable controls together with fixed, sticky, modal, popover, toast, cookie, or other layers that can overlap the focused region."],
        "does_not_apply_when": ["The focused target is intentionally hidden because the product immediately transfers focus to another visible target as part of a documented composite interaction."],
        "failure_modes": ["Keyboard focus lands on a control that is partially or fully obscured, or its focus indicator is clipped or visually indistinguishable because another rendered layer covers the target."],
        "user_impacts": ["Keyboard and low-vision users can lose track of focus, activate the wrong control, or be unable to continue a workflow even though the focus event technically succeeded."],
        "observables": ["Tab or scripted focus moves to a target whose rendered bounds or focus ring intersect an obscuring layer such that the active target cannot be reliably located on screen."],
        "falsifiers": ["Across representative viewport and zoom states, every focus transition results in a visible, unobscured target or an automatic scroll/reposition that exposes the active control and its indicator."],
        "repairs": ["Adjust sticky/overlay geometry, scroll-margin behavior, focus management, or placement so the active target and its focus indication remain visible without requiring pointer-only recovery."],
        "exceptions": ["A deliberately off-screen focus sentinel may exist for focus trapping mechanics when it cannot receive normal user interaction and immediately redirects focus to a visible target."],
        "verification": ["Navigate the complete interaction path by keyboard at representative viewport sizes and zoom, forcing overlays open, and confirm each newly focused target remains visually exposed and identifiable."],
        "owner_hints": ["designing-focus-order-and-restoration"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "accessibility-tree": "REQUIRED"}),
        "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.accessibility.name-updates-with-state",
        "domain": "accessibility", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "An accessible control name must continue to describe the action after its state changes",
        "statement": "Controls whose visible purpose changes after toggling, expanding, muting, pinning, following, revealing, or switching modes must expose an accessible name and state that continue to describe the action or current condition accurately.",
        "intent": "Prevent assistive-technology users from receiving a stale label that contradicts the visible control state or causes the next activation to perform an unexpected inverse action.",
        "applies_when": ["An interactive element changes action, state, selection, expansion, disclosure, playback, subscription, visibility, or another user-relevant condition without being replaced by a semantically new control."],
        "does_not_apply_when": ["The control name intentionally remains constant because the role exposes the changing state separately and the fixed name remains an accurate description of the controlled concept."],
        "failure_modes": ["The visible state changes but the accessible name, state property, or description remains stale, contradictory, empty, or describes the action that already occurred rather than the next available action."],
        "user_impacts": ["Screen-reader and voice-control users can misunderstand current state, invoke the opposite action from the one they expect, or lose a reliable target name for repeated interaction."],
        "observables": ["After a state transition, the accessibility tree or computed accessible name does not match the control's new visible meaning and the action available on the next activation."],
        "falsifiers": ["Each tested state transition produces a coherent accessible role, name, value/state, and description whose combined meaning matches the visible UI and next interaction semantics."],
        "repairs": ["Bind accessible naming and state properties to the same authoritative state model that drives the rendered control, avoiding duplicated labels that can drift independently."],
        "exceptions": ["A stable noun label such as a setting name may remain unchanged when an explicit semantic state like checked, pressed, expanded, or selected communicates the changing condition without ambiguity."],
        "verification": ["Exercise every user-visible state of representative controls and inspect the accessibility tree after each transition, confirming the spoken/semantic result matches the rendered state and next action."],
        "owner_hints": ["designing-accessible-names-and-descriptions"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"accessibility-tree": "REQUIRED"}),
        "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.accessibility.pointer-cancel-before-commit",
        "domain": "accessibility", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Pointer activation must allow cancellation before a consequential action commits",
        "statement": "For pointer interactions that can cause a consequential activation, pressing down on a target must not make the irreversible or material commitment unavoidable before the user can move away, cancel, or otherwise abort the activation.",
        "intent": "Protect users with motor variability from accidental commitments caused by contact onset, drag drift, tremor, or mistaken targeting when they intended to cancel before release.",
        "applies_when": ["A pointer, touch, pen, or similar contact activates deletion, submission, purchase, sending, state-changing commands, or other actions where accidental activation has material impact."],
        "does_not_apply_when": ["The interaction is inherently continuous and reversible during contact, such as scrubbing or drawing, and the initial contact itself is not represented as a discrete committed command."],
        "failure_modes": ["The action commits on pointer-down or contact start, or movement away from the target cannot cancel the pending activation even though no deliberate release/confirmation occurred."],
        "user_impacts": ["Users can trigger destructive or costly actions simply by touching the wrong target and have no interaction-level opportunity to cancel before the command takes effect."],
        "observables": ["Starting contact on the target and then moving outside or cancelling the pointer sequence still produces the same committed action as a deliberate completed activation."],
        "falsifiers": ["A pointer sequence can be cancelled before commitment, and release outside or cancellation prevents the consequential action unless the product uses a separately confirmed interaction model."],
        "repairs": ["Move commitment to a cancellable completion boundary, respect pointer cancellation and release location where appropriate, and separate continuous press feedback from the consequential command."],
        "exceptions": ["Emergency or game-like controls with explicit press-and-hold semantics may begin behavior on contact when release immediately and reliably stops the effect and the design communicates that model."],
        "verification": ["Start activation on each consequential pointer target, move away or issue pointer cancellation before release, and confirm no committed action occurs while a deliberate complete activation still works."],
        "owner_hints": ["designing-pointer-cancellation-accessibility"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}),
        "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.accessibility.drag-has-nondrag-path",
        "domain": "accessibility", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "A drag-only operation must provide an equivalent non-drag interaction path",
        "statement": "When dragging changes order, assignment, placement, membership, value, or another persistent state, users who cannot perform precise dragging must have an operable alternative that reaches the same meaningful result.",
        "intent": "Keep direct manipulation from becoming the only route to product state changes for keyboard users, switch users, people with motor impairments, or contexts where dragging is unavailable.",
        "applies_when": ["The interface exposes drag-and-drop, drag-to-reorder, drag-to-connect, drag-to-resize, or another gesture whose completed result modifies persistent or decision-relevant state."],
        "does_not_apply_when": ["Dragging is purely optional decoration or exploration and every meaningful state change is already available through another clearly reachable command path."],
        "failure_modes": ["A meaningful state can only be reached by dragging, while keyboard, command, menu, stepper, or other non-drag controls cannot perform an equivalent operation."],
        "user_impacts": ["Users who cannot reliably drag are blocked from arranging, assigning, moving, resizing, or otherwise completing the same task as pointer-drag users."],
        "observables": ["Attempting the task without pointer dragging reveals no focusable or command-based mechanism that can produce the same persisted state transition."],
        "falsifiers": ["The complete state-changing operation can be performed without dragging, including target selection and confirmation, and the result is equivalent to the drag path."],
        "repairs": ["Add keyboard/command alternatives such as move before/after, choose destination, increment/decrement, connect via menus, or other semantics appropriate to the domain rather than simulating pointer motion."],
        "exceptions": ["Freehand spatial creation may lack a semantically identical non-drag gesture when the product also provides an alternative method to create or edit the same underlying information without precise path drawing."],
        "verification": ["Complete representative drag operations using only keyboard or the documented non-drag mechanism and compare the resulting application state with the equivalent drag result."],
        "owner_hints": ["designing-accessible-drag-and-drop"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"accessibility-tree": "REQUIRED", "human-review": "REQUIRED"}),
        "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.accessibility.reduced-motion-removes-trigger",
        "domain": "accessibility", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Reduced-motion mode must remove triggering motion rather than merely shortening it",
        "statement": "When the user requests reduced motion, transitions involving large spatial travel, parallax, zooming, continuous movement, flashing sequences, or other potentially triggering effects must be replaced with a materially safer presentation instead of only running faster.",
        "intent": "Respect the user's motion-sensitivity preference at the mechanism level so the product does not preserve the same vestibular or photosensitive trigger with a shorter duration.",
        "applies_when": ["The rendered experience includes substantial motion, spatial transforms, looping animation, animated background movement, or flashing effects and the platform or product exposes a reduced-motion preference."],
        "does_not_apply_when": ["The motion is essential to communicate an immediate change and a reduced alternative preserves the information with a non-triggering minimal transition."],
        "failure_modes": ["Reduced-motion mode keeps the same large translation, zoom, parallax, looping, or flashing mechanism and only reduces duration, delay, or frame count."],
        "user_impacts": ["Motion-sensitive users can still experience discomfort, disorientation, nausea, or seizure risk even though they explicitly requested a safer motion profile."],
        "observables": ["Comparing normal and reduced-motion renders shows the triggering transform or repeated movement remains materially present instead of being removed, substituted, or simplified."],
        "falsifiers": ["Reduced-motion mode removes or replaces triggering spatial/continuous effects while preserving task information, feedback, and state changes through static or minimal alternatives."],
        "repairs": ["Define reduced variants per motion mechanism, replacing spatial travel and loops with opacity, instant state change, restrained emphasis, or another non-triggering transition that preserves meaning."],
        "exceptions": ["A small non-spatial state transition may remain when it does not recreate the triggering mechanism and is needed to preserve orientation or feedback."],
        "verification": ["Enable the platform or product reduced-motion preference and compare representative transitions, loops, backgrounds, and state changes with normal mode to confirm triggering mechanisms are removed or substituted."],
        "owner_hints": ["designing-reduced-motion-and-photosensitivity"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"computed-style": "REQUIRED", "visual-render": "REQUIRED", "human-review": "REQUIRED"}),
        "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.accessibility.live-region-does-not-spam",
        "domain": "accessibility", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "Live announcements must prioritize meaningful state changes instead of narrating every update",
        "statement": "Dynamic interfaces that announce updates to assistive technology must avoid repeatedly interrupting users with low-value, rapidly changing, duplicated, or purely visual status messages when a quieter summary or user-requested detail is sufficient.",
        "intent": "Preserve awareness of important asynchronous changes without turning live regions into an interruption stream that makes the primary task harder to perceive and operate.",
        "applies_when": ["The interface uses live regions or equivalent announcement mechanisms for progress, validation, collaborative updates, search counts, streaming results, notifications, or other asynchronous state changes."],
        "does_not_apply_when": ["The announced event is urgent, safety-relevant, or directly blocks the current action and immediate interruption is necessary for the user to proceed correctly."],
        "failure_modes": ["Rapid or repeated state updates generate overlapping announcements, duplicate messages, narrate every intermediate count, or continuously interrupt reading and command entry."],
        "user_impacts": ["Screen-reader users can lose the primary content, miss important announcements among noise, or be unable to complete a task because the interface repeatedly steals auditory attention."],
        "observables": ["A representative dynamic session produces a high-frequency sequence of announcements whose individual messages do not correspond to distinct decisions or user-relevant terminal states."],
        "falsifiers": ["Dynamic updates are coalesced, prioritized, delayed until meaningful boundaries, or made available on demand while urgent and action-blocking changes remain timely."],
        "repairs": ["Group related updates, announce terminal or decision-relevant states, use appropriate politeness, and expose detailed high-frequency telemetry in an inspectable region rather than the live announcement channel."],
        "exceptions": ["Realtime assistive workflows may intentionally announce frequent updates when users explicitly opted into that stream and can pause, filter, or control its verbosity."],
        "verification": ["Run realistic high-frequency update scenarios with assistive technology or accessibility-tree instrumentation and review the announcement sequence for duplication, interruption pressure, and loss of decision-relevant messages."],
        "owner_hints": ["designing-screen-reader-experiences"], "verifier_hints": ["critiquing-accessibility"],
        "capabilities": interaction_caps(**{"accessibility-tree": "REQUIRED", "human-review": "REQUIRED"}),
        "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["ACCESSIBILITY_INPUT_RULES_V13"]
