"""V13 advanced accessibility rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

ACCESSIBILITY_ADVANCED_RULES_V13 = [
    {
        "rule_id":"ui.accessibility.screen-reader-order-preserves-meaning","domain":"accessibility","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Screen-reader reading order must preserve the semantic sequence needed to understand and act",
        "statement":"DOM and accessibility-tree order must present headings, labels, content, status, and controls in a sequence that preserves task meaning even when visual layout uses grids, columns, sticky regions, or CSS reordering.",
        "intent":"Prevent nonvisual navigation from receiving a different or incoherent information hierarchy from the visible interface.",
        "applies_when":["A material interface uses complex visual ordering, responsive rearrangement, portals, grids, or multi-column structure."],"does_not_apply_when":[],
        "failure_modes":["Assistive technology encounters actions before their labels or context, reads columns in a misleading sequence, or follows source order that contradicts the task’s semantic progression."],
        "user_impacts":["Screen-reader users can misunderstand relationships, miss context, or activate the wrong action because navigation order does not preserve meaning."],
        "observables":["Inspect accessibility-tree and keyboard or virtual-cursor traversal order against the intended semantic hierarchy at supported breakpoints."],
        "falsifiers":["Nonvisual order remains coherent and preserves labels, context, and action sequence independently of visual positioning."],
        "repairs":["Use semantic source order as the primary sequence, avoid visual-only reordering for meaning, and restructure responsive DOM when necessary rather than relying on CSS order."],
        "exceptions":["Purely decorative visual positioning may differ when it does not change semantic reading or interaction relationships."],
        "verification":["Navigate representative flows with an accessibility tree or screen reader at multiple layouts and confirm semantic sequence remains understandable."],
        "owner_hints":["designing-screen-reader-experiences"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"accessibility-tree":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.accessibility.focus-return-when-origin-disappears","domain":"accessibility","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Closing a transient surface must restore focus to a valid logical destination when its opener no longer exists",
        "statement":"If a dialog, popover, menu, or other focus-taking surface closes after the element that opened it was removed, disabled, or rerendered away, focus must move to a sensible surviving location rather than fall to the document body or an unrelated control.",
        "intent":"Preserve keyboard and assistive-technology continuity through dynamic UI mutations.",
        "applies_when":["Transient UI moves focus and its trigger can disappear because of deletion, filtering, navigation, or state changes before close."],"does_not_apply_when":[],
        "failure_modes":["Close attempts to focus a detached trigger and focus becomes lost, body-level, or unpredictably jumps elsewhere."],
        "user_impacts":["Keyboard and screen-reader users lose their place and must rediscover context after completing or cancelling an action."],
        "observables":["Open transient UI, remove or disable its trigger while open, close it, and inspect active element and announced context."],
        "falsifiers":["Focus returns to the surviving logical parent, next meaningful control, or explicit fallback defined for that workflow."],
        "repairs":["Resolve focus restoration at close time against current DOM and task context, with a fallback hierarchy when the original trigger is no longer focusable."],
        "exceptions":["A close action that intentionally navigates to a new page should follow the destination page’s normal focus-management contract instead."],
        "verification":["Exercise trigger deletion, filtering, disabled state, and route transition while transient UI is open and verify a meaningful focus destination."],
        "owner_hints":["designing-screen-reader-experiences"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"accessibility-tree":"REQUIRED","browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.accessibility.virtualized-set-position-truthful","domain":"accessibility","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Virtualized collections must expose truthful set size and item position when assistive navigation depends on them",
        "statement":"When only a window of a larger logical collection is mounted, accessibility metadata must not imply that the rendered window is the whole set if users need position or count to orient themselves.",
        "intent":"Let assistive-technology users understand where a visible item sits in the same logical collection sighted users perceive through scrolling or counts.",
        "applies_when":["Lists, feeds, grids, or tables virtualize items and expose item position or total set semantics to assistive technology."],"does_not_apply_when":[],
        "failure_modes":["A 1,000-item logical list renders 20 nodes and accessibility semantics announce them as items 1 through 20 of 20 regardless of actual position."],
        "user_impacts":["Users cannot determine location, progress, or collection size and may think content is missing."],
        "observables":["Inspect accessibility metadata while scrolling to different virtual windows and compare item positions with logical collection indices and total."],
        "falsifiers":["Position and set-size semantics reflect logical collection state where exposed, or the UI avoids misleading metadata when total is genuinely unknown."],
        "repairs":["Provide logical position and set-size metadata from virtualization state and preserve stable item identity across recycled nodes."],
        "exceptions":["Infinite feeds with genuinely unknown totals need not invent a final set size; they must simply avoid false certainty."],
        "verification":["Inspect first, middle, appended, and end windows with accessibility tooling and verify positions and totals remain truthful."],
        "owner_hints":["designing-screen-reader-experiences"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"accessibility-tree":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.accessibility.zoom-reflow-preserves-essential-content","domain":"accessibility","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Supported text or page zoom must not make essential content or controls unreachable through two-dimensional clipping",
        "statement":"At supported zoom and text-scaling levels, essential reading and task controls must reflow or remain reachable without forcing users to pan both horizontally and vertically through ordinary text-oriented content when the platform can reflow it.",
        "intent":"Preserve task completion for low-vision users who magnify content.",
        "applies_when":["Web or reflow-capable interfaces support browser zoom, text scaling, or responsive magnification."],"does_not_apply_when":[],
        "failure_modes":["Zoom causes primary controls or content to clip outside an inaccessible fixed container, overlap permanently, or require avoidable two-axis navigation."],
        "user_impacts":["Low-vision users can lose access to actions or reading flow when magnification is necessary."],
        "observables":["Exercise supported zoom or text scaling at representative viewport sizes and inspect overflow, clipping, and reachability of essential tasks."],
        "falsifiers":["Essential content remains readable and controls reachable with reflow or appropriate one-axis scrolling for content that inherently requires it."],
        "repairs":["Remove fixed dimensions that block reflow, allow wrapping and vertical growth, and preserve specialized horizontal canvases only where their semantics require it."],
        "exceptions":["Maps, complex data tables, diagrams, and other intrinsically two-dimensional content may require two-axis navigation while surrounding controls still remain accessible."],
        "verification":["Test supported magnification across key routes and confirm essential text and actions remain reachable without destructive clipping."],
        "owner_hints":["designing-accessible-interfaces"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"visual-render":"REQUIRED","browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.accessibility.text-spacing-does-not-clip-content","domain":"accessibility","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Increased text spacing must not clip, overlap, or hide essential text and controls",
        "statement":"Layouts must tolerate supported increases in line height, letter spacing, word spacing, and paragraph spacing without truncating essential labels, instructions, validation, or actions.",
        "intent":"Ensure users who adjust text spacing for readability do not lose information or task access.",
        "applies_when":["The interface contains textual controls or content in containers whose height or width can constrain text expansion."],"does_not_apply_when":[],
        "failure_modes":["Applying increased text spacing clips labels, overlaps controls, hides validation, or makes text inaccessible inside fixed-height regions."],
        "user_impacts":["Users who need greater spacing for readability can no longer understand or operate the interface."],
        "observables":["Apply representative increased text-spacing settings and inspect essential content for clipping, overlap, or lost interactions."],
        "falsifiers":["Containers expand or reflow so essential content remains visible and controls retain usable boundaries."],
        "repairs":["Avoid fixed text container heights, allow wrapping and intrinsic sizing, and test spacing overrides rather than relying on default font metrics."],
        "exceptions":["Decorative non-essential truncation may remain when no meaning or task control is lost and accessible alternatives preserve the content."],
        "verification":["Apply standardized spacing overrides across forms, navigation, dialogs, tables, and cards and verify no essential text or action becomes clipped."],
        "owner_hints":["designing-accessible-interfaces"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"visual-render":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.accessibility.single-key-shortcut-has-safeguard","domain":"accessibility","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Single-character shortcuts need a way to disable, remap, or constrain accidental activation when text focus is not required",
        "statement":"A shortcut triggered by one printable character without modifier must not remain globally unavoidable when accidental speech-input or keyboard activation can cause meaningful action; the product should provide an applicable safeguard such as disabling, remapping, or focus-bounded activation.",
        "intent":"Prevent unintended commands for speech-input and keyboard users while preserving efficient power-user workflows.",
        "applies_when":["The product defines single-letter, number, punctuation, or symbol shortcuts that can activate outside a text-entry control."],"does_not_apply_when":[],
        "failure_modes":["Speaking or pressing an ordinary character anywhere triggers a consequential command with no user-accessible way to disable, remap, or limit the shortcut context."],
        "user_impacts":["Users can accidentally navigate, delete, mutate, or trigger commands simply through ordinary character input or voice control."],
        "observables":["Enumerate unmodified single-character shortcuts and test activation across focus contexts and available shortcut settings."],
        "falsifiers":["Single-character shortcuts are disabled or remappable, or activate only in a tightly defined focus context that prevents unintended general character activation."],
        "repairs":["Add shortcut preferences, require modifiers for consequential global commands, or scope character shortcuts to explicit modes and focus states."],
        "exceptions":["Character input inside a purpose-built application mode may be intrinsic when entering that mode is itself explicit and users can exit it reliably."],
        "verification":["Test all unmodified character shortcuts with keyboard and speech-input-like activation and confirm the documented safeguard prevents accidental global commands."],
        "owner_hints":["designing-keyboard-power-user-ux"],"verifier_hints":["critiquing-accessibility"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED","human-review":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["ACCESSIBILITY_ADVANCED_RULES_V13"]
