"""Independently authored V13 rules for agentic and generative UI execution truth."""
from __future__ import annotations


def _caps(**overrides: str) -> dict[str, str]:
    values = {
        "static": "PARTIAL", "dom": "PARTIAL", "computed-style": "UNSUPPORTED",
        "browser-runtime": "PARTIAL", "interaction": "REQUIRED", "accessibility-tree": "PARTIAL",
        "visual-render": "PARTIAL", "semantic-product": "REQUIRED", "cross-generation": "UNSUPPORTED",
        "human-review": "PARTIAL",
    }
    values.update(overrides)
    return values


AI_AGENT_RULES_V13 = [
    {
        "rule_id": "ui.ai.approval-scope-matches-action",
        "domain": "ai", "class": "mechanical", "severity": "critical", "enforcement": "block",
        "title": "Agent approval must name the actual consequential action and scope",
        "statement": "An approval surface for an agent action must describe the operation, affected objects, destination, and material side effects at the same scope the execution authority will actually receive.",
        "intent": "Prevent broad or ambiguous approvals from silently authorizing actions that a user could not reasonably infer from the approval request they reviewed.",
        "applies_when": ["An agent, automation, or delegated workflow requests user approval before sending, publishing, deleting, purchasing, changing permissions, modifying external state, or invoking another consequential tool."],
        "does_not_apply_when": ["The requested operation is purely read-only, has no material external side effect, and the product does not represent the interaction as an approval boundary."],
        "failure_modes": ["The approval copy describes a narrower, different, or less consequential action than the tool arguments or delegated authority that execution will receive after confirmation."],
        "user_impacts": ["Users can authorize unintended recipients, resources, scopes, costs, or irreversible side effects because the visible consent boundary does not match execution reality."],
        "observables": ["Comparing the rendered approval summary with the pending tool invocation reveals omitted targets, wildcard scope, hidden secondary actions, or materially broader parameters."],
        "falsifiers": ["The approval surface exposes every decision-relevant target and consequence that can be derived from the exact pending invocation, and execution rejects any post-approval scope expansion."],
        "repairs": ["Bind approval UI to the immutable pending invocation contract, surface material parameters in user language, and require a new approval whenever consequential scope changes."],
        "exceptions": ["A previously approved standing policy may cover repeated actions only when its scope, expiry, revocation path, and applicability to the current action are visible and still valid."],
        "verification": ["Capture a pending consequential invocation, compare its exact arguments and authority with the approval surface, then mutate a material target and confirm execution requires fresh approval."],
        "owner_hints": ["designing-agent-approval-scope-boundaries"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.tool-result-attribution",
        "domain": "ai", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Tool-derived claims must remain attributable to the tool result that supports them",
        "statement": "When an agent presents facts, records, calculations, or external-state results obtained from a tool, the UI must preserve enough result identity and execution context to distinguish observed tool output from model-authored inference.",
        "intent": "Keep the interface truthful about where consequential information came from so users can separate retrieved evidence from generated interpretation.",
        "applies_when": ["A generative or agentic surface incorporates tool output into a user-visible answer, recommendation, status, record summary, calculation, or action decision."],
        "does_not_apply_when": ["The tool is a purely local deterministic formatting primitive whose output adds no independent factual or external-state claim."],
        "failure_modes": ["Tool output is blended into generated prose without preserving which values were observed, which tool produced them, or whether the displayed claim is a later model inference."],
        "user_impacts": ["Users may over-trust generated synthesis, misattribute an inference to an authoritative system, or lose the ability to inspect the evidence behind a consequential claim."],
        "observables": ["The displayed result contains tool-derived facts but no recoverable association to the corresponding invocation/result record or provenance representation available in the product."],
        "falsifiers": ["A user can inspect the relevant tool/result provenance for decision-relevant claims and the interface distinguishes retrieved result material from model interpretation where that distinction matters."],
        "repairs": ["Retain a stable result reference and expose source/tool attribution at the appropriate level of detail without overwhelming the primary answer with raw execution logs."],
        "exceptions": ["Low-risk conversational conveniences may compress attribution when no decision-relevant factual distinction is lost and the underlying result remains inspectable on demand."],
        "verification": ["Trace representative user-visible factual claims backward through the UI to the actual tool invocation and result, and confirm generated interpretation is not mislabeled as retrieved evidence."],
        "owner_hints": ["designing-tool-result-presentation-lifecycles"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.stale-plan-revalidation",
        "domain": "ai", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "An agent plan must be revalidated when material execution assumptions become stale",
        "statement": "A plan or queued action sequence that depends on mutable external state must not continue as though its original assumptions remain true after that state, authority, resource identity, or user intent materially changes.",
        "intent": "Prevent a previously reasonable plan from becoming unsafe or incorrect simply because the interface treats planning time and execution time as the same truth boundary.",
        "applies_when": ["An agent prepares multiple actions, waits for approval, resumes after interruption, retries later, or executes against resources whose state can change between planning and commitment."],
        "does_not_apply_when": ["All relevant inputs are immutable snapshots and the resulting operations are explicitly scoped to those immutable versions."],
        "failure_modes": ["Execution proceeds from a stale plan after a dependency, permission, destination, resource version, price, recipient, or user instruction changed in a way that alters the intended outcome."],
        "user_impacts": ["The agent can perform obsolete, conflicting, or newly unauthorized work while the UI still frames the execution as the plan the user previously reviewed."],
        "observables": ["A material dependency has a newer version or state than the plan snapshot, yet the interface offers execution without revalidation, conflict handling, or renewed approval where needed."],
        "falsifiers": ["The system proves relevant assumptions unchanged at execution time or surfaces the drift and requires an appropriate replan, conflict decision, or approval refresh before commitment."],
        "repairs": ["Version decision-relevant assumptions, check them at execution boundaries, invalidate stale steps, and present changed assumptions before the agent resumes consequential work."],
        "exceptions": ["Best-effort background work may continue across benign changes only when the changed state cannot alter authority, target identity, cost, safety, or user-visible outcome."],
        "verification": ["Prepare a plan, mutate one material dependency before execution, and confirm the product detects the drift rather than silently running the stale action sequence."],
        "owner_hints": ["designing-agent-plan-preview-surfaces"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.interruption-preserves-authority",
        "domain": "ai", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Interrupting an agent must stop or bound future side effects under that run authority",
        "statement": "When a user pauses, stops, or cancels an agent run, the product must define and honor which in-flight operation may finish and must prevent unstarted consequential operations from continuing under the canceled run's authority.",
        "intent": "Make interruption a real control boundary rather than a cosmetic status change that leaves delegated side effects running invisibly.",
        "applies_when": ["An agent can execute more than one step, invoke external tools, queue actions, or continue working after the user has an available pause, stop, cancel, or interrupt control."],
        "does_not_apply_when": ["The product has no delegated execution and interruption only stops local generation with no external side effects."],
        "failure_modes": ["The UI reports the run stopped while queued or newly started consequential tool calls continue to execute without a separately disclosed and authorized continuation contract."],
        "user_impacts": ["Users lose practical control over delegated work and may believe external changes were prevented when the agent continues modifying state after interruption."],
        "observables": ["After interruption is acknowledged, execution logs or external state show new consequential operations starting from the canceled run rather than only bounded cleanup or unavoidable in-flight completion."],
        "falsifiers": ["The interruption boundary cancels unstarted work, clearly reports unavoidable in-flight operations, and requires new authority before any later consequential step resumes."],
        "repairs": ["Propagate cancellation to the execution scheduler, separate cancellable from already-committed operations, and surface residual in-flight work until it reaches a truthful terminal state."],
        "exceptions": ["An already committed external operation may be impossible to cancel, but the UI must report that fact and must not treat later queued operations as equally unavoidable."],
        "verification": ["Start a multi-step run, interrupt it between consequential steps, and inspect tool execution plus external state to confirm no new unauthorized side effect begins afterward."],
        "owner_hints": ["designing-agent-interruption-and-resume"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.irreversible-action-last-mile-confirmation",
        "domain": "ai", "class": "contextual", "severity": "critical", "enforcement": "block",
        "title": "Irreversible agent actions need a last-mile consequence boundary near execution",
        "statement": "A broad instruction to an agent is not sufficient authorization for a newly resolved irreversible action when the exact object, destination, amount, audience, or destructive consequence only becomes known later in the run.",
        "intent": "Place user awareness at the point where an abstract request turns into a concrete irreversible side effect instead of treating early conversational intent as perpetual blanket consent.",
        "applies_when": ["An agent resolves concrete details after planning and is about to delete, publish, send, transfer, purchase, revoke, or otherwise cause a material effect that cannot be cheaply reversed."],
        "does_not_apply_when": ["The exact irreversible action and complete scope were already explicitly approved and remain unchanged at execution time."],
        "failure_modes": ["The agent commits an irreversible effect using an earlier broad instruction even though decision-relevant execution details were not visible or fixed when the user gave that instruction."],
        "user_impacts": ["Users can incur permanent loss, disclosure, financial cost, or third-party consequences that they did not meaningfully review at the point those consequences became concrete."],
        "observables": ["The final tool invocation contains newly resolved consequential parameters but no corresponding last-mile confirmation or pre-existing policy that explicitly covers those exact parameters."],
        "falsifiers": ["The exact action scope was already approved under an unexpired policy or the product obtains a fresh confirmation after all decision-relevant execution details are resolved."],
        "repairs": ["Introduce a pre-commit boundary that presents the resolved irreversible consequence, affected scope, and any material uncertainty before granting execution authority."],
        "exceptions": ["Explicitly configured unattended automation may operate without per-action confirmation when users deliberately created a standing policy with bounded scope, auditability, and revocation."],
        "verification": ["Give the agent a broad task that later resolves an irreversible target, then confirm execution pauses with the resolved consequence visible before the irreversible tool call is authorized."],
        "owner_hints": ["designing-agent-reversible-action-surfaces"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"browser-runtime": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.tool-failure-not-success",
        "domain": "ai", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "A failed or uncommitted tool operation must not be rendered as completed success",
        "statement": "Agent-facing UI must derive success from the tool or authoritative system's actual completion boundary and must keep timeout, rejection, partial completion, queued, and unknown outcomes distinct from committed success.",
        "intent": "Prevent fluent model narration from outrunning execution truth and falsely telling users that an external change occurred.",
        "applies_when": ["An agent invokes a tool whose outcome changes external state or returns a result that the UI summarizes as completed, saved, sent, published, created, deleted, or otherwise successful."],
        "does_not_apply_when": ["The displayed status explicitly describes model intent or a dry-run preview rather than claiming an external operation completed."],
        "failure_modes": ["The interface displays completion or affirmative success when the underlying tool returned an error, timed out, remained queued, completed only partially, or never provided a trustworthy terminal result."],
        "user_impacts": ["Users may stop retrying, make follow-up decisions, or communicate false state to others because the product claims an operation happened when it did not."],
        "observables": ["A mismatch exists between the tool invocation's authoritative outcome and the terminal status, toast, assistant prose, ledger entry, or object state rendered to the user."],
        "falsifiers": ["Every tested failure, timeout, rejection, partial-result, and pending response maps to a distinct truthful UI state and only authoritative completion produces success."],
        "repairs": ["Bind terminal user messaging to structured tool outcomes, preserve UNKNOWN when no terminal evidence exists, and make partial success enumerate the scope that actually completed."],
        "exceptions": ["A tool may report accepted or queued status as a successful submission only when the UI names that weaker boundary explicitly instead of implying downstream completion."],
        "verification": ["Force error, timeout, partial, queued, and successful tool outcomes and compare each rendered terminal state with the actual tool contract result."],
        "owner_hints": ["designing-agent-tool-call-lifecycles"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.generated-content-origin-visible",
        "domain": "ai", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "Decision-relevant generated content needs a visible origin and editing status",
        "statement": "When generated text, code, data, media, or recommendations can be mistaken for user-authored, verified, or source-system content, the interface should preserve whether the material is generated, edited, approved, or externally sourced.",
        "intent": "Avoid provenance collapse in collaborative and consequential workflows without forcing an intrusive AI badge onto every low-risk piece of generated interface copy.",
        "applies_when": ["Generated material enters a document, record, message, decision artifact, shared workspace, or other surface where authorship or verification status affects trust, accountability, or later editing."],
        "does_not_apply_when": ["Origin is immaterial to the task, the generated text is transient interface microcopy, or the product deliberately presents all content as system-generated with no plausible authorship ambiguity."],
        "failure_modes": ["Generated material becomes visually indistinguishable from independently authored or verified content even though downstream users rely on authorship, review, or source status to judge it."],
        "user_impacts": ["Collaborators may attribute statements to the wrong person, overestimate review, or fail to inspect material that was generated rather than independently verified."],
        "observables": ["A shared or persistent artifact contains generated material but exposes no origin, review state, or history capable of distinguishing generation from subsequent human acceptance where that distinction matters."],
        "falsifiers": ["The product's workflow makes origin irrelevant or provides an inspectable provenance/history model that accurately records generation, edits, approval, and external sourcing."],
        "repairs": ["Preserve origin and review metadata in the artifact model and expose it contextually where users make trust or accountability decisions rather than adding decorative AI labeling everywhere."],
        "exceptions": ["Low-risk suggestions that are immediately transformed into ordinary user-authored content may intentionally drop origin when no later decision depends on it."],
        "verification": ["Create generated material, edit and approve part of it, then inspect the shared/persistent view and history to confirm origin and review state remain distinguishable where required."],
        "owner_hints": ["designing-ai-uncertainty-and-provenance"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"human-review": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.ai.autonomy-boundary-visible",
        "domain": "ai", "class": "contextual", "severity": "major", "enforcement": "warn",
        "title": "Users need to distinguish suggestion, delegated execution, and autonomous continuation",
        "statement": "An agent surface must not blur whether the system is only proposing work, waiting for authorization, actively executing delegated actions, or permitted to continue without additional user interaction when those modes carry different consequences.",
        "intent": "Make practical agency legible so users know when their review is advisory, required, or no longer part of the next execution step.",
        "applies_when": ["A product supports more than one AI agency mode such as draft-only suggestions, approval-gated tools, background runs, scheduled automation, or bounded autonomous execution."],
        "does_not_apply_when": ["The product supports exactly one clearly documented non-consequential generation mode and cannot execute external actions."],
        "failure_modes": ["The same visual state and controls represent materially different execution authority, leaving users unable to predict whether the agent will act, wait, or continue after they leave the surface."],
        "user_impacts": ["Users may unintentionally delegate more authority than expected, duplicate actions the agent is already performing, or assume work is progressing when the system is actually waiting for approval."],
        "observables": ["Two runs with different authorization/continuation semantics are presented without a stable visible distinction in status, control affordances, or inspectable run policy."],
        "falsifiers": ["The current run mode, pending approval requirement, background-continuation policy, and available stop/revoke control are unambiguous at the points where user behavior depends on them."],
        "repairs": ["Expose the current agency mode as a functional state tied to controls and run policy, and update it whenever authorization or continuation semantics change."],
        "exceptions": ["A compact mode label may be omitted from low-risk transient interactions when execution authority cannot change and users cannot reasonably confuse proposal with action."],
        "verification": ["Exercise suggestion-only, approval-gated, executing, and background-continuation modes and ask what the system will do next from the rendered state without consulting hidden logs."],
        "owner_hints": ["designing-agent-autonomy-and-control"], "verifier_hints": ["critiquing-ai-trust-and-agency"],
        "capabilities": _caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-agentic-interaction-owners-v13"], "status": "active",
    },
]
