"""V13 collaboration and realtime rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


COLLABORATION_REALTIME_RULES_V13 = [
    {
        "rule_id": 'ui.collaboration.presence-distinguishes-viewing-editing', "domain": 'collaboration', "class": 'mechanical', "severity": 'moderate', "enforcement": 'warn',
        "title": 'Presence indicators must distinguish passive viewing from active editing authority',
        "statement": 'Presence UI that influences coordination must not collapse viewing, typing, editing, presenting, or disconnected states into a single generic online marker when those distinctions affect user decisions.',
        "intent": 'Give collaborators an accurate operational picture of who may currently change shared state without implying certainty beyond the presence signals the system actually has.',
        "applies_when": ['A shared surface shows collaborator presence while different activity or authority states can materially affect coordination.'], "does_not_apply_when": [],
        "failure_modes": ['A user is shown as generically active even though the system knows they are only viewing, are currently editing, or have lost the connection needed to participate.'],
        "user_impacts": ['Collaborators can avoid work unnecessarily, overwrite each other, or assume another person is available to coordinate when the indicator communicates the wrong participation state.'],
        "observables": ['Compare rendered presence with authoritative session and activity events and find materially different states represented by the same decision-relevant label or icon.'],
        "falsifiers": ['Presence states exposed to users correspond to distinctions the backend can actually support, and uncertain activity is represented as uncertain rather than inferred as editing.'],
        "repairs": ['Map authoritative presence signals into bounded states such as viewing, editing, presenting, idle, or reconnecting only where the product can support those claims.'],
        "exceptions": ['Products may intentionally expose only coarse presence when finer activity would violate privacy or lacks reliable instrumentation, provided the UI does not imply the missing distinction.'],
        "verification": ['Exercise viewing, editing, idle, reconnecting, and disconnected sessions and compare the visible presence model with server or session evidence.'],
        "owner_hints": ['designing-collaboration-and-presence'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.collaboration.remote-delete-does-not-destroy-local-draft', "domain": 'collaboration', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Remote deletion must not silently destroy an uncommitted local draft',
        "statement": 'If a collaborator deletes or removes the shared object while another user still has valid uncommitted local work, the client must preserve that local work in a recoverable conflict or draft state instead of erasing it during reconciliation.',
        "intent": 'Separate remote object lifecycle from local uncommitted authorship so concurrent deletion cannot turn synchronization into silent user-data loss.',
        "applies_when": ['A collaborative editor or form permits local draft work while the underlying shared object can be deleted, archived, or removed remotely.'], "does_not_apply_when": [],
        "failure_modes": ['A remote deletion event causes the local client to close or reset the editor and discard unsaved text, selections, attachments, or other valid local changes without recovery.'],
        "user_impacts": ['Users can lose substantial work because another collaborator changed object lifecycle while they were editing, even though their local draft was still recoverable.'],
        "observables": ['Create unsaved local edits, delete the object remotely, deliver the synchronization event, and inspect whether the local draft remains recoverable.'],
        "falsifiers": ['Remote deletion removes shared authority but the client preserves local work as a recoverable draft, copy, conflict record, or explicit export path before dismissing it.'],
        "repairs": ['Snapshot uncommitted local state before applying destructive remote lifecycle events and route it into a conflict or recovery surface that cannot accidentally resubmit to the deleted object.'],
        "exceptions": ['A security policy may require immediate local purge of highly sensitive content after access revocation; that policy must be explicit and distinct from ordinary collaborative deletion.'],
        "verification": ['Edit from one client, delete the shared object from another, synchronize both directions, and verify local uncommitted work is preserved or intentionally purged only under a documented policy.'],
        "owner_hints": ['designing-conflict-resolution'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.collaboration.conflict-resolution-preserves-both-versions', "domain": 'collaboration', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Conflict resolution must preserve both materially divergent versions until a resolution commits',
        "statement": 'When concurrent edits cannot be merged safely, the conflict UI must retain the competing versions or their recoverable content until the user or policy selects a resolution; opening the resolver must not itself discard one side.',
        "intent": 'Make conflict resolution a reversible decision boundary rather than a destructive overwrite disguised as a comparison screen.',
        "applies_when": ['Concurrent edits produce a merge conflict, divergent document state, or competing versions that cannot be reconciled automatically without potential information loss.'], "does_not_apply_when": [],
        "failure_modes": ['Entering or choosing a conflict flow overwrites one version before resolution commits, hides unique content from one side, or offers only a destructive keep-latest path without recovery.'],
        "user_impacts": ['Users can lose collaborators’ work while believing they are merely reviewing a conflict and may be unable to reconstruct the discarded version afterward.'],
        "observables": ['Create two divergent versions with unique content, open the conflict resolver, and trace whether both payloads remain accessible before and after previewing resolution choices.'],
        "falsifiers": ['Both materially distinct versions remain recoverable until an explicit resolution commits, and the chosen outcome records or preserves prior content according to the product history model.'],
        "repairs": ['Persist conflict inputs separately from the working copy, show the meaningful differences, and commit resolution as a new state without deleting source versions prematurely.'],
        "exceptions": ['A system with an explicit immutable last-writer policy may auto-resolve when users were clearly informed that concurrent alternatives are not retained and the use case accepts that loss model.'],
        "verification": ['Generate conflicting changes, enter resolution, switch between choices without committing, and verify both original versions remain intact until the final resolution boundary.'],
        "owner_hints": ['designing-conflict-resolution'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.collaboration.cursor-identity-stable', "domain": 'collaboration', "class": 'contextual', "severity": 'moderate', "enforcement": 'warn',
        "title": 'Collaborative cursor identity should remain stable across movement and rerender',
        "statement": 'When remote cursors or selections are attributed to collaborators, their visual identity must not reshuffle unpredictably because users rely on stable attribution to follow activity across the shared canvas or document.',
        "intent": 'Preserve social orientation in fast-moving collaborative surfaces without claiming stronger identity than the authenticated or session data actually provides.',
        "applies_when": ['The interface shows remote cursors, selections, carets, viewport indicators, or other continuously moving collaborator markers.'], "does_not_apply_when": [],
        "failure_modes": ['Colors, labels, avatars, or marker identities are reassigned between collaborators during rerenders, reconnects, or list-order changes without an identity change in the underlying session.'],
        "user_impacts": ['Users can follow the wrong collaborator, misinterpret who changed a region, or lose the ability to coordinate verbally around visible remote activity.'],
        "observables": ['Maintain several active collaborators while forcing rerenders and reconnects, then compare marker identity mapping against stable collaborator or session identifiers.'],
        "falsifiers": ['Each collaborator keeps a stable visible identity for the relevant session or the UI explicitly marks a new session or identity transition instead of silently reusing another marker.'],
        "repairs": ['Key visual attribution from stable collaborator or session identity rather than array order, transient cursor order, or non-deterministic rendering position.'],
        "exceptions": ['Color reuse may occur after a collaborator fully leaves and no simultaneous ambiguity remains, especially in systems with a bounded palette.'],
        "verification": ['Run multiple concurrent cursors through movement, reconnect, viewport changes, and participant list updates and verify attribution remains stable for each active identity.'],
        "owner_hints": ['designing-collaborative-cursors'], "verifier_hints": ['critiquing-user-experience'],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.collaboration.permission-change-revokes-action', "domain": 'collaboration', "class": 'behavioral', "severity": 'critical', "enforcement": 'block',
        "title": 'A live collaboration permission downgrade must revoke now-forbidden actions before commit',
        "statement": 'If a collaborator loses edit, comment, approve, share, or administrative authority while a shared surface is open, the client must revalidate the action at commit and must not rely solely on stale controls rendered under the old role.',
        "intent": 'Keep collaborative authority bound to current permission state so open tabs cannot preserve capabilities after an administrator or owner has revoked them.',
        "applies_when": ['Roles or sharing permissions can change while users keep long-lived collaborative sessions or editors open.'], "does_not_apply_when": [],
        "failure_modes": ['A user whose role was downgraded can still commit an action because the client cached authorization, or the UI reports success before the server rejects the stale authority.'],
        "user_impacts": ['Revoked users can modify protected shared state or receive misleading success from an action they no longer have authority to perform.'],
        "observables": ['Open an editor with edit authority, revoke it from another session, then attempt a protected action without reloading and inspect both UI and server result.'],
        "falsifiers": ['Protected commits are authorized against current policy, stale controls transition to a truthful denied or read-only state, and no forbidden mutation becomes authoritative.'],
        "repairs": ['Revalidate authorization at the action boundary, propagate permission changes to live clients, and reconcile stale UI into a denied or read-only state without dropping local work unnecessarily.'],
        "exceptions": ['A bounded offline mode may permit local drafting after online authority disappears, but it must not represent the draft as committed shared state until authorization is re-established.'],
        "verification": ['Change collaboration permissions while another client remains open and verify every now-forbidden action is blocked at authority commit and the local UI reconciles truthfully.'],
        "owner_hints": ['designing-collaboration-permissions'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.collaboration.offline-edits-rejoin-with-conflict-state', "domain": 'collaboration', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Offline collaborative edits must rejoin through reconciliation rather than overwrite newer shared state blindly',
        "statement": 'When a user edits shared content offline and later reconnects after other collaborators changed the same logical region, synchronization must reconcile or surface conflict instead of applying the offline snapshot as an unconditional replacement.',
        "intent": 'Protect both offline productivity and newer shared work by making reconnection a causal synchronization boundary rather than a full-state last-write race.',
        "applies_when": ['A collaborative product permits editing while temporarily disconnected and the same content can change remotely before reconnection.'], "does_not_apply_when": [],
        "failure_modes": ['Reconnect applies an offline snapshot over newer shared changes without version checks, merge semantics, or conflict surfacing for materially overlapping edits.'],
        "user_impacts": ['Users can erase others’ work simply by reconnecting with an older local state and may not realize the overwrite occurred.'],
        "observables": ['Take one client offline, edit overlapping content while another client commits a different change, reconnect, and inspect the authoritative merged or conflict result.'],
        "falsifiers": ['Reconnection compares causal or version state, merges non-conflicting changes, and surfaces overlapping conflicts or policy outcomes without silently replacing newer shared content.'],
        "repairs": ['Carry base or version identity with offline edits, reconcile operations rather than snapshots where possible, and route non-mergeable overlap through an explicit conflict contract.'],
        "exceptions": ['Some append-only collaboration models can safely merge offline operations without user-visible conflict when operation semantics guarantee no destructive overlap.'],
        "verification": ['Create overlapping and non-overlapping offline and online edits, reconnect in varied orders, and verify reconciliation preserves valid work according to the declared collaboration model.'],
        "owner_hints": ['designing-realtime-communication-systems'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["COLLABORATION_REALTIME_RULES_V13"]
