"""V13 consent-control rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

CONSENT_CONTROL_RULES_V13 = [
    {
        "rule_id":"ui.consent.preference-center-shows-effective-state","domain":"consent","class":"mechanical","severity":"major","enforcement":"block",
        "title":"A consent preference center must show the effective persisted state rather than only the last local toggle gesture",
        "statement":"Consent controls must reconcile from the authoritative preference state after save, policy enforcement, account sync, or server rejection so a toggle cannot remain visually enabled when the effective choice is different.",
        "intent":"Make privacy preference UI a truthful view of effective consent rather than an optimistic local form detached from behavior.",
        "applies_when":["Users manage persisted consent or privacy preferences through toggles, categories, purposes, or vendor controls."],"does_not_apply_when":[],
        "failure_modes":["A local toggle appears saved but the server rejected it, another policy overrides it, or reload shows a different effective state without earlier reconciliation."],
        "user_impacts":["Users can believe collection or processing was enabled or disabled when the effective preference says otherwise."],
        "observables":["Change preferences under successful, rejected, policy-locked, and cross-device updates and compare controls with authoritative effective state."],
        "falsifiers":["After each mutation the preference center reflects the effective persisted state and identifies controls that are policy-fixed or pending."],
        "repairs":["Separate draft toggle state from effective consent state, reconcile after authority response, and expose policy-controlled values as such."],
        "exceptions":["Unsaved preference forms may display draft choices before commit when the unsaved state is explicit and not represented as effective behavior."],
        "verification":["Exercise save success, rejection, policy override, reload, and remote change and verify displayed preferences match the behavior-controlling state."],
        "owner_hints":["designing-consent-preference-centers"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.consent.scope-expansion-requires-renewed-choice","domain":"consent","class":"behavioral","severity":"critical","enforcement":"block",
        "title":"Material expansion of a consented purpose must not inherit old consent silently",
        "statement":"If a previously chosen consent scope expands to a materially new purpose, data class, recipient, or processing behavior, the new scope must not be treated as already authorized solely because an older narrower preference was granted.",
        "intent":"Keep user authority bounded to the choice actually made when product behavior evolves.",
        "applies_when":["A consent-controlled feature changes purpose, data use, recipients, or other material scope after the user made the earlier choice."],"does_not_apply_when":[],
        "failure_modes":["A new broader behavior becomes enabled under the old consent record without a renewed authority boundary or policy-supported equivalent."],
        "user_impacts":["Users can have data used in ways they never selected while the interface claims their old consent covers it."],
        "observables":["Version a consent purpose from narrow to materially broader and inspect migration of stored preferences and runtime behavior."],
        "falsifiers":["Materially expanded scope remains disabled or pending until a valid renewed choice or other documented lawful authority exists."],
        "repairs":["Version consent scopes and compare effective behavior requirements against the version and dimensions the user actually authorized."],
        "exceptions":["Non-material wording clarification that does not change effective processing need not create a new choice solely because text changed."],
        "verification":["Test narrow-to-broad scope migrations and verify legacy granted records cannot automatically enable newly added material behavior."],
        "owner_hints":["designing-permissions-and-consent"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"semantic-product":"REQUIRED","browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.consent.optional-purpose-not-default-enabled","domain":"consent","class":"contextual","severity":"major","enforcement":"review",
        "title":"An optional consent purpose must not be represented as an already chosen preference when no valid prior choice exists",
        "statement":"For a genuinely optional purpose that requires user choice under the product’s consent model, initial UI state should not visually or behaviorally imply opt-in before a valid stored choice exists.",
        "intent":"Prevent presentation defaults from masquerading as user authorization.",
        "applies_when":["The product models a purpose as optional and choice-controlled rather than necessary or otherwise independently authorized."],"does_not_apply_when":[],
        "failure_modes":["A fresh user sees the optional purpose enabled and processing begins even though no prior valid preference or other authority exists."],
        "user_impacts":["Users can be enrolled in optional processing through default state rather than an actual choice."],
        "observables":["Inspect first-load control state and runtime behavior for accounts with no consent record."],
        "falsifiers":["No-choice state is distinct from granted state and optional behavior remains inactive until the product’s valid choice boundary is satisfied."],
        "repairs":["Represent unknown or not-chosen separately from granted, initialize optional behavior from authoritative preference records, and avoid deriving authority from component defaults."],
        "exceptions":["This rule does not determine legal basis; if processing is not actually choice-controlled, the UI should not misleadingly present it as optional consent at all."],
        "verification":["Create accounts with no prior record and verify control state and processing behavior do not fabricate an opt-in."],
        "owner_hints":["designing-consent-preference-centers"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"semantic-product":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.consent.essential-processing-not-fake-optional-toggle","domain":"consent","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Required processing must not be shown as a user-controllable consent toggle when disabling it has no effect",
        "statement":"If a data use is genuinely required for the requested service or is policy-fixed, the interface must not present an apparently editable optional toggle that cannot actually stop the behavior.",
        "intent":"Avoid false control in privacy settings and distinguish explanation from user authority.",
        "applies_when":["The preference center includes processing categories that are required, technically necessary, or otherwise not controlled by the displayed choice."],"does_not_apply_when":[],
        "failure_modes":["A toggle appears interactive or disableable but the underlying processing continues unchanged or the value snaps back without explaining that it is not optional."],
        "user_impacts":["Users believe they exercised privacy control that the system did not honor."],
        "observables":["Attempt to disable each claimed required category and inspect persisted state and controlled runtime behavior."],
        "falsifiers":["Non-optional processing is represented as fixed explanatory state rather than fake choice, with its role and any genuine controls distinguished."],
        "repairs":["Render required categories as informational or policy-fixed controls and reserve toggles for behavior the user can actually change."],
        "exceptions":["A control may disable an optional sub-feature while required base processing remains; the distinction must be explicit."],
        "verification":["Compare every preference control with the behavior it claims to govern and confirm apparent user choices have real effect."],
        "owner_hints":["designing-consent-preference-centers"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"semantic-product":"REQUIRED","browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.consent.cross-device-preference-reconciles","domain":"consent","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Account-level consent changes must reconcile across active devices before stale clients overwrite them",
        "statement":"When consent preferences are account-level, a stale client reconnecting after another device changed the preference must not restore an older choice through whole-state last-write behavior.",
        "intent":"Preserve the most authoritative consent state across devices and prevent stale preference snapshots from re-enabling revoked behavior.",
        "applies_when":["Consent or privacy preferences synchronize across multiple devices or sessions."],"does_not_apply_when":[],
        "failure_modes":["Device A revokes a preference, offline device B later reconnects with an older granted snapshot, and the account becomes granted again without a new choice."],
        "user_impacts":["Previously withdrawn optional processing can restart because of stale-device synchronization."],
        "observables":["Change a preference while another device is offline, reconnect the stale device, and inspect account-level state and behavior."],
        "falsifiers":["Synchronization uses versioned or monotonic preference semantics so stale state cannot silently reverse a newer authority change."],
        "repairs":["Version consent decisions and reconcile by decision identity or server authority instead of replacing the preference object from a stale client snapshot."],
        "exceptions":["Device-local permissions such as OS camera access are distinct from account-level consent and may legitimately differ per device."],
        "verification":["Exercise grant and revoke sequences across offline devices and verify stale reconnect cannot reverse the latest authoritative choice silently."],
        "owner_hints":["designing-consent-preference-centers"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.consent.withdrawal-does-not-erase-required-record-without-policy","domain":"consent","class":"contextual","severity":"major","enforcement":"review",
        "title":"Withdrawing consent must stop controlled future behavior without pretending every historical record must or can be erased",
        "statement":"A withdrawal flow should separate stopping future consent-controlled processing from deletion or retention of historical records governed by other product or policy obligations, rather than promise universal erasure it cannot enforce.",
        "intent":"Keep withdrawal, deletion, and retention semantics truthful and independently actionable where the system distinguishes them.",
        "applies_when":["The product stores historical consent records, transactions, security logs, or other records after consent-controlled behavior can be withdrawn."],"does_not_apply_when":[],
        "failure_modes":["The UI says withdrawing consent deletes all historical data while required records remain, or deletes records necessary for an independent retention contract without communicating the distinction."],
        "user_impacts":["Users receive false privacy assurances or the product destroys records that another declared obligation requires."],
        "observables":["Withdraw consent and inspect future behavior, historical records, deletion workflows, and user-facing retention explanations."],
        "falsifiers":["Withdrawal stops the behavior it controls and separately communicates or routes deletion and retained-record semantics according to the product’s actual policy."],
        "repairs":["Model consent authority, data deletion, and retention as separate lifecycle concerns and ensure UI promises match the behavior of each."],
        "exceptions":["Where product policy truly requires immediate deletion of all associated records, withdrawal and deletion may coincide if the implementation enforces that same boundary."],
        "verification":["Test withdrawal with retained and deletable record classes and verify future processing and historical retention match declared semantics."],
        "owner_hints":["designing-privacy-control-centers"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"semantic-product":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["CONSENT_CONTROL_RULES_V13"]
