"""Independently authored V13 rules for tables, analytical data, and visualization truth."""
from __future__ import annotations


def _caps(**overrides: str) -> dict[str, str]:
    values = {
        "static": "PARTIAL", "dom": "PARTIAL", "computed-style": "PARTIAL",
        "browser-runtime": "PARTIAL", "interaction": "PARTIAL", "accessibility-tree": "PARTIAL",
        "visual-render": "REQUIRED", "semantic-product": "REQUIRED", "cross-generation": "UNSUPPORTED",
        "human-review": "PARTIAL",
    }
    values.update(overrides)
    return values


DATA_VIZ_RULES_V13 = [
    {
        "rule_id": "ui.data.sort-preserves-row-identity", "domain": "data", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Sorting a collection must preserve row identity, selection, and row-bound state",
        "statement": "When records are sorted or resorted, row-local selection, expansion, editing, focus, validation, and pending state must follow stable record identity rather than the previous visual index.",
        "intent": "Prevent visual reordering from silently attaching user state to a different record merely because that record moved into the same row position.",
        "applies_when": ["A table, grid, list, tree, or other record collection supports sorting while rows can also hold selection, expansion, edit state, focus, draft input, or asynchronous status."],
        "does_not_apply_when": ["Rows are purely presentational, contain no persistent row-bound interaction state, and sorting cannot change the meaning of any local UI state."],
        "failure_modes": ["After sorting, a selected, expanded, edited, focused, or pending state remains attached to a row index and therefore appears on a different record than the one the user acted on."],
        "user_impacts": ["Users may edit, delete, inspect, or interpret the wrong record because the interface visually preserved state while changing the entity that state refers to."],
        "observables": ["Apply row-local state, change sort order so the target record moves, and observe whether that state follows the record's stable identity or remains at the original position."],
        "falsifiers": ["Every row-bound state follows the stable record identity through sorting and disappears or reconciles explicitly only when the underlying record itself is removed or invalidated."],
        "repairs": ["Key row-local UI state by durable record identity, reconcile pending edits and focus after resort, and avoid using rendered index as the authoritative state key."],
        "exceptions": ["A position-based workflow may intentionally bind state to a rank slot only when the slot itself is the semantic entity and the interface clearly communicates that model."],
        "verification": ["Select, expand, edit, and focus representative records, resort them into new positions, and confirm each state remains attached to the intended record identity."],
        "owner_hints": ["designing-table-sorting"], "verifier_hints": ["critiquing-functional-completeness"], "capabilities": _caps(**{"interaction": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.hidden-transformation-count-visible", "domain": "data", "class": "contextual", "severity": "major", "enforcement": "warn",
        "title": "A transformed collection should reveal when unseen records are excluded from the view",
        "statement": "When filters, search, scopes, permissions, or grouping hide records that users might otherwise expect in a collection, the interface should expose enough result and transformation context to distinguish absence from exclusion.",
        "intent": "Reduce false conclusions that a record does not exist simply because the current view silently excludes it.",
        "applies_when": ["A collection can display a subset of an underlying dataset and users make decisions about completeness, counts, missing records, or follow-up actions from the visible result set."],
        "does_not_apply_when": ["The surface is explicitly a narrow query result where the filter itself is the primary visible context and no reasonable completeness inference exists."],
        "failure_modes": ["The visible collection appears complete even though active transformations or hidden scopes exclude additional relevant records without any visible count or state cue."],
        "user_impacts": ["Users may conclude that records are missing, complete work on an incomplete subset, or apply bulk decisions without realizing the current view excludes other data."],
        "observables": ["Compare the visible set with the underlying eligible set and determine whether active filters, hidden scopes, or grouping reductions are visible near the collection and reflected in result counts."],
        "falsifiers": ["The view clearly communicates its active transformation or result scope, including a meaningful count or reset path when excluded records affect user interpretation."],
        "repairs": ["Surface active transformation state and result scope near the collection, show counts that distinguish visible from broader eligible records where useful, and provide a clear reset or scope change path."],
        "exceptions": ["Security-sensitive hidden records must not be disclosed through counts when even their existence is unauthorized; scope communication should remain within permitted disclosure."],
        "verification": ["Apply several filters and permission/scope combinations, then verify a user can tell whether the visible records represent the full eligible set without inspecting hidden query state."],
        "owner_hints": ["designing-table-filtering"], "verifier_hints": ["critiquing-user-experience"], "capabilities": _caps(), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.aggregate-scope-explicit", "domain": "data", "class": "contextual", "severity": "major", "enforcement": "block",
        "title": "Aggregated metrics must expose the population and transformation scope they summarize",
        "statement": "A total, average, rate, percentage, percentile, or other aggregate must not appear detached from the filtered population, time interval, grouping basis, or missing-data treatment that determines its meaning when those choices can change decisions.",
        "intent": "Prevent mathematically valid numbers from becoming misleading because the interface hides which records and transformations produced them.",
        "applies_when": ["An analytical or operational surface presents aggregate values that can change under filters, date ranges, scopes, grouping, exclusions, sampling, or missing-data policy."],
        "does_not_apply_when": ["The aggregate's population and basis are fixed by an unambiguous nearby context that cannot vary within the surface."],
        "failure_modes": ["A metric updates under hidden or distant transformations but retains a label that implies a broader or different population than the value actually summarizes."],
        "user_impacts": ["Users can compare incompatible numbers, make decisions on the wrong population, or mistake a filtered subset for an organization-wide result."],
        "observables": ["Changing filter or scope state materially changes the aggregate while the rendered metric provides no recoverable indication of the active population, time basis, or exclusion rules."],
        "falsifiers": ["The aggregate label, surrounding scope controls, or inspectable definition makes the summarized population and material transformations clear at the point of interpretation."],
        "repairs": ["Bind aggregate presentation to active query scope, expose decision-relevant filters/time basis, and document special missingness, weighting, sampling, or exclusion logic when it materially changes interpretation."],
        "exceptions": ["Fixed contractual metrics may use a stable named definition instead of repeating the full formula when users can readily inspect that definition and it is not overridden by local view state."],
        "verification": ["Change each transformation that affects the aggregate and verify the visible scope or definition updates so two differently scoped values cannot be mistaken as directly equivalent."],
        "owner_hints": ["designing-data-dense-interfaces"], "verifier_hints": ["critiquing-user-experience"], "capabilities": _caps(**{"semantic-product": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.chart-uncertainty-not-false-certainty", "domain": "data", "class": "contextual", "severity": "major", "enforcement": "warn",
        "title": "Charts must not render uncertain estimates with stronger certainty than the source supports",
        "statement": "Forecasts, modeled values, confidence intervals, imputed points, provisional observations, and other uncertain data must remain distinguishable from confirmed observations when uncertainty affects interpretation or decisions.",
        "intent": "Keep visual polish from collapsing epistemic differences that exist in the underlying data and model.",
        "applies_when": ["A visualization combines observed and estimated values, forecast ranges, confidence or credible intervals, imputed gaps, provisional data, or another source of decision-relevant uncertainty."],
        "does_not_apply_when": ["The uncertainty is immaterial at the intended decision scale and the product's documented analytical contract intentionally treats the values as equivalent for that use."],
        "failure_modes": ["Estimated or uncertain values use the same visual encoding and labeling as confirmed observations even though the source distinguishes their confidence, status, or range."],
        "user_impacts": ["Users may treat forecasts or inferred values as measured facts, overestimate precision, or fail to account for uncertainty in consequential comparisons."],
        "observables": ["Trace chart marks to the underlying records and identify uncertain classes that have no distinct visual, textual, or inspectable uncertainty representation in the rendered chart."],
        "falsifiers": ["Decision-relevant uncertainty is encoded or disclosed in a way that remains interpretable with the chart's legends, labels, tooltips, and nonvisual equivalent."],
        "repairs": ["Use an appropriate uncertainty channel such as interval, band, mark style, status annotation, or explicit qualifier, and keep the same uncertainty semantics in accessible alternatives."],
        "exceptions": ["Dense monitoring views may defer detailed uncertainty to inspection when the overview still distinguishes provisional or modeled data sufficiently for the decisions made there."],
        "verification": ["Compare known, estimated, forecast, and provisional records in both the visual and nonvisual reading path and verify users can identify which claims carry uncertainty."],
        "owner_hints": ["designing-uncertainty-visualization"], "verifier_hints": ["critiquing-research-validity"], "capabilities": _caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.time-series-timezone-basis-visible", "domain": "data", "class": "contextual", "severity": "major", "enforcement": "block",
        "title": "Time-series displays need an explicit timezone basis when boundaries can change meaning",
        "statement": "Charts, buckets, logs, and summaries that group or compare events by time must expose the timezone or calendar basis whenever a different basis would move events between periods or change an operational conclusion.",
        "intent": "Prevent apparently precise temporal analysis from hiding a timezone transformation that changes which interval an event belongs to.",
        "applies_when": ["A time-series spans users, systems, or operations across time zones, daylight-saving changes, locale boundaries, or server-versus-user time bases and the bucket boundary matters."],
        "does_not_apply_when": ["All timestamps are inherently in one fixed and obvious operational timezone and users cannot plausibly interpret the display under another basis."],
        "failure_modes": ["The UI groups or labels events by a timezone that is not visible, allowing the same timestamp to appear in a different day/hour bucket than users reasonably expect."],
        "user_impacts": ["Users may compare wrong periods, miss incidents around boundaries, or make scheduling and operational decisions from an unstated temporal basis."],
        "observables": ["Render the same dataset under different user or system timezone settings and observe a material bucket/label change without corresponding visible timezone context."],
        "falsifiers": ["The chart or nearby scope control names the operative timezone/calendar basis and any conversion preserves the represented instant and intended aggregation semantics."],
        "repairs": ["Choose an explicit analysis timezone, expose it near time controls or labels, and keep bucket generation, tooltips, export, and nonvisual summaries on the same basis."],
        "exceptions": ["Personal local-time views may omit repeated timezone labels when local time is a stable product convention and cross-zone comparison is not part of the task."],
        "verification": ["Test records around midnight and daylight-saving boundaries under multiple supported timezone settings and confirm labels, buckets, exports, and stated basis remain coherent."],
        "owner_hints": ["designing-time-zone-selection"], "verifier_hints": ["critiquing-localization"], "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.virtualized-selection-keeps-identity", "domain": "data", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Virtualized collections must keep selection independent from recycled rendered rows",
        "statement": "In a virtualized table or list, selection and row-bound commands must be keyed to stable data identity so recycling DOM nodes or window positions cannot transfer selection to a different record during scroll or refresh.",
        "intent": "Keep rendering optimization from changing the authoritative selection model users rely on for inspection and bulk actions.",
        "applies_when": ["A large list, grid, table, tree, or timeline reuses rendered row containers while users can select records, invoke row actions, or maintain range/multi-selection across scrolling."],
        "does_not_apply_when": ["The virtualized surface has no row-bound persistent interaction state and recycled nodes cannot affect any user-visible selection or action target."],
        "failure_modes": ["As rows are recycled or data is refreshed, selected visual state follows a rendered slot or stale index and appears on a different record than the selected identity."],
        "user_impacts": ["Bulk actions or follow-up commands can target unintended records after scrolling, making a performance optimization directly corrupt user intent."],
        "observables": ["Select records, scroll far enough to recycle their DOM nodes, return or refresh the data, and inspect whether selection remains associated with the original stable identities."],
        "falsifiers": ["Selection state is stored against stable record identity, recycled nodes derive their visual state from that model, and removed records reconcile explicitly rather than transferring selection."],
        "repairs": ["Separate the selection model from the rendered window, key it by durable identity, and recompute recycled row presentation from authoritative selection on every bind."],
        "exceptions": ["A deliberately positional selection model may bind to slots only when the slot itself is the semantic entity and bulk actions operate on positions rather than records."],
        "verification": ["Exercise sparse and range selections across several virtualization windows, insert and remove records, then confirm selected identities and action scope remain exact."],
        "owner_hints": ["designing-accessible-data-table-navigation"], "verifier_hints": ["critiquing-functional-completeness"], "capabilities": _caps(**{"interaction": "REQUIRED", "browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.color-legend-distinguishes-state-from-category", "domain": "data", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "A legend must not reuse indistinguishable color semantics for category and state",
        "statement": "When color communicates both categorical identity and status such as selected, warning, failed, inactive, or forecast, the encoding must keep those semantic dimensions distinguishable rather than overloading one hue system ambiguously.",
        "intent": "Prevent a visually attractive palette from forcing users to guess whether a color difference means what an item is or what condition it is in.",
        "applies_when": ["Charts, maps, matrices, dashboards, timelines, or analytical controls use color for more than one independent semantic dimension within the same comparison context."],
        "does_not_apply_when": ["The dimensions never appear together or another dominant channel makes their meanings unambiguous without relying on color distinction."],
        "failure_modes": ["The same or perceptually similar color treatment represents both membership in a category and a transient status, causing marks with different semantics to become visually confusable."],
        "user_impacts": ["Users can misclassify entities, overlook alerts, or interpret a selection/status change as a change in data category."],
        "observables": ["Inspect the legend and representative marks and identify colors whose meaning changes between category, status, selection, or confidence without an independent shape, position, label, or texture cue."],
        "falsifiers": ["Each semantic dimension has a consistent legend and at least one independent distinguishable channel so users do not need to infer meaning from overloaded hue alone."],
        "repairs": ["Reserve color roles by semantic dimension, introduce another encoding channel where dimensions overlap, and align legends, states, and accessible text with the same mapping."],
        "exceptions": ["Small local interactions may reuse a brand accent for selection when category identity is encoded independently and no legend-level ambiguity is created."],
        "verification": ["Review mixed category and state examples with color desaturated or unavailable, then confirm each mark's category and current status remain separately identifiable."],
        "owner_hints": ["designing-data-visualization"], "verifier_hints": ["critiquing-accessibility"], "capabilities": _caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.data.visualization-has-nonvisual-reading-path", "domain": "data", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Decision-relevant visualization content requires a usable nonvisual reading path",
        "statement": "A chart or spatial data graphic that communicates information needed to complete a task must expose the relevant values, relationships, trends, or conclusions through accessible structured text or data rather than requiring sight of graphical marks.",
        "intent": "Preserve access to analytical meaning without pretending that an image description alone can replace every interactive data task.",
        "applies_when": ["A visualization conveys decision-relevant values, comparisons, alerts, trends, or selectable data and the product supports users who cannot reliably perceive the visual encoding."],
        "does_not_apply_when": ["The graphic is purely decorative and communicates no information or operation beyond content already available equivalently nearby."],
        "failure_modes": ["The only way to obtain the values or relationships necessary for the task is to visually inspect marks, hover-only tooltips, color, position, or geometry that has no accessible equivalent."],
        "user_impacts": ["Screen-reader and nonvisual users cannot perform the same analytical decision or retrieve the information that sighted users obtain from the visualization."],
        "observables": ["Navigate with nonvisual assistive technology and attempt to identify the same key values, categories, trends, and actionable data points available through the visual chart."],
        "falsifiers": ["A structured summary, table, accessible data navigation model, or equivalent representation exposes the required analytical information and actions without relying on visual mark perception."],
        "repairs": ["Provide an appropriate nonvisual representation tied to the same data and transformation state, including labels and action targets needed for the actual analytical task."],
        "exceptions": ["Free-form exploratory spatial analysis may not have a one-to-one textual equivalent, but task-critical findings and operations still need an accessible path or explicitly bounded alternative workflow."],
        "verification": ["Complete representative analytical questions using the nonvisual path alone and compare the obtainable values, scope, filters, and actions with those available from the rendered visualization."],
        "owner_hints": ["designing-nonvisual-chart-equivalents"], "verifier_hints": ["critiquing-accessibility"], "capabilities": _caps(**{"accessibility-tree": "REQUIRED", "interaction": "REQUIRED"}), "provenance_ids": ["nui-data-viz-owners-v13"], "status": "active",
    },
]
