"""V13 device and capture rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

DEVICE_CAPTURE_RULES_V13 = [
    {
        "rule_id":"ui.capture.permission-denial-preserves-alternative-path","domain":"capture","class":"contextual","severity":"major","enforcement":"block",
        "title":"Capture permission denial must preserve an available alternative when the task does not inherently require live capture",
        "statement":"If users can satisfy the same task by choosing an existing file, manual entry, or another supported source, denying camera or microphone permission must not trap them in a live-capture-only flow.",
        "intent":"Keep optional hardware permission separate from the underlying user goal.",
        "applies_when":["A capture flow has a supported non-live alternative such as upload, gallery choice, code entry, or document selection."],"does_not_apply_when":[],
        "failure_modes":["Denying capture permission leaves no path forward even though the product supports an equivalent non-capture source elsewhere."],
        "user_impacts":["Users are coerced into granting hardware access or abandon a task that could be completed without it."],
        "observables":["Deny or permanently disable capture permission and inspect whether valid alternate acquisition paths remain reachable."],
        "falsifiers":["The flow explains the unavailable capture path and offers supported alternatives without repeatedly forcing the same permission prompt."],
        "repairs":["Model source selection before permission gating and route denial to an alternate source choice when domain semantics permit it."],
        "exceptions":["A feature whose intrinsic purpose is live camera or microphone operation may legitimately require that hardware, with truthful explanation."],
        "verification":["Test first denial, permanent denial, and later enablement while completing the task through every supported alternate source."],
        "owner_hints":["designing-camera-capture-flows"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.capture.orientation-metadata-not-double-applied","domain":"capture","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Capture orientation metadata must not be applied twice across preview and stored output",
        "statement":"When camera or image pipelines normalize pixel orientation and also retain orientation metadata, rendering and export must avoid applying both transformations and rotating or mirroring content again.",
        "intent":"Preserve the physical orientation users captured across preview, processing, storage, and later display.",
        "applies_when":["Captured images or documents can include EXIF or device orientation metadata or pixel normalization transforms."],"does_not_apply_when":[],
        "failure_modes":["The preview appears correct but the saved or uploaded image is rotated or mirrored because metadata and pixel transform were both applied."],
        "user_impacts":["Users submit incorrectly oriented documents or media despite approving a correct preview."],
        "observables":["Capture in multiple device orientations and compare raw metadata, preview transform, stored pixels, and final downstream render."],
        "falsifiers":["Exactly one orientation interpretation governs the authoritative output and preview matches saved or uploaded content."],
        "repairs":["Normalize either pixels or metadata at a defined pipeline boundary and clear or preserve orientation metadata consistently afterward."],
        "exceptions":["Formats without orientation metadata may rely solely on explicit pixel transforms."],
        "verification":["Test portrait, landscape, front-camera mirror, imported media, and downstream re-rendering and verify orientation remains stable."],
        "owner_hints":["designing-camera-capture-flows"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"visual-render":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.capture.retake-does-not-upload-rejected-capture","domain":"capture","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Choosing retake must prevent the rejected capture from becoming the authoritative upload",
        "statement":"When users reject a preview and request a retake, asynchronous processing or upload from the rejected capture must be cancelled or quarantined so its late completion cannot replace the accepted retake.",
        "intent":"Keep user approval bound to the exact captured media they accepted.",
        "applies_when":["Capture supports preview, retake, asynchronous processing, compression, OCR, or upload."],"does_not_apply_when":[],
        "failure_modes":["Capture A is rejected, capture B is accepted, then a late upload or processing result for A becomes the submitted attachment or document."],
        "user_impacts":["Users can submit an image they explicitly rejected, including sensitive or poor-quality content."],
        "observables":["Delay processing of capture A, retake B, accept B, then complete A late and inspect the authoritative submitted media identity."],
        "falsifiers":["Only accepted capture identity can become authoritative and late work for rejected captures is ignored or safely discarded."],
        "repairs":["Assign capture IDs and approval lifecycle, cancel or invalidate rejected processing, and gate final attachment assignment by the currently accepted ID."],
        "exceptions":["Products intentionally retaining rejected takes in a private gallery may do so if those takes cannot silently become submitted output."],
        "verification":["Force out-of-order capture processing across repeated retakes and verify only the accepted take is submitted."],
        "owner_hints":["designing-camera-capture-flows"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.capture.document-page-order-stable","domain":"capture","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Multi-page document capture must preserve explicit page order through processing and upload",
        "statement":"Reordering, rescanning, deleting, cropping, or asynchronously processing pages must not change the submitted page sequence because completion events arrive in another order.",
        "intent":"Preserve document narrative and legal meaning independent of capture-processing latency.",
        "applies_when":["Users scan or capture multi-page documents and can edit page sequence before submission."],"does_not_apply_when":[],
        "failure_modes":["Pages are stored or assembled by processing completion order, array index reuse, or stale thumbnails rather than the user-approved sequence."],
        "user_impacts":["Forms, contracts, receipts, or identity documents can be submitted in the wrong order."],
        "observables":["Capture pages with varied processing delays, reorder and replace pages, then compare approved sequence with generated document."],
        "falsifiers":["Stable page IDs and explicit ordering determine final assembly regardless of processing order."],
        "repairs":["Persist page identity and order separately from asynchronous processing state and assemble only from the approved ordered list."],
        "exceptions":["Single-page capture has no page-order contract."],
        "verification":["Exercise reorder, delete, rescan, rotation, and out-of-order processing and verify final document sequence matches approval preview."],
        "owner_hints":["designing-document-scanning-capture"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED","visual-render":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.device.disconnect-during-action-reconciles-authority","domain":"device","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Device disconnect during an action must reconcile whether the physical effect actually committed",
        "statement":"When connection drops while controlling or configuring an external device, the UI must not infer success or failure solely from transport loss if the device may already have applied the command.",
        "intent":"Prevent duplicate commands and false device state after an ambiguous hardware boundary.",
        "applies_when":["The interface sends state-changing commands to Bluetooth, local, embedded, robotic, peripheral, or other connected devices."],"does_not_apply_when":[],
        "failure_modes":["Disconnect after command send causes immediate failure and retry even though the device applied it, or claims success without later state confirmation."],
        "user_impacts":["Users can repeat physical actions, misconfigure devices, or trust a UI state that diverges from hardware."],
        "observables":["Drop connectivity before send, after send, and before acknowledgement and compare UI state with device state after reconnect."],
        "falsifiers":["Ambiguous completion becomes pending or unknown and reconnect queries or otherwise reconciles authoritative device state before enabling unsafe retry."],
        "repairs":["Use command identity and post-reconnect state reconciliation, separating transport acknowledgement from physical state confirmation."],
        "exceptions":["Read-only commands without side effects can be retried freely when duplication cannot change device state."],
        "verification":["Inject disconnect at command lifecycle boundaries and confirm recovery converges UI and device state without duplicate effects."],
        "owner_hints":["designing-device-integration-interfaces"],"verifier_hints":["critiquing-human-factors-and-safety"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED","semantic-product":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.device.hardware-selection-not-label-only","domain":"device","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Hardware selection must bind to stable device identity rather than display name alone",
        "statement":"When multiple nearby or previously paired devices can share the same human-readable name, selection and subsequent commands must remain tied to stable device identity and expose disambiguating context where users need it.",
        "intent":"Prevent commands or capture from being routed to the wrong physical device because names collide or change.",
        "applies_when":["Users select among multiple external devices and display names are non-unique, editable, localized, or reused by manufacturers."],"does_not_apply_when":[],
        "failure_modes":["The UI or command layer uses device label as the identifier so two same-name devices can swap state or receive each other’s actions."],
        "user_impacts":["Users can connect to, configure, record from, or control the wrong physical hardware."],
        "observables":["Pair same-name devices, rename them, change discovery order, and compare selected UI item with stable hardware/session identifier used for commands."],
        "falsifiers":["Selection is keyed by stable identity and the UI provides enough secondary context to distinguish simultaneously reachable same-name devices."],
        "repairs":["Bind state to stable platform device IDs or authenticated identities and use label only as presentation metadata."],
        "exceptions":["A platform may intentionally rotate privacy-preserving identifiers; the session must still maintain an unambiguous identity binding while active."],
        "verification":["Exercise same-name, rename, reconnect, and discovery-order changes and verify commands remain targeted to the selected physical device."],
        "owner_hints":["designing-device-integration-interfaces"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["DEVICE_CAPTURE_RULES_V13"]
