"""V13 file lifecycle rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


FILE_LIFECYCLE_RULES_V13 = [
    {
        "rule_id": 'ui.files.upload-queue-item-identity', "domain": 'files', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Each queued upload must retain stable file identity across retries, reorder, and duplicate names',
        "statement": 'Multi-file upload queues must associate progress, errors, retries, cancellation, and final server results with stable file identities rather than display name or current list position.',
        "intent": 'Prevent progress or actions for one file from being applied to another when users upload duplicate names, reorder the queue, or retry individual items.',
        "applies_when": ['The product uploads multiple files concurrently or sequentially and users can retry, reorder, cancel, remove, or add items while work is active.'], "does_not_apply_when": [],
        "failure_modes": ['Queue state is keyed by filename or index so duplicate names or reordering can transfer progress, errors, cancellation, or completion to the wrong file.'],
        "user_impacts": ['Users can cancel or retry the wrong transfer, see incorrect progress, or associate a server result with a different local file than the one they selected.'],
        "observables": ['Upload duplicate filenames with different content, reorder items during transfer, retry one failure, and trace progress and actions to local and server-side file identities.'],
        "falsifiers": ['Every queue item keeps a stable identity from selection through terminal server result regardless of visible name collisions or list reordering.'],
        "repairs": ['Generate a stable client upload identity per selected file, bind transport and UI state to it, and map the authoritative server object back to that identity on completion.'],
        "exceptions": ['A single-file uploader with no concurrent queue may use the active transfer object directly when no identity ambiguity can exist.'],
        "verification": ['Exercise duplicate names, reorder, retry, cancellation, and late completion events and verify each event applies only to its original queue item.'],
        "owner_hints": ['designing-multi-file-upload-queues'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.files.resume-validates-source-version', "domain": 'files', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Resuming an interrupted upload must verify that the local source still matches the partial transfer',
        "statement": 'A resumable upload must not append bytes from a changed local file onto partial content created from an older version without validating file identity, size, checksum, version, or another trustworthy continuity token.',
        "intent": 'Prevent resumed transfers from producing corrupted remote files that combine byte ranges from different local source versions.',
        "applies_when": ['An interrupted file transfer can resume later and the local source may change between the initial and resumed attempts.'], "does_not_apply_when": [],
        "failure_modes": ['Resume continues from the previous byte offset even though the selected file changed content or version while retaining a compatible path or name.'],
        "user_impacts": ['Users can successfully upload a corrupted hybrid file while the interface reports an ordinary resumed completion.'],
        "observables": ['Start a resumable transfer, modify or replace the local source, then resume and inspect whether the transport detects the source-version mismatch.'],
        "falsifiers": ['Resume proceeds only when source continuity is verified; otherwise the client explicitly restarts or asks the user to select the intended current source.'],
        "repairs": ['Persist resumable metadata including source identity or integrity evidence and revalidate it before sending additional ranges to the existing remote upload session.'],
        "exceptions": ['Platforms that guarantee immutable file handles for the lifetime of the resumable session may rely on that guarantee instead of recalculating content identity.'],
        "verification": ['Interrupt uploads, mutate source size or content where supported, resume, and verify mismatches trigger safe restart or explicit recovery rather than hybrid completion.'],
        "owner_hints": ['designing-resumable-file-uploads'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.files.rename-conflict-no-silent-overwrite', "domain": 'files', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Rename or move conflicts must not silently overwrite a different existing file',
        "statement": 'When a rename or move targets a path already occupied by another object, the interface and operation must apply the product’s explicit conflict policy rather than replacing the existing object without a visible decision.',
        "intent": 'Protect file identity and existing content when namespace changes collide under concurrent or user-driven operations.',
        "applies_when": ['Users can rename or move files or folders into namespaces where the target name may already exist or appear concurrently.'], "does_not_apply_when": [],
        "failure_modes": ['The operation succeeds by replacing, merging with, or hiding an existing different object without exposing that conflict and the consequences before commit.'],
        "user_impacts": ['Users can lose or detach existing content while believing they only renamed or moved another file.'],
        "observables": ['Create target-name collisions including concurrent creation, execute rename or move, and inspect resulting object identities and conflict feedback.'],
        "falsifiers": ['The operation blocks, disambiguates, versions, or explicitly confirms the documented conflict action while preserving both objects unless the user chooses replacement.'],
        "repairs": ['Perform an authoritative collision check at commit, surface conflict choices tied to object identity, and avoid using stale directory listings as proof the target is free.'],
        "exceptions": ['Systems with immutable versioned namespaces may auto-create a new version when that semantic is explicit and no prior version becomes inaccessible.'],
        "verification": ['Exercise same-folder rename, cross-folder move, case variants, and concurrent target creation and verify existing objects are never silently lost.'],
        "owner_hints": ['designing-file-rename-move-conflicts'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.files.share-expiry-visible', "domain": 'files', "class": 'contextual', "severity": 'moderate', "enforcement": 'warn',
        "title": 'Expiring file shares must make the operative expiry state visible where users manage or send them',
        "statement": 'If a file share can expire by date, duration, policy, or revocation, management and sending surfaces should expose enough expiry context that users do not present a link as durable when it is about to stop working.',
        "intent": 'Align sharing decisions with actual access lifetime without falsely promising availability after policy or owner changes.',
        "applies_when": ['Users create, copy, send, or manage share links whose access can expire automatically or under a configured policy.'], "does_not_apply_when": [],
        "failure_modes": ['A share appears active with no recoverable expiry context even though the system knows it will expire soon or has a specific terminal time.'],
        "user_impacts": ['Users can distribute links that fail unexpectedly for recipients or mistake a temporary share for persistent access.'],
        "observables": ['Create shares with different expiry policies and inspect copy, send, and manage surfaces for the effective expiration state and timezone basis.'],
        "falsifiers": ['The relevant surface exposes expiration or clearly indicates policy-controlled lifetime, and expired shares transition to a truthful inaccessible state.'],
        "repairs": ['Carry authoritative expiry metadata with share objects and display it at creation, management, and high-consequence send or copy points using unambiguous time semantics.'],
        "exceptions": ['Highly compact surfaces may omit repeated dates when an adjacent persistent policy summary clearly governs all listed shares.'],
        "verification": ['Create, copy, send, expire, extend, and revoke shares and verify visible lifecycle state matches the access service throughout.'],
        "owner_hints": ['designing-file-sharing-expiration'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.files.preview-not-authoritative-download', "domain": 'files', "class": 'mechanical', "severity": 'moderate', "enforcement": 'warn',
        "title": 'A generated preview must not be presented as the authoritative original file',
        "statement": 'File previews that use transcoding, rasterization, extraction, redaction, compression, partial loading, or cached derivatives must remain distinguishable from the original downloadable object when fidelity or completeness can differ.',
        "intent": 'Prevent users from treating a convenience preview as proof that the authoritative file has identical content, quality, metadata, or version.',
        "applies_when": ['The product renders a file using a derivative, converted preview, extracted text, thumbnail, cached representation, or partial stream rather than the exact original bytes.'], "does_not_apply_when": [],
        "failure_modes": ['The preview is labeled or acted on as though it is the original despite known possible differences in pages, fonts, color, metadata, redaction, version, or supported features.'],
        "user_impacts": ['Users can approve, review, or share conclusions based on a derivative that omits or alters content relative to the authoritative file.'],
        "observables": ['Compare preview provenance and displayed version with the original object and inspect whether derivative limitations or stale versions are recoverable from the UI.'],
        "falsifiers": ['The UI distinguishes preview from original where fidelity matters, identifies stale or converted state when known, and keeps download or open-original actions bound to the authoritative object.'],
        "repairs": ['Track preview source version and transformation metadata and expose a clear path to the original instead of reusing derivative state as file authority.'],
        "exceptions": ['Lossless byte-identical streaming views need no derivative warning when the rendered content is demonstrably the same authoritative object.'],
        "verification": ['Test converted, stale, partially supported, and current previews and verify users can identify when they are not viewing the authoritative original.'],
        "owner_hints": ['designing-file-preview-surfaces'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.files.storage-limit-before-transfer', "domain": 'files', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Known storage or quota limits should be checked before wasting a large transfer that cannot commit',
        "statement": 'When the service already knows a user, project, device, or destination lacks sufficient quota for a selected transfer, the interface should surface the blocking condition before or early in transfer rather than accepting all bytes and failing only at commit.',
        "intent": 'Avoid predictable bandwidth and time waste while keeping dynamic quota races honest when availability can change during the upload.',
        "applies_when": ['A file transfer has a known or estimable size and the destination exposes authoritative storage, quota, policy, or maximum-object limits before upload completion.'], "does_not_apply_when": [],
        "failure_modes": ['The client starts or completes a large transfer despite authoritative preflight evidence that the object cannot be committed because of a hard size or quota boundary.'],
        "user_impacts": ['Users spend bandwidth and time on an operation that the product already knew could not succeed, especially harmful on constrained connections or large media transfers.'],
        "observables": ['Select transfers beyond current quota and compare preflight knowledge with when the UI reports the failure and whether transport unnecessarily begins.'],
        "falsifiers": ['Known hard limits block or warn before expensive transfer; dynamic races are handled as runtime errors without pretending preflight guarantees future quota.'],
        "repairs": ['Preflight applicable size or quota constraints, reserve capacity when supported, and distinguish predictable limits from capacity that can change concurrently.'],
        "exceptions": ['If the destination cannot expose trustworthy remaining capacity before commit, the UI may transfer optimistically but should not claim the limit was known in advance.'],
        "verification": ['Test known over-limit files, near-limit concurrent transfers, and changing quota and verify predictable failures are surfaced before unnecessary large transfer.'],
        "owner_hints": ['designing-file-transfer-and-storage'], "verifier_hints": ['critiquing-performance-and-resilience'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["FILE_LIFECYCLE_RULES_V13"]
