"""V13 financial and administrative authority rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


FINANCE_ADMIN_RULES_V13 = [
    {
        "rule_id": 'ui.finance.currency-mismatch-before-commit', "domain": 'finance', "class": 'mechanical', "severity": 'critical', "enforcement": 'block',
        "title": 'A financial commit must surface currency mismatch before authorization',
        "statement": 'When source, destination, account, invoice, order, or entered amount currencies differ and conversion is not identity-preserving, the confirmation must expose the operative currencies and conversion boundary before the user authorizes the transaction.',
        "intent": 'Prevent users from approving a numerically familiar amount that represents a different currency value or conversion than they intended.',
        "applies_when": ['A financial operation combines amounts, accounts, or instruments that can use different currencies or requires conversion before settlement.'], "does_not_apply_when": [],
        "failure_modes": ['The UI displays a single number or familiar symbol without revealing that source and destination currencies differ until after authorization or settlement.'],
        "user_impacts": ['Users can transfer, pay, trade, or approve materially different value because currency identity and conversion were hidden at the decision boundary.'],
        "observables": ['Configure mismatched currencies and compare entry, review, and commit surfaces with the authoritative transaction currency fields.'],
        "falsifiers": ['Before authorization, users can identify source amount and currency, destination or settlement currency, and any rate or fee basis that materially changes the committed value.'],
        "repairs": ['Carry explicit currency type with every amount, detect mismatch before commit, and render conversion or rate semantics from the same quote or transaction authority used for execution.'],
        "exceptions": ['Products operating in a single immutable currency need not repeat currency identity on every control when no mismatch can occur.'],
        "verification": ['Test same-currency, cross-currency, expired quote, and account-switch scenarios and verify mismatch is exposed before the authorization boundary.'],
        "owner_hints": ['designing-decimal-and-financial-type-alignment'], "verifier_hints": ['critiquing-human-factors-and-safety'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.finance.pending-transaction-not-settled', "domain": 'finance', "class": 'mechanical', "severity": 'critical', "enforcement": 'block',
        "title": 'Pending financial transactions must not be represented as finally settled',
        "statement": 'Authorizations, submitted transfers, pending card operations, provisional trades, or other non-terminal financial states must remain visibly distinct from completed settlement when reversal, rejection, confirmation, or final posting is still possible.',
        "intent": 'Keep financial state language aligned with the ledger or provider lifecycle so users do not treat provisional movement as final money state.',
        "applies_when": ['A financial operation has intermediate accepted, authorized, submitted, pending, processing, or provisional states before terminal settlement or failure.'], "does_not_apply_when": [],
        "failure_modes": ['The UI labels a non-terminal transaction completed, paid, settled, or final solely because submission or provider acceptance succeeded.'],
        "user_impacts": ['Users can spend against unavailable funds, issue duplicate payments, or make accounting decisions based on an operation that can still fail or reverse.'],
        "observables": ['Drive transactions through each provider or ledger state and compare user-visible status and balance semantics with the authoritative lifecycle.'],
        "falsifiers": ['Only terminal settled state uses final language; intermediate states communicate pending authority and balance treatment according to the product ledger model.'],
        "repairs": ['Map provider or ledger states explicitly, avoid collapsing accepted into settled, and separate available, pending, and posted effects in balances and histories.'],
        "exceptions": ['Instant-settlement rails may move directly from initiation to terminal state when the authoritative ledger truly has no intermediate user-relevant state.'],
        "verification": ['Simulate submitted, pending, failed, reversed, and settled transactions and verify status labels and balance treatment follow ledger truth.'],
        "owner_hints": ['designing-financial-transaction-ui'], "verifier_hints": ['critiquing-human-factors-and-safety'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.finance.limit-breach-explains-block', "domain": 'finance', "class": 'contextual', "severity": 'major', "enforcement": 'warn',
        "title": 'A financial risk or limit block should expose the actionable boundary without inventing approval certainty',
        "statement": 'When a transaction is blocked by a known user, account, policy, risk, exposure, or regulatory limit, the interface should identify the blocking boundary and available next action to the extent policy permits rather than present an unexplained generic failure.',
        "intent": 'Help users distinguish invalid input from an intentional risk-control boundary while avoiding disclosure of sensitive risk models or guarantees of approval.',
        "applies_when": ['A financial operation can be blocked by configured limits, exposure thresholds, account restrictions, approval requirements, or other policy controls known to the product.'], "does_not_apply_when": [],
        "failure_modes": ['The UI returns a generic error indistinguishable from network failure or claims that changing one value guarantees approval when the policy does not support that certainty.'],
        "user_impacts": ['Users repeatedly retry unsafe operations, cannot route required approval, or misunderstand a policy decision as a technical outage.'],
        "observables": ['Trigger representative known limit blocks and compare rendered reason or actionability with the authoritative policy outcome and allowed disclosure.'],
        "falsifiers": ['The surface communicates a truthful bounded reason or category and valid recovery such as reducing scope, seeking approval, or contacting the appropriate authority without leaking forbidden model details.'],
        "repairs": ['Translate policy outcomes into approved user-facing categories, expose applicable remaining or required boundaries where allowed, and keep uncertain risk decisions explicitly non-guaranteed.'],
        "exceptions": ['Fraud or abuse controls may intentionally use generic messaging to avoid gaming; in that case recovery should remain safe without exposing the hidden rule.'],
        "verification": ['Exercise hard limits, approval-required states, dynamic risk blocks, and technical failures and verify users can distinguish only the categories policy permits.'],
        "owner_hints": ['designing-financial-risk-limit-controls'], "verifier_hints": ['critiquing-human-factors-and-safety'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.admin.role-change-effective-scope-visible', "domain": 'admin', "class": 'mechanical', "severity": 'critical', "enforcement": 'block',
        "title": 'Administrative role changes must expose the effective permission scope before commit',
        "statement": 'When assigning or changing a role, the confirmation must communicate the effective scope of inherited, nested, workspace, organization, or resource permissions that materially exceeds the visible role name.',
        "intent": 'Prevent administrators from granting broader authority than intended because a compact role label hides inherited or downstream access.',
        "applies_when": ['An administrative UI assigns roles whose effective permissions depend on hierarchy, groups, resource scope, inheritance, or bundled capabilities.'], "does_not_apply_when": [],
        "failure_modes": ['The commit surface shows only a role name while the actual grant includes materially broader inherited resources or capabilities not recoverable before authorization.'],
        "user_impacts": ['Administrators can unintentionally grant sensitive access or destructive capability to users, service accounts, or groups.'],
        "observables": ['Configure roles with inherited and scoped permissions and compare the confirmation or effective-permissions view with the policy engine result.'],
        "falsifiers": ['Before commit, the admin can recover the material effective scope or inspect the capabilities and resources that differ from the prior state.'],
        "repairs": ['Resolve effective permissions from the policy authority, highlight added or removed high-impact capabilities, and make inherited scope inspectable rather than inferring from the role label alone.'],
        "exceptions": ['Very small systems with one-to-one role-to-permission mappings may use the role name alone when its scope is stable, documented, and unambiguous.'],
        "verification": ['Change roles across nested scopes and verify the pre-commit effective-permission representation matches post-commit policy results.'],
        "owner_hints": ['designing-organization-administration'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.admin.bulk-action-partial-failure', "domain": 'admin', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Bulk administrative actions must preserve item-level truth when only part of the batch succeeds',
        "statement": 'If a bulk invitation, role change, revoke, suspend, delete, migration, or policy operation succeeds for some targets and fails for others, the result must preserve per-target outcomes and must not present the entire batch as successful or failed.',
        "intent": 'Enable safe recovery from mixed administrative outcomes without causing duplicate retries on targets that already committed.',
        "applies_when": ['An administrative command applies independently to multiple users, groups, resources, policies, or records and partial commit is possible.'], "does_not_apply_when": [],
        "failure_modes": ['The UI reports a single global success or failure and loses which targets committed, causing retry-all to repeat effects or hide unresolved failures.'],
        "user_impacts": ['Administrators can duplicate invitations or actions, leave risky targets unchanged unknowingly, or waste time reconstructing which subset needs recovery.'],
        "observables": ['Force mixed validation, permission, and transient failures across one batch and compare aggregate feedback with authoritative per-target outcomes.'],
        "falsifiers": ['Every target retains terminal or pending outcome, aggregate status reflects partial completion, and retry operates only on unresolved targets unless explicitly selected otherwise.'],
        "repairs": ['Track batch child operations by stable identity, derive aggregate state from them, and preserve targeted retry or export of failures rather than replacing the batch with one boolean.'],
        "exceptions": ['Atomic all-or-nothing batch operations may report a single failure when the backend guarantees no target committed.'],
        "verification": ['Run mixed-outcome and atomic-rejection batches and verify item states, aggregate summary, and retry scope match the actual transaction model.'],
        "owner_hints": ['designing-bulk-administration'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.admin.audit-entry-after-authoritative-commit', "domain": 'admin', "class": 'mechanical', "severity": 'major', "enforcement": 'block',
        "title": 'Administrative audit success entries must correspond to authoritative committed actions',
        "statement": 'An audit trail must not record an administrative action as successfully completed merely because the UI submitted it; success audit state should correspond to the authoritative commit, with rejected or pending attempts represented distinctly when retained.',
        "intent": 'Keep audit evidence aligned with real authority changes so investigations do not rely on events that never actually committed.',
        "applies_when": ['The product exposes audit or history for role, permission, configuration, security, policy, or other administrative actions that can fail or remain pending after submission.'], "does_not_apply_when": [],
        "failure_modes": ['The audit log records a successful change before backend authorization or commit, or fails to distinguish a rejected attempt from a completed mutation.'],
        "user_impacts": ['Operators can reconstruct the wrong security history, believe a protection was enabled when it failed, or attribute actions that never became authoritative.'],
        "observables": ['Force administrative operations to be rejected, delayed, and committed and compare audit entries with the authoritative policy or configuration state.'],
        "falsifiers": ['Successful audit entries correspond to committed authoritative changes; attempts, pending operations, and failures use distinct event semantics where the product records them.'],
        "repairs": ['Emit or finalize success audit records at the authority commit boundary and correlate attempts with stable operation IDs so later failures cannot masquerade as completed changes.'],
        "exceptions": ['Some compliance systems intentionally log every attempt; those attempt records are valid when their event type clearly differs from a successful state change.'],
        "verification": ['Execute successful, denied, conflicted, and delayed admin actions and verify audit event type, timestamp basis, actor, and target match the authoritative outcome.'],
        "owner_hints": ['designing-organization-administration'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["FINANCE_ADMIN_RULES_V13"]
