"""Independently authored V13 rules for forms, authentication, and recovery."""
from __future__ import annotations


def _caps(**overrides: str) -> dict[str, str]:
    values = {
        "static": "PARTIAL", "dom": "PARTIAL", "computed-style": "UNSUPPORTED",
        "browser-runtime": "PARTIAL", "interaction": "REQUIRED", "accessibility-tree": "PARTIAL",
        "visual-render": "PARTIAL", "semantic-product": "REQUIRED", "cross-generation": "UNSUPPORTED",
        "human-review": "PARTIAL",
    }
    values.update(overrides)
    return values


FORMS_AUTH_RULES_V13 = [
    {
        "rule_id": "ui.forms.async-validation-does-not-race", "domain": "forms", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Asynchronous field validation must not let older responses overwrite newer input",
        "statement": "A field whose validity depends on asynchronous checks must bind each result to the value or request version that produced it so a delayed response for older input cannot replace the state of newer input.",
        "intent": "Keep remote validation aligned with the value the user is actually editing rather than allowing network timing to create contradictory or misleading form state.",
        "applies_when": ["Username availability, coupon validity, address verification, account lookup, entitlement, inventory, or another field condition is checked asynchronously while the user can continue editing."],
        "does_not_apply_when": ["The field is disabled while a single immutable request is pending and users cannot change the checked value until that request resolves."],
        "failure_modes": ["A late validation response for an earlier value marks the current value valid or invalid even though the current value was never evaluated by that response."],
        "user_impacts": ["Users may submit invalid data, be blocked by a false error, or make a decision based on availability or eligibility that belongs to a value they already replaced."],
        "observables": ["Rapidly changing the field while reordering validation responses produces a message or valid/invalid state that does not correspond to the currently displayed value."],
        "falsifiers": ["Each response is ignored unless its request identity still matches the current value/version, or superseded requests are canceled before their results can commit UI state."],
        "repairs": ["Version asynchronous checks by normalized field value, cancel or ignore superseded requests, and clear stale remote status when editing invalidates the checked value."],
        "exceptions": ["Server responses that intentionally apply to a stable external entity rather than the editable value may remain current when the UI makes that entity scope explicit."],
        "verification": ["Type multiple values quickly, force their remote responses to arrive out of order, and confirm only the result for the current normalized value can affect validation state."],
        "owner_hints": ["designing-field-validation-and-error-recovery"], "verifier_hints": ["critiquing-functional-completeness"], "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.password-manager-compatible", "domain": "forms", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Credential forms must remain operable with password managers and platform autofill",
        "statement": "Authentication and credential-creation fields must preserve semantic input structure, stable labeling, and ordinary value entry so password managers and platform autofill can populate credentials without fighting custom presentation logic.",
        "intent": "Avoid degrading secure credential practices by making a visually customized authentication form incompatible with established credential-entry tooling.",
        "applies_when": ["A user enters, creates, confirms, or changes a username, email identifier, password, passphrase, one-time credential, or other sign-in secret through standard form controls."],
        "does_not_apply_when": ["The platform provides a native authentication ceremony whose credential entry is entirely outside the product-authored interface."],
        "failure_modes": ["Custom field behavior, misleading semantics, blocked paste, unstable names, or split secret entry prevents recognized password managers or platform autofill from correctly identifying and populating credentials."],
        "user_impacts": ["Users are pushed toward manual entry, weaker memorable passwords, copy errors, or abandoning credential managers even though the underlying authentication flow does not require that friction."],
        "observables": ["Representative browser or platform credential managers fail to recognize the credential fields, populate the wrong controls, or have their inserted value immediately overwritten or rejected by authored logic."],
        "falsifiers": ["Supported credential managers and platform autofill correctly identify, populate, submit, and update the intended fields without disabling normal paste or causing value loss."],
        "repairs": ["Use semantic form controls and appropriate autocomplete intent, preserve normal paste/value events, and remove custom masking or segmentation that conflicts with credential tooling unless essential."],
        "exceptions": ["A security-sensitive input may impose narrowly justified restrictions when an explicit threat model requires them, but cosmetic preference or anti-paste convention is not sufficient."],
        "verification": ["Exercise sign-in and credential creation with at least one supported password manager or platform autofill path and confirm values populate the intended semantic controls through submission."],
        "owner_hints": ["designing-authentication-and-passkeys"], "verifier_hints": ["critiquing-security-and-privacy"], "capabilities": _caps(**{"interaction": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.otp-paste-completes-sequence", "domain": "forms", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Segmented one-time-code entry must accept a complete pasted or autofilled code",
        "statement": "When a one-time code is visually split across multiple character boxes, users must still be able to paste or autofill the complete code as one logical value without manually distributing characters field by field.",
        "intent": "Preserve the semantics of a single credential even when presentation uses segmented boxes for readability or platform convention.",
        "applies_when": ["Verification, login, recovery, or transaction authorization asks for a short code represented as multiple visual character positions or inputs."],
        "does_not_apply_when": ["Each position is genuinely a separate answer with independent meaning rather than one serialized authentication code."],
        "failure_modes": ["Pasting or autofilling the complete code populates only one box, drops characters, reverses order, traps focus, or requires users to manually type every segment."],
        "user_impacts": ["Users copying codes from messages, password managers, or accessibility tooling encounter needless failure and may time out or abandon an otherwise valid authentication attempt."],
        "observables": ["A full valid code pasted into the active segmented control does not deterministically populate the complete logical code and advance to the expected next state."],
        "falsifiers": ["Complete paste and supported one-time-code autofill populate the logical value in order, while editing any segment still updates the same underlying code predictably."],
        "repairs": ["Model the code as one logical value, distribute pasted/autofilled characters across presentation segments, and keep focus movement as an enhancement rather than an input requirement."],
        "exceptions": ["Codes containing separators or variable-length groups may preserve those group boundaries when the complete clipboard value is still accepted and normalized correctly."],
        "verification": ["Paste a full valid and invalid code into different segment positions, exercise supported autofill, and confirm ordering, focus, correction, and submission remain predictable."],
        "owner_hints": ["designing-multi-step-forms"], "verifier_hints": ["critiquing-input-modality"], "capabilities": _caps(**{"interaction": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.session-expiry-preserves-draft", "domain": "forms", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Session expiry during editing must not silently discard recoverable draft work",
        "statement": "When authentication expires while a user is composing a recoverable form or document, reauthentication must preserve or restore non-sensitive draft state unless a specific security boundary requires that state to be discarded.",
        "intent": "Separate loss of authentication authority from needless loss of user-authored work that the product could safely retain across reauthentication.",
        "applies_when": ["A user can spend meaningful time entering structured data or prose and the authenticated session may expire before the work is submitted or saved."],
        "does_not_apply_when": ["The draft itself contains secrets or regulated material that policy explicitly forbids retaining beyond the expired session boundary."],
        "failure_modes": ["Submitting or navigating after expiry redirects to sign-in and returns to an empty/default form even though valid non-sensitive draft state existed immediately before reauthentication."],
        "user_impacts": ["Users must recreate substantial work because the product conflates expired authorization with erasing input that was still locally recoverable."],
        "observables": ["Populate multiple fields, force session expiry, reauthenticate, and observe that unrelated recoverable input is missing without a disclosed policy reason or recovery path."],
        "falsifiers": ["Draft content is safely retained or restorable through reauthentication, while specifically sensitive values that must be cleared are clearly identified and requested again."],
        "repairs": ["Persist a bounded draft outside the expiring request transaction, restore it after authentication succeeds, and explicitly exclude values whose retention violates security policy."],
        "exceptions": ["Highly sensitive one-time secrets, payment authentication data, or policy-forbidden fields may be cleared when the interface explains what must be re-entered."],
        "verification": ["Create a representative draft, expire the session before save, complete reauthentication, and compare the restored form with the pre-expiry state including intentional sensitive-field exclusions."],
        "owner_hints": ["designing-account-recovery-flows"], "verifier_hints": ["critiquing-user-experience"], "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.server-normalization-visible", "domain": "forms", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "Material server-side normalization must be visible before it changes user meaning",
        "statement": "If the server canonicalizes, rounds, reformats, truncates, maps, or otherwise transforms submitted input in a way that can alter meaning, the interface should show the resulting canonical value before or immediately after commitment.",
        "intent": "Prevent invisible normalization from making users believe the system stored exactly what they entered when the authoritative representation is materially different.",
        "applies_when": ["Submitted identifiers, addresses, quantities, dates, names, financial values, units, or structured content are transformed by authoritative backend rules beyond superficial whitespace or presentation formatting."],
        "does_not_apply_when": ["Normalization is semantically lossless and users cannot make a materially different decision based on the normalized representation."],
        "failure_modes": ["The authoritative stored value differs materially from the entered value but the UI continues to display the original input or claims successful save without revealing the transformation."],
        "user_impacts": ["Users may act on a value the system did not actually store, miss truncation or rounding, or discover a changed identifier only after later workflow failure."],
        "observables": ["Comparing submitted data with the persisted authoritative record reveals a semantic transformation that is not surfaced in the post-submit view or confirmation boundary."],
        "falsifiers": ["The authoritative representation matches user meaning, or the UI presents the canonicalized value and any material difference at a point where the user can correct or accept it."],
        "repairs": ["Return canonicalized values in the commit response, update the form from authoritative state, and call attention to transformations that change scope, precision, identity, or interpretation."],
        "exceptions": ["Pure formatting normalization such as insignificant whitespace cleanup can remain implicit when it cannot alter identity, calculation, search, or downstream behavior."],
        "verification": ["Submit inputs that trigger each material normalization path and compare entered, persisted, and rendered post-commit values for semantic transparency."],
        "owner_hints": ["designing-forms"], "verifier_hints": ["critiquing-functional-completeness"], "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.conditional-fields-preserve-dependent-data", "domain": "forms", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Temporarily hidden conditional fields must not erase still-recoverable dependent data",
        "statement": "When a controlling answer temporarily hides dependent form fields, the product must distinguish hiding inactive data from intentionally clearing it so reversible exploration does not silently destroy valid user work.",
        "intent": "Let users revise branching answers without losing substantial dependent input merely because the UI conditionally removed those controls from view.",
        "applies_when": ["A form reveals nested sections based on plan, country, role, checkbox, category, workflow branch, or another answer and users can change the controlling value before final submission."],
        "does_not_apply_when": ["The controlling change makes the old dependent values invalid or unsafe to retain and the interface clearly communicates that they will be cleared."],
        "failure_modes": ["Switching a controlling answer away and back recreates empty dependent fields even though the previous dependent values remained valid and no explicit clear action occurred."],
        "user_impacts": ["Users lose work while exploring options and may avoid correcting earlier choices because conditional UI unexpectedly destroys downstream input."],
        "observables": ["Populate dependent fields, temporarily select another branch, restore the original branch, and observe that valid values disappeared without warning or irreversible semantic reason."],
        "falsifiers": ["Dependent data returns when the branch is restored, or the product explicitly confirms and explains destructive clearing before removing values that cannot safely remain."],
        "repairs": ["Keep inactive branch data in bounded draft state, validate it again when reactivated, and clear it only at an explicit semantic invalidation or user-confirmed reset boundary."],
        "exceptions": ["Changing jurisdiction, identity, or another authority-defining answer may require clearing now-invalid dependent data when retention could produce a false or unsafe submission."],
        "verification": ["Exercise each reversible branch transition with populated dependent fields and confirm values, validation state, and explicit invalidation behavior match the data semantics."],
        "owner_hints": ["designing-multi-step-forms"], "verifier_hints": ["critiquing-user-experience"], "capabilities": _caps(), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.submit-retry-does-not-double-commit", "domain": "forms", "class": "mechanical", "severity": "critical", "enforcement": "block",
        "title": "Retrying a consequential form submission must not create a second committed operation",
        "statement": "When a submit response is lost, times out, or appears uncertain, a user retry must reconcile with the original operation identity instead of blindly creating a duplicate purchase, booking, message, account, or mutation.",
        "intent": "Make recovery from ambiguous network outcomes safe at the UI-to-operation boundary rather than relying on users to guess whether the first submission committed.",
        "applies_when": ["Form submission can charge, book, send, create, publish, transfer, provision, or otherwise produce a consequential side effect that users may retry after uncertain feedback."],
        "does_not_apply_when": ["The operation is explicitly additive and repeated submissions are intentionally separate outcomes with clearly different operation identities."],
        "failure_modes": ["A second activation after timeout or lost response generates another authoritative side effect because the UI and backend do not preserve or reconcile the first submission identity."],
        "user_impacts": ["Users can be double charged, create duplicate records, send repeated messages, or reserve multiple resources while attempting to recover from an ambiguous first submission."],
        "observables": ["Simulating commit followed by a dropped response and then retrying results in more than one authoritative operation for the same intended submission."],
        "falsifiers": ["Retry reuses or reconciles an idempotency/operation identity and either returns the original committed result or safely continues the same operation without duplicating side effects."],
        "repairs": ["Assign a stable submission identity before dispatch, keep it across uncertain retry, and reconcile authoritative status before offering a fresh independent operation."],
        "exceptions": ["A deliberate user choice to perform the operation again may create a new identity only after the previous outcome is known or the interface clearly distinguishes the second operation."],
        "verification": ["Force the server to commit while the client loses the response, retry from the resulting UI state, and verify only one consequential operation exists afterward."],
        "owner_hints": ["designing-retry-and-recovery-actions"], "verifier_hints": ["critiquing-functional-completeness"], "capabilities": _caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
    {
        "rule_id": "ui.forms.identity-recovery-does-not-enumerate-secret-state", "domain": "forms", "class": "contextual", "severity": "major", "enforcement": "block",
        "title": "Account recovery feedback must not disclose protected account existence or secret state",
        "statement": "Recovery and identifier-reminder flows must avoid exposing whether a protected account, recovery channel, secret factor, or security configuration exists when that information is not already authorized for the requester.",
        "intent": "Keep helpful recovery feedback from becoming an oracle that reveals sensitive identity or account configuration to unauthenticated or insufficiently trusted users.",
        "applies_when": ["An unauthenticated or partially authenticated user submits email, phone, username, recovery code, or other identifiers to recover or discover access to an account."],
        "does_not_apply_when": ["The account existence is intentionally public or the requester has already passed an authorization step that permits disclosure of the specific recovery state."],
        "failure_modes": ["Different messages, timing, controls, or next-step options reveal that one identifier has an account, configured factor, or recovery destination while another does not."],
        "user_impacts": ["Attackers can enumerate users or sensitive recovery configuration, while legitimate users receive inconsistent disclosure that exceeds the authority established by the flow."],
        "observables": ["Submitting known-existing and nonexistent identifiers produces materially distinguishable unauthenticated output that exposes protected account or factor existence."],
        "falsifiers": ["Unauthenticated responses preserve equivalent disclosure while still offering a legitimate recovery path, and any later detailed state appears only after sufficient authorization."],
        "repairs": ["Use disclosure-bounded feedback before authorization, move sensitive recovery detail behind an appropriate proof step, and keep timing/control differences from becoming an equivalent enumeration channel."],
        "exceptions": ["Public-directory products may disclose account existence by design, but secret factors, private destinations, and protected security configuration remain separately bounded."],
        "verification": ["Compare recovery behavior for known, unknown, partially configured, and locked accounts from the same unauthenticated state and review every visible and behavioral disclosure difference."],
        "owner_hints": ["designing-account-recovery-flows"], "verifier_hints": ["critiquing-security-and-privacy"], "capabilities": _caps(**{"browser-runtime": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-form-auth-owners-v13"], "status": "active",
    },
]
