"""Authored V13 convergence rules for typography costume, motion, fashion migration, and cross-generation/product fit."""
from __future__ import annotations

from ._capabilities import convergence_caps

FOUNDATION_CONVERGENCE_BEHAVIOR_RULES_V13 = [
    {
        "rule_id": "ui.convergence.developer-typography-costume",
        "domain": "convergence",
        "class": "convergence",
        "severity": "observation",
        "enforcement": "review",
        "title": "Developer-coded typography should correspond to actual content semantics",
        "statement": "Monospace type, tiny uppercase labels, terminal-like prefixes, and code-adjacent typography become convergence signals when they are applied to ordinary marketing or product copy merely to imply technical credibility rather than to represent code, identifiers, telemetry, or a deliberate brand grammar.",
        "intent": "Separate semantic technical typography from fashionable developer costume without banning monospace or compact uppercase labels as legitimate tools.",
        "applies_when": ["A surface uses monospace, terminal conventions, tiny uppercase metadata, or code-like typographic treatments outside literal code and structured technical data."],
        "does_not_apply_when": ["The typography encodes code, commands, identifiers, telemetry, machine-readable values, editorial voice, or a documented brand system with deliberate contrast to surrounding type."],
        "failure_modes": ["Technical-looking typography is repeated across semantically ordinary copy and its removal would not change interpretation, hierarchy, data type, interaction, or brand meaning."],
        "user_impacts": ["The interface can adopt a generic AI/developer aesthetic while sacrificing readability or creating false cues that ordinary content has technical semantics."],
        "observables": ["Monospace or code-like labels appear in decorative positions where the content is neither code-like nor governed by a documented typographic role."],
        "falsifiers": ["A content taxonomy, brand grammar, or data-type rule predicts where the technical typography appears and where it must not appear."],
        "repairs": ["Assign typography from content semantics and hierarchy; reserve technical treatments for content roles that benefit from their metrics, voice, or data-type affordance."],
        "exceptions": ["Strong editorial and brand systems may deliberately use technical typography as voice when readability and hierarchy are validated across the intended audience."],
        "verification": ["Map each technical typographic treatment to a content role and confirm the treatment changes or disappears when that role is absent."],
        "owner_hints": ["designing-script-sensitive-typography", "directing-visual-ambition"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"computed-style": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.motion-reflex-stack",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Stacked generic motion effects should trace to interaction meaning",
        "statement": "A generated interface shows convergence risk when scale, translate, shadow, rotation, spring, fade, and broad transitions are layered repeatedly across controls and cards without each motion communicating state, causality, hierarchy, continuity, or spatial relationship.",
        "intent": "Make motion answer an interaction question instead of serving as generic liveliness, while preserving expressive motion in products that intentionally use it as part of brand and feedback.",
        "applies_when": ["A surface contains repeated hover, entrance, selection, navigation, or state-transition animation and the purpose of each motion can be evaluated against the interaction model."],
        "does_not_apply_when": ["The experience is explicitly motion-led, entertainment-oriented, demonstrative, or brand-expressive and the motion grammar has documented roles, reduced-motion behavior, and performance limits."],
        "failure_modes": ["Multiple decorative transforms are stacked on ordinary interactions and repeated widely even though the motion does not explain state change, target relationship, continuity, or consequence."],
        "user_impacts": ["Users experience distracting or fatiguing movement, weak state communication, and an interface whose motion vocabulary feels repetitive rather than informative."],
        "observables": ["The same compound transform or broad transition pattern recurs across unrelated components with little variation based on interaction semantics."],
        "falsifiers": ["Each recurring motion primitive has a documented semantic role and its timing, geometry, and presence change predictably with state transition or spatial relationship."],
        "repairs": ["Remove decorative motion layers that carry no interaction meaning and define a smaller motion grammar tied to feedback, continuity, hierarchy, and spatial causality."],
        "exceptions": ["Promotional, game, creative-tool, and entertainment surfaces may intentionally prioritize expressive motion when usability, preference, and performance requirements remain satisfied."],
        "verification": ["Disable each motion family in turn and identify the state, causality, hierarchy, or spatial information lost; effects that communicate nothing require explicit art-direction justification."],
        "owner_hints": ["designing-motion"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"browser-runtime": "REQUIRED", "interaction": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.blacklist-fashion-migration",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Avoid replacing a banned visual default with another fashionable default",
        "statement": "An anti-convergence intervention fails when removing a stigmatized pattern merely moves the design to another fashionable statistical mode without increasing product specificity, structural divergence, semantic color roles, or workflow-derived decisions.",
        "intent": "Prevent anti-slop policy from becoming a style generator that produces a new recognizable house aesthetic instead of better product-specific design reasoning.",
        "applies_when": ["A generation or redesign was explicitly constrained by negative style rules, anti-slop guidance, banned motifs, or a previous critique of recognizable AI defaults."],
        "does_not_apply_when": ["The replacement direction follows an existing product design system, approved brand refresh, explicit creative brief, or reference contract with documented rationale independent of the banned pattern."],
        "failure_modes": ["The rejected default disappears but multiple unrelated choices converge on a new fashionable palette, type pairing, composition, or material treatment without stronger connection to product intent."],
        "user_impacts": ["The product remains generic despite passing superficial anti-pattern checks, and teams may mistake aesthetic migration for increased originality or product fit."],
        "observables": ["Before-and-after comparison shows style substitution without material change to macrostructure, information priority, workflow decisions, or product-specific design grammar."],
        "falsifiers": ["The replacement direction can be traced to explicit product constraints, reference evidence, brand grammar, or divergent exploration and materially changes decisions beyond the banned style surface."],
        "repairs": ["Return to design intent and divergent alternatives, then select positive product-specific constraints rather than choosing the nearest fashionable opposite of the banned motif."],
        "exceptions": ["A deliberate trend-aligned art direction can be valid when it is an explicit product or campaign choice rather than an accidental fallback caused by negative prompting."],
        "verification": ["Compare pre- and post-intervention structure, hierarchy, token roles, and product-specific decisions; require evidence of changed reasoning rather than only changed fashion markers."],
        "owner_hints": ["directing-visual-ambition", "modeling-product-intent"],
        "verifier_hints": ["critiquing-research-validity"],
        "capabilities": convergence_caps(**{"cross-generation": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.premature-first-pass-completeness",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Suspiciously complete first-pass design should expose its skipped decisions",
        "statement": "A polished first pass becomes a convergence signal when many independent design decisions appear resolved before the agent has explored materially different structures, clarified product constraints, or surfaced uncertainty about content, state, and interaction trade-offs.",
        "intent": "Introduce productive friction before convergence so apparent completeness does not hide unexamined statistical defaults.",
        "applies_when": ["An agent moves from a materially underspecified product request to a production-looking interface or design direction with many decisions apparently settled in one generation cycle."],
        "does_not_apply_when": ["The task supplies a mature design system, exact reference contract, detailed information architecture, existing component library, and bounded change scope that legitimately determines most design decisions in advance."],
        "failure_modes": ["The first generated direction resolves macrostructure, visual grammar, component treatment, copy rhythm, and motion without evidence of divergent alternatives or explicit decisions tied to product constraints."],
        "user_impacts": ["Teams can accept a coherent-looking default too early, reducing exploration and embedding generic choices that become expensive to challenge after implementation."],
        "observables": ["Generation history shows one dominant direction reaching high visual completeness before materially different structural candidates or unresolved decision dimensions were recorded."],
        "falsifiers": ["The task was genuinely bounded by existing product grammar, or the agent produced and compared structurally distant alternatives before selecting the polished direction."],
        "repairs": ["Reopen unresolved design dimensions, generate structurally divergent candidates, compare trade-offs against product intent, and only then recommit to a selected direction."],
        "exceptions": ["Small maintenance changes and tightly constrained implementation tasks do not need artificial divergence when the governing design decisions already exist."],
        "verification": ["Inspect the design history for explicit alternatives, decision dimensions, and selection rationale preceding the point at which the chosen direction became visually complete."],
        "owner_hints": ["directing-visual-ambition"],
        "verifier_hints": ["critiquing-research-validity"],
        "capabilities": convergence_caps(**{"static": "UNSUPPORTED", "dom": "UNSUPPORTED", "computed-style": "UNSUPPORTED", "cross-generation": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.cross-generation-macrostructure-cloning",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Repeated macrostructure across unrelated generations requires divergence review",
        "statement": "Cross-generation similarity becomes a stronger convergence signal when unrelated products repeatedly receive near-identical section order, component graph, content slots, and spatial hierarchy even after color, typography, and copy are changed.",
        "intent": "Detect structural sameness that cosmetic audits miss while avoiding a universal threshold that would punish legitimately standardized product families.",
        "applies_when": ["Previous generated interfaces or project generations are available for comparison and the products or tasks are sufficiently different that identical macrostructure is not an explicit requirement."],
        "does_not_apply_when": ["The compared surfaces share a deliberate design system, product family template, white-label architecture, regulated workflow, or other requirement that intentionally preserves macrostructure."],
        "failure_modes": ["Component graph and spatial sequence remain highly similar across materially different tasks while the apparent diversity comes primarily from palette, type, imagery, or wording changes."],
        "user_impacts": ["Different products inherit the same interaction and information assumptions, reducing fit and making generated experiences recognizably repetitive even when surface styling varies."],
        "observables": ["Cross-generation comparison shows repeated section topology, component relationships, and hierarchy beyond what shared platform conventions or explicit system constraints explain."],
        "falsifiers": ["The shared structure is required by common product architecture or measured task similarity, or the current generation contains materially different topology at the workflow and information-architecture level."],
        "repairs": ["Generate alternative component graphs and information sequences from the current task model, then select based on product fit rather than cosmetic distance from previous output."],
        "exceptions": ["Design-system families, enterprise suites, and standardized workflows can intentionally preserve macrostructure when consistency is itself a user requirement."],
        "verification": ["Compare component graph, section sequence, hierarchy, and interaction topology against prior generations after normalizing away color, typeface, imagery, and copy."],
        "owner_hints": ["modeling-product-intent"],
        "verifier_hints": ["critiquing-research-validity"],
        "capabilities": convergence_caps(**{"cross-generation": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.product-specific-exception-absence",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "A mature product flow should reveal justified exceptions to generic component grammar",
        "statement": "An interface can signal convergence when every workflow fits perfectly into generic components and spacing rules despite product requirements that should create unusual states, edge conditions, exceptions, or domain-specific manipulations.",
        "intent": "Look for evidence that real workflow pressure shaped the interface, not for novelty as an end in itself.",
        "applies_when": ["The product has non-trivial domain workflows, edge cases, state transitions, or decision risks that would reasonably be expected to create specialized interaction or presentation needs."],
        "does_not_apply_when": ["The product domain is intentionally simple, the current scope excludes complex workflows, or a mature component system already encodes the necessary domain-specific exceptions internally."],
        "failure_modes": ["All screens remain perfectly regular and generic even though documented product behavior includes edge conditions or specialized tasks that the generic grammar does not visibly accommodate."],
        "user_impacts": ["Important domain complexity can be pushed into hidden logic or omitted entirely, leaving users with an elegant shell that breaks down when real exceptional work begins."],
        "observables": ["Requirements mention specialized states or edge cases, but the rendered/component model contains no corresponding variation in controls, hierarchy, recovery, disclosure, or information structure."],
        "falsifiers": ["The supposedly unusual requirements are fully satisfied by existing components with verified states, or domain-specific exceptions are explicitly represented and tested even if they remain visually subtle."],
        "repairs": ["Trace real edge workflows into component and state requirements, then allow justified local exceptions where generic grammar would hide consequence or task structure."],
        "exceptions": ["Consistency may deliberately dominate in safety-critical or highly standardized systems when exceptions increase risk and the platform provides proven patterns for the specialized workflow."],
        "verification": ["Select representative edge workflows and map each unusual requirement to a visible interaction, state, recovery, or information-architecture decision in the implementation."],
        "owner_hints": ["modeling-product-intent"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"interaction": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
]

__all__ = ["FOUNDATION_CONVERGENCE_BEHAVIOR_RULES_V13"]
