"""Authored V13 convergence rules for macrostructure, surfaces, hierarchy, and decorative repetition."""
from __future__ import annotations

from ._capabilities import convergence_caps

FOUNDATION_CONVERGENCE_STRUCTURE_RULES_V13 = [
    {
        "rule_id": "ui.convergence.product-substitution-plausibility",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "A product shell that survives competitor substitution needs identity review",
        "statement": "When a product name, logo, and nouns can be swapped for an unrelated competitor while the interface remains equally plausible, the design lacks evidence that its structure was derived from this product's specific jobs, constraints, and information priorities.",
        "intent": "Use substitutability as a falsifiable product-fit probe rather than as an authorship detector or a demand for ornamental uniqueness.",
        "applies_when": ["A material product surface has been generated or redesigned and enough real workflow, content, and brand context exists to judge whether the interface encodes product-specific decisions."],
        "does_not_apply_when": ["The surface is intentionally generic infrastructure such as an authentication shell, operating-system utility, standards-driven settings page, or white-label product whose interchangeability is an explicit requirement."],
        "failure_modes": ["The composition, hierarchy, interaction emphasis, and content slots remain credible after replacing product identity with an unrelated competitor, indicating that product-specific constraints had little effect on the design."],
        "user_impacts": ["Users receive a polished but weakly differentiated interface whose hierarchy may fail to expose the workflows, risks, terminology, or decision points that make the actual product useful."],
        "observables": ["A substitution critique can replace product identity and domain nouns without forcing material changes to information architecture, component roles, interaction flow, or visual emphasis."],
        "falsifiers": ["Documented product constraints require concrete structural or interaction decisions that would become incorrect, nonsensical, or unsafe under a competitor substitution."],
        "repairs": ["Re-derive hierarchy and interaction emphasis from real user jobs, domain constraints, product data, risk, and content rather than adding decorative difference after the fact."],
        "exceptions": ["White-label systems and deliberately standardized commodity flows can remain substitutable when product differentiation is not part of the surface's purpose."],
        "verification": ["Run a competitor-substitution critique against the rendered flow and identify the product-specific structural decisions that fail or become incoherent after substitution."],
        "owner_hints": ["modeling-product-intent"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.default-saas-macrostructure-density",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Dense default SaaS section sequencing requires content-derived justification",
        "statement": "A familiar marketing sequence becomes a convergence signal when hero, social proof, equal features, statistics, pricing, FAQ, final CTA, and footer appear primarily because they form a statistical default rather than because the available evidence requires those sections in that order.",
        "intent": "Challenge macrostructure chosen by reflex while preserving conventional conversion structures when research, content, and business goals genuinely justify them.",
        "applies_when": ["A marketing, launch, product-introduction, or commercial landing surface contains several conventional sections whose ordering and inclusion can be evaluated against real content and conversion intent."],
        "does_not_apply_when": ["The information architecture is constrained by an approved campaign template, regulated disclosure sequence, experiment design, or evidence-backed conversion system that explicitly requires the conventional order."],
        "failure_modes": ["The page reproduces a high-frequency SaaS macrostructure with little evidence that section presence, order, or relative emphasis was derived from actual user questions and product proof."],
        "user_impacts": ["Users must scan predictable but weakly prioritized sections, while the product's strongest evidence or most important decision information can be diluted by generic marketing completeness."],
        "observables": ["Multiple conventional sections appear in default order and can be removed, reordered, or replaced without contradicting a documented content dependency or user decision path."],
        "falsifiers": ["Research, campaign requirements, conversion evidence, or content dependencies explain why each questioned section exists, why it appears at that point, and why its relative prominence is appropriate."],
        "repairs": ["Recompose the page around the actual sequence of user questions, proof, objections, and decisions; remove conventional sections that lack a defensible job."],
        "exceptions": ["A known high-performing template may be retained when its constraints and intended audience are explicit and the product-specific content hierarchy remains materially differentiated."],
        "verification": ["For each major section, trace inclusion, order, and prominence to a real user question, product claim, proof artifact, business requirement, or measured experiment hypothesis."],
        "owner_hints": ["architecting-information", "modeling-product-intent"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"cross-generation": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.cardification-without-semantic-boundaries",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Repeated surface containers should correspond to real semantic boundaries",
        "statement": "Cards, panels, framed regions, and nested surfaces become a convergence signal when boundaries are repeated uniformly despite differences in grouping, interaction ownership, hierarchy, or content relationship.",
        "intent": "Distinguish useful containment from automatic cardification so visual boundaries communicate structure instead of merely making a generated layout look finished.",
        "applies_when": ["A rendered interface contains repeated bordered, elevated, rounded, tinted, or otherwise bounded surfaces that can be compared with the semantic grouping of their contents."],
        "does_not_apply_when": ["The platform or design system intentionally defines repeated containers as the primary interaction primitive and each container represents a meaningful independent object or action scope."],
        "failure_modes": ["Visually equivalent containers are applied to unrelated content types and nested repeatedly even where no independent semantic, interaction, or ownership boundary exists."],
        "user_impacts": ["Users receive noisy grouping cues, weaker hierarchy, and unnecessary visual fragmentation that can make related content feel disconnected and unrelated content feel equally important."],
        "observables": ["Container geometry and decoration repeat at high density while the enclosed regions do not share a consistent semantic role, independent action scope, or content boundary."],
        "falsifiers": ["Each repeated surface maps to a stable semantic entity, interaction scope, or grouping contract, and removing its boundary would materially reduce comprehension or operability."],
        "repairs": ["Remove decorative containment where spacing, typography, alignment, or section rhythm communicates hierarchy more accurately; retain boundaries only where they encode meaningful grouping or interaction."],
        "exceptions": ["Dense dashboards, object browsers, and modular workspaces can legitimately use many surfaces when each surface owns a distinct tool, dataset, state, or manipulation scope."],
        "verification": ["Sample representative containers and state the semantic or interaction boundary each one communicates; treat unexplained repeated boundaries as candidates for simplification."],
        "owner_hints": ["architecting-information", "governing-design-systems"],
        "verifier_hints": ["critiquing-cognitive-load"],
        "capabilities": convergence_caps(**{"computed-style": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.visual-hierarchy-equalization",
        "domain": "convergence",
        "class": "convergence",
        "severity": "moderate",
        "enforcement": "review",
        "title": "Uniform visual weight across unlike decisions signals hierarchy collapse",
        "statement": "A surface converges toward generic generated composition when many panels, metrics, controls, and calls to action receive comparable size, contrast, spacing, and decoration despite materially different importance to the user's current task.",
        "intent": "Detect statistical evenness that hides task priority while allowing deliberately egalitarian browsing surfaces where no item should dominate.",
        "applies_when": ["A screen presents multiple competing regions or actions and the product task model provides a meaningful distinction between primary, secondary, supporting, and exceptional information."],
        "does_not_apply_when": ["The product intentionally supports undirected exploration or peer comparison where equal prominence is a core information-design requirement."],
        "failure_modes": ["Repeated modules receive nearly uniform visual prominence even though the workflow contains a clear primary task, higher-risk decision, or dominant information need."],
        "user_impacts": ["Users spend more effort discovering what matters now, can miss the primary decision path, and may interpret supporting information as equally actionable or urgent."],
        "observables": ["Size, contrast, spacing, border treatment, and placement show low differentiation across regions that have substantially different task priority or consequence."],
        "falsifiers": ["The product's task model demonstrates that the compared regions are intentionally peers, or rendered emphasis changes in accordance with user state, risk, and current task priority."],
        "repairs": ["Establish a task-derived emphasis model and deliberately reduce or increase prominence so visual weight tracks decision priority, consequence, and current workflow state."],
        "exceptions": ["Catalogs, comparison grids, monitoring walls, and exploratory canvases may intentionally equalize peers while still differentiating alerts, selection, or exceptional states."],
        "verification": ["Rank visible regions by intended task importance, then compare that ranking with rendered prominence and explain any deliberate mismatch."],
        "owner_hints": ["directing-visual-energy"],
        "verifier_hints": ["critiquing-cognitive-load"],
        "capabilities": convergence_caps(),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.decorative-gradient-text-default",
        "domain": "convergence",
        "class": "convergence",
        "severity": "observation",
        "enforcement": "review",
        "title": "Gradient-clipped text without a semantic role is a weak convergence signal",
        "statement": "Gradient text is not a defect by itself, but repeated or prominent use becomes a convergence signal when the color transition communicates no brand, state, category, emphasis hierarchy, or content meaning beyond generic technological polish.",
        "intent": "Question decorative gradient typography without replacing one fashionable default with another or banning a legitimate brand treatment.",
        "applies_when": ["Prominent headings, metric values, labels, or calls to action use gradient-clipped text in a surface where the design rationale and semantic color roles can be inspected."],
        "does_not_apply_when": ["The gradient is a documented brand asset, represents a meaningful data/state continuum, or participates in a broader art direction with explicit visual-system rules."],
        "failure_modes": ["Gradient typography is introduced as an isolated sophistication cue and remains semantically interchangeable with a flat accent treatment."],
        "user_impacts": ["The interface can feel statistically generic or visually noisy, and meaningful color semantics may become harder to distinguish from decoration."],
        "observables": ["Gradient-clipped text appears in high-salience positions while no product state, brand rule, data encoding, or content hierarchy depends on the gradient transition."],
        "falsifiers": ["A documented brand, semantic encoding, or composition rule explains why the gradient exists, what it communicates, and where the same treatment must or must not recur."],
        "repairs": ["Remove the gradient or integrate it into an explicit visual grammar with a defined role instead of using it as an isolated generic emphasis effect."],
        "exceptions": ["Expressive campaign art, entertainment experiences, and brand-led editorial compositions may use decorative gradient typography as intentional art direction."],
        "verification": ["Identify the gradient's product, semantic, or art-direction role and confirm its recurrence follows that role rather than appearing wherever extra emphasis was desired."],
        "owner_hints": ["directing-visual-ambition"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"static": "SUPPORTED", "computed-style": "REQUIRED", "cross-generation": "UNSUPPORTED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
    {
        "rule_id": "ui.convergence.decorative-icon-tile-repetition",
        "domain": "convergence",
        "class": "convergence",
        "severity": "observation",
        "enforcement": "review",
        "title": "Uniform icon tiles across unrelated features need semantic justification",
        "statement": "A repeated icon-inside-rounded-tile treatment becomes a convergence signal when every feature receives the same decorative wrapper regardless of action type, information role, frequency, risk, or relationship to the surrounding content.",
        "intent": "Prevent icon wrappers from becoming automatic filler while preserving coherent icon systems whose containers communicate a real interaction or category contract.",
        "applies_when": ["Several features, benefits, settings, or dashboard modules use visually uniform icon containers that can be compared against their semantic and interaction roles."],
        "does_not_apply_when": ["The icon tile is itself a stable component primitive with a documented semantic function such as application launcher, category selector, or independently operable tool."],
        "failure_modes": ["Identical icon containers are applied to unrelated concepts solely to create repeated visual rhythm and can be removed without changing operation, grouping, category, or hierarchy."],
        "user_impacts": ["Users receive repetitive decoration that consumes attention without improving recognition, while genuinely different feature roles can appear more similar than they are."],
        "observables": ["Multiple unrelated items share nearly identical icon tile geometry, radius, background, size, and placement despite different semantic or interaction roles."],
        "falsifiers": ["The tile consistently communicates a defined category, affordance, ownership boundary, or interaction mode and changes meaningfully when those semantics change."],
        "repairs": ["Use icons directly, vary treatment according to semantic role, or remove redundant wrappers so the visual system reflects information and interaction structure."],
        "exceptions": ["Application grids, launcher surfaces, device home screens, and taxonomy-driven category systems can legitimately standardize icon containers as a core navigation primitive."],
        "verification": ["Compare a sample of icon tiles and document the semantic reason for the container itself, not merely the reason for the icon glyph."],
        "owner_hints": ["governing-design-systems"],
        "verifier_hints": ["critiquing-user-experience"],
        "capabilities": convergence_caps(**{"computed-style": "REQUIRED"}),
        "provenance_ids": ["nui-anti-convergence-corpus-2026-09-01"],
        "status": "active",
    },
]

__all__ = ["FOUNDATION_CONVERGENCE_STRUCTURE_RULES_V13"]
