"""V13 history and destructive operation rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


HISTORY_DESTRUCTIVE_RULES_V13 = [
    {
        "rule_id": 'ui.history.undo-restores-dependent-state', "domain": 'history', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Undo must restore dependent state that was part of the original logical operation',
        "statement": 'When one user command changes multiple coupled values, references, selections, or structural relationships, undo must reverse the whole logical transaction rather than only its most visible field and leave dependent state inconsistent.',
        "intent": 'Make undo correspond to user intent and transaction boundaries instead of exposing internal implementation fragments.',
        "applies_when": ['A user command performs a compound edit such as move, delete, group, replace, format, rename, reconnect, or another operation with dependent state.'], "does_not_apply_when": [],
        "failure_modes": ['Undo reverses only one mutation while leaving derived references, selection, hierarchy, links, metadata, or related values in the post-command state.'],
        "user_impacts": ['Users can enter corrupted or confusing states after trusting undo to reverse the action they just performed.'],
        "observables": ['Perform representative compound operations, capture all affected state, undo once, and compare the logical model with the pre-command state.'],
        "falsifiers": ['One undo restores the product-defined transaction to a coherent prior state including dependent relationships that were part of the same user command.'],
        "repairs": ['Record history at semantic transaction boundaries with enough inverse data or snapshots to restore coupled state atomically.'],
        "exceptions": ['Some derived caches may be recomputed rather than literally restored when recomputation yields the same logical pre-command state.'],
        "verification": ['Exercise compound edits and compare serialized or inspectable logical state before command and after one undo for equivalence within documented derived fields.'],
        "owner_hints": ['designing-undo-redo-history'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.history.redo-invalidated-after-divergent-edit', "domain": 'history', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Redo history must be invalidated or branched after a divergent new edit',
        "statement": 'After undo, a new edit creates a different history branch; a subsequent redo must not blindly replay the abandoned future on top of the new state unless the product explicitly supports branching history and can merge safely.',
        "intent": 'Prevent redo from applying operations against a base state they were not created for.',
        "applies_when": ['The product supports undo and redo and allows users to make a new mutation after moving backward in history.'], "does_not_apply_when": [],
        "failure_modes": ['The old redo stack remains available after a divergent edit and replays against the changed base, producing an unintended compound or corrupt state.'],
        "user_impacts": ['Users can resurrect abandoned edits or corrupt documents because redo semantics ignore that history diverged.'],
        "observables": ['Perform A then B, undo B, perform C, and inspect whether redo of B remains enabled or is represented as an explicit alternate branch.'],
        "falsifiers": ['A divergent edit clears linear redo or creates an explicit branch with safe semantics; the abandoned future is never replayed as though the base were unchanged.'],
        "repairs": ['Track history graph or branch identity and invalidate linear redo when a new command commits from a non-tip state unless branch-aware history is implemented.'],
        "exceptions": ['Professional systems may preserve alternate history branches when those branches are explicitly represented and switching or restoring them cannot masquerade as ordinary redo.'],
        "verification": ['Exercise linear and branch-aware edit sequences and verify redo availability and resulting state match the declared history model.'],
        "owner_hints": ['designing-undo-redo-history'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.history.version-restore-is-new-version', "domain": 'history', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Restoring an old version must preserve later history rather than rewriting it out of existence',
        "statement": 'A version restore should normally create a new current version derived from the selected historical state so versions created after that point remain inspectable and recoverable.',
        "intent": 'Make restoration reversible and audit-friendly instead of treating history as a destructive rewind.',
        "applies_when": ['The product exposes persistent version history for documents, configurations, files, workflows, or other durable content and supports restoring a prior version.'], "does_not_apply_when": [],
        "failure_modes": ['Restoring version N deletes or makes versions N plus one onward inaccessible without explicit destructive-history semantics and confirmation.'],
        "user_impacts": ['Users can lose intervening work while believing restore is a reversible history action, and audit trails can become incomplete.'],
        "observables": ['Create several versions, restore an early one, and inspect whether intervening versions remain available and whether a new version records the restore.'],
        "falsifiers": ['The restored content becomes current through a new version or equivalent reversible record while later historical versions remain inspectable.'],
        "repairs": ['Implement restore as a new commit or version referencing the selected historical source and preserve the prior head in the history graph.'],
        "exceptions": ['A deliberately destructive reset feature may prune later history when explicitly named, separately authorized, and appropriate to the product domain.'],
        "verification": ['Create, restore, edit after restore, and navigate version history to confirm both intervening and restored lineage remain recoverable.'],
        "owner_hints": ['designing-version-history'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.destructive.bulk-scope-visible-before-commit', "domain": 'destructive', "class": 'mechanical', "severity": 'critical', "enforcement": 'block',
        "title": 'A bulk destructive action must expose the effective target scope before commit',
        "statement": 'Before delete, revoke, archive, disable, remove, or another destructive bulk operation commits, the confirmation state must make the actual selected, filtered, all-target, or inherited scope recoverable rather than relying on a vague count or stale selection impression.',
        "intent": 'Prevent destructive actions from affecting a broader set than users intend when selection semantics include hidden pages, filters, all-results modes, or inherited scopes.',
        "applies_when": ['A destructive command can apply to multiple items selected across pages, filters, groups, accounts, or an all-results mode.'], "does_not_apply_when": [],
        "failure_modes": ['The confirmation does not distinguish visible selection from all matching items, hidden selected items, excluded filters, or inherited descendants that the operation will affect.'],
        "user_impacts": ['Users can destroy or revoke far more content or access than they intended because the visible table does not represent the actual operation scope.'],
        "observables": ['Construct selections across pagination and filter boundaries and inspect the confirmation payload against the authoritative target set used at commit.'],
        "falsifiers": ['The confirmation communicates the effective scope, target count where meaningful, and exceptional hidden or inherited coverage so users can verify what will be affected.'],
        "repairs": ['Derive confirmation from the authoritative selection query or target IDs, surface all-results or inherited semantics explicitly, and recompute scope if filters or data change before commit.'],
        "exceptions": ['Tiny obvious local selections may not need verbose enumeration when every target is simultaneously visible and no hidden scope can exist.'],
        "verification": ['Test visible-only, cross-page, all-results, filtered, and descendant-inclusive selections and compare confirmation semantics with the commit target set.'],
        "owner_hints": ['designing-bulk-administration'], "verifier_hints": ['critiquing-security-and-privacy'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.destructive.delete-pending-not-gone', "domain": 'destructive', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'A deletion request that is still pending must not be represented as permanently gone',
        "statement": 'If deletion is asynchronous, queued, reversible for a grace period, or awaiting remote confirmation, the UI must distinguish requested or pending deletion from terminal removal and must reconcile failures or cancellation truthfully.',
        "intent": 'Keep destructive lifecycle aligned with authority so users know whether the object can still exist, recover, or fail to delete.',
        "applies_when": ['Delete or removal operations can remain pending, be retried, fail remotely, or support undo before final commit.'], "does_not_apply_when": [],
        "failure_modes": ['The item disappears with terminal deleted language immediately even though the authoritative delete is pending and can later fail or be cancelled.'],
        "user_impacts": ['Users may assume sensitive or unwanted content is gone when it still exists, or cannot understand why a supposedly deleted item reappears.'],
        "observables": ['Delay or reject deletion after the UI initiates it and compare visible lifecycle states with the authoritative object.'],
        "falsifiers": ['Pending deletion is represented as pending or undoable as appropriate, terminal language appears only after authoritative commit, and failure restores or explains the retained object.'],
        "repairs": ['Model deletion as explicit lifecycle states and reconcile UI from authoritative completion rather than treating click acknowledgement as terminal removal.'],
        "exceptions": ['Local-only ephemeral items may disappear immediately when the local mutation itself is the authoritative deletion boundary.'],
        "verification": ['Force delayed, failed, cancelled, and successful deletes and verify the visible state transitions match the authoritative lifecycle in every case.'],
        "owner_hints": ['designing-undo-redo-history'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.destructive.archive-vs-delete-distinct', "domain": 'destructive', "class": 'mechanical', "severity": 'major', "enforcement": 'block',
        "title": 'Archive and delete controls must remain semantically distinct when their retention and recovery differ',
        "statement": 'If archive and delete have different retention, visibility, recovery, legal, storage, or collaboration consequences, the UI must not use interchangeable wording or icons that hide which lifecycle action will occur.',
        "intent": 'Help users choose the intended content lifecycle operation rather than infer destructive semantics from generic remove affordances.',
        "applies_when": ['The product supports more than one removal-like action such as archive, trash, delete, remove from list, revoke, or hide with materially different consequences.'], "does_not_apply_when": [],
        "failure_modes": ['Controls, confirmation, or post-action feedback use ambiguous remove language so users cannot tell whether content remains recoverable, merely hidden, or permanently deleted.'],
        "user_impacts": ['Users can permanently delete content they meant to archive or assume deleted content is gone when it remains retained and discoverable elsewhere.'],
        "observables": ['Compare labels, confirmations, help text, and resulting lifecycle states for each removal action and inspect whether consequences are distinguishable before commit.'],
        "falsifiers": ['Each action uses language and feedback consistent with its retention or recovery semantics and exposes destructive permanence where it materially differs.'],
        "repairs": ['Name actions by domain lifecycle effect, use separate confirmations for irreversible states, and avoid reusing generic trash or remove icons without clarifying text where semantics differ.'],
        "exceptions": ['A product with only one removal lifecycle does not need to contrast archive versus delete when no alternate interpretation exists.'],
        "verification": ['Exercise every removal-like action and verify users can predict resulting visibility, retention, recovery, and permanence from pre-commit UI.'],
        "owner_hints": ['designing-undo-redo-history'], "verifier_hints": ['critiquing-user-experience'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["HISTORY_DESTRUCTIVE_RULES_V13"]
