"""V13 import, export, and migration rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

IMPORT_EXPORT_MIGRATION_RULES_V13 = [
    {
        "rule_id":"ui.import.mapping-preview-before-commit","domain":"import","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Structured import mapping must expose the interpreted destination before irreversible commit",
        "statement":"When imported columns or fields are mapped into a product schema, users must be able to inspect the effective source-to-destination mapping and representative parsed values before a high-impact import commits.",
        "intent":"Prevent schema guesses from creating valid-looking records under the wrong fields or units.",
        "applies_when":["Users import structured data whose headers, types, units, or destination fields can require mapping or inference."],"does_not_apply_when":[],
        "failure_modes":["The importer auto-maps ambiguous fields and commits without showing how source values will populate destination schema."],
        "user_impacts":["Large datasets can be imported with swapped identities, units, dates, or categories and require costly cleanup."],
        "observables":["Use ambiguous headers and type-compatible but semantically different columns and compare preview mapping with committed records."],
        "falsifiers":["The effective mapping and representative parsed values are inspectable before commit and ambiguous mappings require a choice or explicit policy."],
        "repairs":["Separate parsing and mapping from commit, show destination fields and sample values, and require resolution for materially ambiguous mappings."],
        "exceptions":["A fixed machine-to-machine format with a versioned schema may bypass human mapping when the schema match is authoritative."],
        "verification":["Import ambiguous and unambiguous datasets and verify the preview reflects the exact mapping later used at commit."],
        "owner_hints":["designing-structured-import-mapping"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.import.partial-failure-preserves-row-results","domain":"import","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Partial import failure must preserve which records committed and which remain recoverable",
        "statement":"If an import can commit some records while rejecting others, the result must retain item-level outcomes and retry material rather than collapse the operation into a single success or failure state.",
        "intent":"Enable safe recovery without duplicating records that already imported successfully.",
        "applies_when":["Structured or batch import permits partial commit across independent rows or objects."],"does_not_apply_when":[],
        "failure_modes":["The UI reports a global error after some rows committed but loses which rows succeeded, causing retry-all to create duplicates or hide unresolved failures."],
        "user_impacts":["Users can duplicate imported data or fail to recover rejected records accurately."],
        "observables":["Force mixed validation and server failures and compare item-level import results with authoritative committed records."],
        "falsifiers":["Committed and rejected items remain distinguishable and retry can target only unresolved items or use stable idempotency."],
        "repairs":["Track each imported object by stable source identity and terminal state, produce a failure report, and scope retry to unresolved items."],
        "exceptions":["Atomic imports may report one failure when the backend guarantees no item committed."],
        "verification":["Run mixed-outcome and atomic imports and verify recovery never duplicates already committed records."],
        "owner_hints":["designing-structured-import-mapping"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.import.encoding-detection-reviewable","domain":"import","class":"contextual","severity":"moderate","enforcement":"warn",
        "title":"Ambiguous text encoding or delimiter detection should be reviewable before parsing changes data meaning",
        "statement":"When import encoding, delimiter, decimal convention, or quoting cannot be determined reliably, the interface should expose or allow correction of the detected interpretation rather than silently parse mojibake or shifted columns.",
        "intent":"Keep automatic format detection helpful without turning uncertain heuristics into authoritative data interpretation.",
        "applies_when":["Users import delimited or text files whose encoding or structural dialect is not guaranteed by a versioned format."],"does_not_apply_when":[],
        "failure_modes":["The importer guesses an ambiguous encoding or delimiter and proceeds even though previewed text or columns are malformed."],
        "user_impacts":["Names, identifiers, amounts, and field boundaries can be corrupted while the import still appears syntactically successful."],
        "observables":["Provide files with ambiguous delimiter, encoding, quoting, and decimal conventions and inspect detection confidence and preview."],
        "falsifiers":["High-confidence formats parse consistently while ambiguous detection can be inspected and corrected before commit."],
        "repairs":["Expose parsing controls or confidence-triggered review and render a representative raw-to-parsed preview before importing."],
        "exceptions":["Strict formats with mandatory encoding and delimiter declarations need no heuristic review when invalid files are rejected."],
        "verification":["Test UTF variants, legacy encodings, comma/tab/semicolon dialects, quotes, and locale decimals and verify ambiguity never silently corrupts import."],
        "owner_hints":["designing-structured-import-mapping"],"verifier_hints":["critiquing-user-experience"],"capabilities":interaction_caps(**{"semantic-product":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.export.scope-matches-requested-filter","domain":"export","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Exported scope must match the filter or selection the user authorized",
        "statement":"When an export is initiated from a filtered, searched, selected, paginated, or scoped view, the export contract must make clear whether it includes visible rows, selected items, all matching results, or the entire dataset and execute that same scope.",
        "intent":"Prevent data exports from silently including more or less information than users intended, especially sensitive records outside the visible view.",
        "applies_when":["Export can operate on a subset defined by search, filter, selection, workspace, account, date range, or pagination."],"does_not_apply_when":[],
        "failure_modes":["A filtered view says Export but the generated file contains the whole dataset, or only the current page is exported when the user authorized all matching results."],
        "user_impacts":["Users can leak unrelated data or deliver incomplete datasets while believing export matched the visible scope."],
        "observables":["Create filters and selections spanning pages and compare the declared export scope with generated record identities."],
        "falsifiers":["The pre-export control communicates effective scope and the output contains exactly that authoritative target set."],
        "repairs":["Represent export scope as an explicit query or identity set, confirm ambiguous all-versus-visible semantics, and execute from that same immutable scope contract."],
        "exceptions":["A dedicated full-dataset export surface may always export everything when that behavior is explicit and independent of table filters."],
        "verification":["Test visible-page, selected, all-matching, and full-dataset exports and compare output IDs against authorized scope."],
        "owner_hints":["designing-data-export-portability"],"verifier_hints":["critiquing-security-and-privacy"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.export.generated-file-bound-to-request-version","domain":"export","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Asynchronous export results must remain bound to the request version that generated them",
        "statement":"When data or export settings can change while a file is being generated, the completed download must retain the request parameters or snapshot identity used to build it rather than appear as though it reflects current screen state.",
        "intent":"Prevent stale generated files from being mistaken for exports of newer filters, data revisions, or configuration.",
        "applies_when":["Exports are asynchronous or queued and source data or export configuration can change before completion."],"does_not_apply_when":[],
        "failure_modes":["An old export completes after the user changes filters or starts another export and the generic download action is relabeled as the current request."],
        "user_impacts":["Users can share or analyze a file with the wrong scope or data version because completion lost request provenance."],
        "observables":["Start exports A and B with different scope and complete them out of order, then inspect download labels and output metadata."],
        "falsifiers":["Each result keeps stable job and request identity and exposes enough request context to distinguish older files from current view state."],
        "repairs":["Persist normalized export parameters and source snapshot/version with the job and bind completion notifications and downloads to that identity."],
        "exceptions":["Synchronous exports completed before any state can change do not need a long-lived request provenance surface."],
        "verification":["Complete multiple exports out of order after filter and data changes and verify each file maps to its originating request."],
        "owner_hints":["designing-export-configuration"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.migration.resume-does-not-reapply-completed-step","domain":"migration","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Resuming a migration must not reapply a completed non-idempotent step",
        "statement":"A resumable migration must persist step or item completion strongly enough that restart continues from unresolved work instead of replaying already committed transformations, invitations, writes, or charges.",
        "intent":"Make interrupted migrations recoverable without multiplying side effects or corrupting partially moved state.",
        "applies_when":["A migration or onboarding transfer spans multiple durable steps and can be interrupted or resumed."],"does_not_apply_when":[],
        "failure_modes":["Restart begins from an earlier checkpoint and re-executes completed non-idempotent work because UI progress was not tied to authoritative step state."],
        "user_impacts":["Users can get duplicate records, notifications, permissions, or other side effects after recovery from interruption."],
        "observables":["Interrupt after each durable step, resume repeatedly, and inspect authoritative side effects and step ledger."],
        "falsifiers":["Resume identifies completed steps or safely idempotent operations and executes only work that remains unresolved."],
        "repairs":["Persist migration checkpoints and idempotency identities at authority boundaries rather than deriving resume position from transient progress percentage."],
        "exceptions":["A fully idempotent migration may replay steps when the backend guarantees identical result without duplicate side effects."],
        "verification":["Crash and resume at every step boundary and confirm each non-idempotent side effect occurs at most once."],
        "owner_hints":["designing-migration-onboarding"],"verifier_hints":["critiquing-performance-and-resilience"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["IMPORT_EXPORT_MIGRATION_RULES_V13"]
