"""V13 localization and search-state rules."""
from __future__ import annotations

from ._capabilities import interaction_caps


LOCALIZATION_SEARCH_RULES_V13 = [
    {
        "rule_id": "ui.locale.number-format-matches-locale-and-unit",
        "domain": "locale", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Localized numbers must preserve value, unit, sign, and grouping meaning",
        "statement": "Formatting a numeric value for locale must not change its underlying magnitude, sign, unit/currency identity, decimal meaning, or grouping semantics, and parsing/editing must not silently reinterpret separators under the active locale.",
        "intent": "Prevent visually localized numbers from becoming different values or ambiguous financial/measurement inputs when decimal and grouping conventions vary.",
        "applies_when": ["The interface displays or accepts decimal numbers, percentages, measurements, currencies, quantities, or other locale-sensitive numeric values."],
        "does_not_apply_when": ["The value is an intentionally locale-neutral machine identifier, code, version, or data format whose syntax must not be localized."],
        "failure_modes": ["Locale formatting changes value meaning, drops unit/currency, swaps decimal/group separators incorrectly, or an edited localized string parses to a different magnitude than the user entered."],
        "user_impacts": ["Users can read or submit the wrong amount, quantity, rate, or measurement because localization changes semantics rather than presentation."],
        "observables": ["Round-trip representative positive, negative, fractional, large, and currency/measurement values through display and editing across locales and compare the authoritative numeric value."],
        "falsifiers": ["Formatting and parsing preserve the authoritative numeric value and unit while adapting separators, grouping, symbols, and placement according to the active locale."],
        "repairs": ["Use locale-aware formatting/parsing primitives, store canonical numeric values separately from display strings, and keep unit/currency identity explicit in the data model."],
        "exceptions": ["Intentionally rounded display values may reduce visible precision when the rounding policy is product-approved and users are not expected to recover the hidden exact value from the formatted text."],
        "verification": ["Round-trip representative values through display and editable input in several locales with contrasting separators and symbol placement, confirming value and unit identity remain unchanged."],
        "owner_hints": ["designing-locale-number-formatting"], "verifier_hints": ["critiquing-localization"],
        "capabilities": interaction_caps(**{"static": "PARTIAL", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.locale.datetime-disambiguates-zone",
        "domain": "locale", "class": "contextual", "severity": "major", "enforcement": "warn",
        "title": "Decision-relevant date and time displays must make the operative timezone basis recoverable",
        "statement": "When users coordinate, schedule, audit, expire, trade, publish, or otherwise act on time across zones, the interface must make the timezone basis clear enough to distinguish local display from source, event, account, or absolute time.",
        "intent": "Prevent identical clock labels from representing different moments when users or systems operate across timezones, daylight transitions, or locale preferences.",
        "applies_when": ["A displayed or editable timestamp affects deadlines, meetings, transactions, logs, publication, travel, collaboration, expiry, or any workflow where timezone changes the real moment."],
        "does_not_apply_when": ["The time is purely relative or local by definition and no user or system can reasonably interpret it in another operative timezone."],
        "failure_modes": ["The UI shows a clock time/date without recoverable timezone basis, converts inconsistently across surfaces, or lets editing reinterpret an existing instant under a different zone silently."],
        "user_impacts": ["Users can miss deadlines, schedule the wrong moment, misread audit history, or coordinate incorrectly because the same display maps to multiple possible instants."],
        "observables": ["Compare the same timestamp across users/zones and inspect whether the UI identifies the operative zone or preserves enough context to resolve the absolute instant unambiguously."],
        "falsifiers": ["Decision-relevant timestamps consistently expose or make inspectable the timezone basis, and editing explicitly preserves either the instant or local wall time according to product semantics."],
        "repairs": ["Model timezone alongside timestamps, label the operative basis at decision points, and define explicit conversion semantics when users change zone or edit local time."],
        "exceptions": ["Compact feeds may omit repeated timezone labels when a persistent page-level or user-level timezone context is clearly established and all displayed times follow it consistently."],
        "verification": ["Test the same event around daylight transitions and across multiple account/device timezones, comparing display, edit, storage, and audit surfaces for a consistent operative time basis."],
        "owner_hints": ["designing-locale-date-time-formatting"], "verifier_hints": ["critiquing-localization"],
        "capabilities": interaction_caps(**{"semantic-product": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.locale.rtl-mirrors-directional-meaning-not-content",
        "domain": "locale", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "RTL adaptation must mirror directional interface meaning without corrupting inherently directed content",
        "statement": "Right-to-left layout should mirror navigation, progression, placement, and directional UI relationships where meaning depends on reading direction while preserving inherent direction for media controls, data, maps, diagrams, codes, and other content whose semantics are not locale-relative.",
        "intent": "Avoid both under-mirroring interface structure and over-mirroring content whose left/right direction carries domain meaning independent of language.",
        "applies_when": ["A product supports right-to-left locales and contains directional icons, navigation, progressions, panels, media, charts, maps, diagrams, or mixed-direction content."],
        "does_not_apply_when": ["The product is restricted to locales with one reading direction and explicitly does not claim RTL support."],
        "failure_modes": ["LTR-specific placement or arrows remain wrong in RTL navigation, or the implementation blindly flips media/data/content whose inherent direction should remain unchanged."],
        "user_impacts": ["RTL users encounter reversed navigation logic, misleading directional symbols, corrupted content meaning, or interactions that visually contradict reading flow."],
        "observables": ["Render representative RTL locales and classify each directional element by locale-relative versus intrinsic direction; observed mirroring does not match that semantic classification."],
        "falsifiers": ["Locale-relative structure and directional affordances adapt to RTL while intrinsically directed content preserves its domain meaning and mixed-direction text remains readable."],
        "repairs": ["Use logical layout properties and semantic directional assets, define explicit non-mirroring exceptions for intrinsic content, and test mixed-direction data rather than applying a global transform."],
        "exceptions": ["Brand marks and culturally fixed symbols may preserve orientation even when adjacent navigation mirrors, provided their meaning does not imply the wrong interaction direction."],
        "verification": ["Review full task flows in RTL with navigation, media, maps/data, icons, and mixed-direction text, confirming each directional element follows its semantic rather than purely geometric mirroring rule."],
        "owner_hints": ["designing-rtl-component-mirroring"], "verifier_hints": ["critiquing-localization"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.locale.translation-expansion-does-not-hide-action",
        "domain": "locale", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Text expansion must not clip or hide the action needed to complete the current task",
        "statement": "Localized labels, validation, navigation, and action text must be able to expand within supported layouts without clipping essential meaning, pushing primary actions outside reachable regions, or turning controls into ambiguous truncated fragments.",
        "intent": "Ensure localization remains functionally complete when translated strings are materially longer than the source language.",
        "applies_when": ["The product localizes user-visible text in controls, forms, navigation, dialogs, banners, tables, cards, or other layouts with constrained dimensions."],
        "does_not_apply_when": ["The product intentionally uses a language-independent symbol whose accessible name is localized separately and the visible symbol remains unambiguous."],
        "failure_modes": ["Longer translations are clipped, overlap adjacent content, push commit/cancel actions off-screen, collapse into indistinguishable ellipses, or require a viewport wider than the supported layout."],
        "user_impacts": ["Users cannot understand or activate essential controls in some locales even though the source-language layout appears complete."],
        "observables": ["Pseudolocalized or long real translations cause essential labels/actions to overflow, become unreachable, or lose the text necessary to distinguish their purpose."],
        "falsifiers": ["Supported layouts accommodate realistic expansion through wrapping, flexible sizing, reflow, or alternative composition while preserving complete access to essential actions and meaning."],
        "repairs": ["Replace brittle fixed dimensions with flexible/reflowing layout, define meaningful wrapping and overflow behavior, and use pseudolocalization to expose constrained regions before translation delivery."],
        "exceptions": ["Truncation may be appropriate for user-generated titles when the full value is inspectable and truncation does not affect the identity of an essential command."],
        "verification": ["Run pseudolocalization and representative verbose translations across supported breakpoints, then inspect essential labels, validation, navigation, and commit/cancel actions for clipping or lost reachability."],
        "owner_hints": ["designing-translation-expansion-resilience"], "verifier_hints": ["critiquing-localization"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED"}), "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.search.filter-state-visible-in-results",
        "domain": "search", "class": "contextual", "severity": "major", "enforcement": "warn",
        "title": "Search results must make active filtering and scope recoverable when they change what can appear",
        "statement": "When query scope, facets, hidden filters, permissions, saved constraints, date ranges, or other conditions materially restrict search results, users must be able to recover which constraints are active from the result state itself.",
        "intent": "Prevent users from treating a constrained result set as a complete search of the product when invisible scope is actually excluding relevant items.",
        "applies_when": ["A search surface can apply filters or scopes beyond the literal query text, including persisted facets, current-folder scope, saved views, role restrictions, date bounds, or contextual entity types."],
        "does_not_apply_when": ["The search domain has exactly one immutable scope and no user or system state can further restrict the candidate set."],
        "failure_modes": ["Results or no-results states omit material active constraints, so users cannot tell that hidden filters or scope—not the query alone—caused items to disappear."],
        "user_impacts": ["Users conclude content does not exist, duplicate records, broaden queries unnecessarily, or make decisions from an incomplete result set without realizing why it is incomplete."],
        "observables": ["Apply non-query constraints, run a search with known excluded matches, and inspect whether the result surface makes the active scope/filter state discoverable and removable where permitted."],
        "falsifiers": ["Material constraints are visible or inspectable from the result state, no-results copy reflects constrained scope, and users can adjust applicable filters without reconstructing the whole search."],
        "repairs": ["Represent active scope and facets alongside results, include constrained-state context in empty results, and preserve removable filter chips or an equivalent inspectable filter summary."],
        "exceptions": ["Security-enforced permissions should not reveal inaccessible data or forbidden scope details, but the interface may still state that results reflect the user's available access."],
        "verification": ["Search with and without persisted facets, scoped containers, date limits, and permission constraints and confirm the result state communicates every decision-relevant active restriction users are allowed to know."],
        "owner_hints": ["designing-faceted-search"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"semantic-product": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.search.saved-view-does-not-silently-drift",
        "domain": "search", "class": "behavioral", "severity": "moderate", "enforcement": "warn",
        "title": "A saved search or view must not silently change its query semantics after schema or filter evolution",
        "statement": "When saved searches, views, or filters depend on fields, operators, scopes, or ranking semantics that later change, the product must preserve the original meaning where possible or surface migration and incompatibility instead of silently executing a different query.",
        "intent": "Protect repeatable analytical and operational workflows from semantic drift as the product's search model evolves.",
        "applies_when": ["Users can persist search criteria, filter builders, dashboard views, alert queries, or other reusable retrieval definitions across product versions or schema changes."],
        "does_not_apply_when": ["The saved item is explicitly a mutable shortcut that always adopts current defaults and its non-stable semantics are part of the product contract."],
        "failure_modes": ["A removed field, changed operator, default scope, ranking rule, or schema migration alters the saved result set without warning while the saved view retains the same name and apparent validity."],
        "user_impacts": ["Users rely on recurring searches that no longer mean what they originally configured, potentially missing records or acting on newly included items without realizing the query changed."],
        "observables": ["Load a saved definition created before a search-schema change and compare its normalized query semantics and result scope with the originally persisted definition."],
        "falsifiers": ["The saved definition preserves compatible semantics, is explicitly migrated with reviewable changes, or enters an incompatible state that requires user repair before presenting changed results as equivalent."],
        "repairs": ["Version saved-query schemas, migrate operators and field identities explicitly, retain original normalized intent, and surface any semantic change that cannot be preserved automatically."],
        "exceptions": ["Ranking-only changes may be acceptable without migration when the saved view guarantees membership criteria but explicitly does not promise stable ordering."],
        "verification": ["Create saved searches using fields and operators, apply representative schema/default changes, reopen them, and compare normalized query meaning plus user-visible migration/incompatibility handling."],
        "owner_hints": ["designing-saved-searches-and-views"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["LOCALIZATION_SEARCH_RULES_V13"]
