"""V13 messaging rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

MESSAGING_RULES_V13 = [
    {
        "rule_id":"ui.messaging.delivery-state-not-read-state","domain":"messaging","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Message delivery must not be presented as recipient read state",
        "statement":"Sent, server-accepted, delivered-to-device, and read or seen states must remain semantically distinct when the product exposes them; transport delivery alone must not produce a read indicator.",
        "intent":"Prevent communication status from claiming recipient attention that the system has not observed.",
        "applies_when":["The messaging UI displays delivery or read receipts."],"does_not_apply_when":[],
        "failure_modes":["A transport acknowledgement or device delivery event flips the message to read or seen without a corresponding read receipt or product-defined observation."],
        "user_impacts":["Senders can infer that a recipient saw information when only transport delivery occurred."],
        "observables":["Drive messages through queued, sent, delivered, and read events separately and compare visible status with authoritative receipt state."],
        "falsifiers":["Each visible status corresponds only to the strongest authoritative event actually observed."],
        "repairs":["Model transport and attention receipts as separate states and map UI labels or icons to explicit receipt events."],
        "exceptions":["Products that intentionally expose only a coarse sent state need not distinguish unshown delivery stages as long as they do not call them read."],
        "verification":["Delay or suppress read receipts after successful delivery and verify the UI never upgrades delivery to seen."],
        "owner_hints":["designing-message-delivery-state"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.messaging.retry-does-not-duplicate-message","domain":"messaging","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Retry after ambiguous send completion must not create a duplicate logical message",
        "statement":"If acknowledgement is lost after a message may have committed, automatic or user retry must preserve operation identity or reconcile the original message rather than submit a second distinct message blindly.",
        "intent":"Protect conversations from duplicate messages caused by uncertain network completion.",
        "applies_when":["Message send can be retried after timeout, reconnect, or ambiguous transport failure."],"does_not_apply_when":[],
        "failure_modes":["The first send commits but loses its acknowledgement and retry produces another message with the same user content as a new authoritative object."],
        "user_impacts":["Recipients receive duplicate messages and senders cannot tell which copy reflects subsequent delivery or reply state."],
        "observables":["Drop acknowledgement after server commit, retry, and inspect authoritative message IDs and conversation output."],
        "falsifiers":["Retry resolves or reuses the original send identity and at most one logical message becomes authoritative."],
        "repairs":["Assign a stable client message or idempotency ID before send and retain it across retries and reconnect reconciliation."],
        "exceptions":["A deliberate resend action may create a new message when explicitly labeled as a new send rather than retry recovery."],
        "verification":["Inject failures before send, after commit, and before acknowledgement and confirm retry never duplicates the logical message."],
        "owner_hints":["designing-message-delivery-state"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.messaging.edit-race-preserves-latest-authoritative-version","domain":"messaging","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Out-of-order message edit responses must not restore an older edit over a newer one",
        "statement":"When multiple edits to one message are in flight, late acknowledgement or synchronization for an older edit must not overwrite a later authoritative or still-pending version.",
        "intent":"Keep message editing causally ordered under latency and multi-device races.",
        "applies_when":["Users can edit a message more than once before all prior edit requests or sync events have completed."],"does_not_apply_when":[],
        "failure_modes":["Edit B is visible, then a late response for edit A replaces the message with A because responses are applied by arrival rather than version."],
        "user_impacts":["The conversation can revert to text the user already corrected or expose an unintended earlier version."],
        "observables":["Send edits A and B with forced completion order B then A and compare visible and authoritative message version."],
        "falsifiers":["Older edit events are ignored or merged according to version identity and cannot replace a newer committed or pending edit."],
        "repairs":["Version message edits and reconcile responses against current version or mutation identity instead of applying every success event to the same view slot."],
        "exceptions":["Systems that serialize editing server-side may avoid concurrent versions, but clients must still handle stale responses consistently."],
        "verification":["Force reordered edit acknowledgements and cross-device edits and verify the latest declared version remains authoritative."],
        "owner_hints":["designing-chat-interfaces"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.messaging.attachment-send-waits-for-upload-authority","domain":"messaging","class":"behavioral","severity":"major","enforcement":"block",
        "title":"A message attachment must not appear successfully sent before its upload becomes usable",
        "statement":"When attachment storage is a separate asynchronous operation, message send must bind to an authoritative attachment object or explicitly represent pending media rather than claiming a usable attachment that can still fail to upload.",
        "intent":"Keep message success and attachment availability consistent for both sender and recipients.",
        "applies_when":["Messages can include files or media uploaded asynchronously before or during send."],"does_not_apply_when":[],
        "failure_modes":["The message reports sent with an attachment card even though the upload later fails and recipients cannot retrieve the file."],
        "user_impacts":["Users believe they shared required material but recipients receive a broken or permanently unavailable attachment."],
        "observables":["Delay and fail attachment upload around send and inspect message status, recipient availability, and recovery."],
        "falsifiers":["Send waits for a usable attachment reference or clearly exposes pending upload state and reconciles failure without claiming completed sharing."],
        "repairs":["Bind message payload to stable uploaded attachment identity or model attachment-pending lifecycle explicitly with retry or removal recovery."],
        "exceptions":["Some systems intentionally send placeholders while media uploads; the placeholder must remain visibly pending and not imply availability."],
        "verification":["Exercise successful, slow, failed, cancelled, and retried uploads and verify message and attachment states remain truthful."],
        "owner_hints":["designing-message-attachments"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.messaging.reply-target-stable-after-reorder","domain":"messaging","class":"mechanical","severity":"moderate","enforcement":"warn",
        "title":"Reply context must stay bound to message identity when the timeline reorders or changes",
        "statement":"Quoted replies, threads, and reply composers must reference stable message identity rather than current list index so incoming history, deletion, or sorting cannot retarget the reply silently.",
        "intent":"Ensure users respond to the message they selected even when the conversation changes before send.",
        "applies_when":["Users can reply to a specific message while the timeline can receive new messages, reorder, paginate, or update concurrently."],"does_not_apply_when":[],
        "failure_modes":["Reply target is stored as array position and becomes another message after insertion, deletion, or reorder."],
        "user_impacts":["Users can send a response attached to the wrong statement or person."],
        "observables":["Open reply composer, mutate timeline ordering and items, then inspect quoted target and outgoing reply reference."],
        "falsifiers":["Reply target remains the same stable message identity or becomes explicitly unavailable if that target is no longer replyable."],
        "repairs":["Store and submit stable message or thread IDs, and reconcile target deletion or access changes explicitly."],
        "exceptions":["A composer for the whole conversation without message-specific reply semantics has no target identity to preserve."],
        "verification":["Insert, delete, paginate, and reorder messages while composing a reply and confirm target identity never shifts silently."],
        "owner_hints":["designing-chat-interfaces"],"verifier_hints":["critiquing-user-experience"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.messaging.offline-send-queued-not-delivered","domain":"messaging","class":"mechanical","severity":"major","enforcement":"block",
        "title":"Offline outgoing messages must be represented as queued rather than delivered",
        "statement":"A message accepted into a local offline queue must not receive sent, delivered, or read semantics until the corresponding authority event occurs after reconnect.",
        "intent":"Keep offline composition useful without fabricating network or recipient state.",
        "applies_when":["The messaging product supports composing or submitting messages while disconnected."],"does_not_apply_when":[],
        "failure_modes":["Pressing send offline immediately shows ordinary sent or delivered state even though no server or peer accepted the message."],
        "user_impacts":["Users can assume communication succeeded and fail to notice messages that remain stranded locally."],
        "observables":["Disconnect before send and trace local queue, reconnect, server acceptance, device delivery, and UI status transitions."],
        "falsifiers":["Offline messages remain clearly queued or unsent until authoritative send and delivery events advance their lifecycle."],
        "repairs":["Model local queue state separately from remote send state and transition only on correlated transport acknowledgements."],
        "exceptions":["Peer-to-peer products may have a different authority boundary, but local enqueue alone still must not imply remote receipt."],
        "verification":["Send while offline, close and reopen, reconnect, fail, and retry; verify status reflects each real lifecycle boundary."],
        "owner_hints":["designing-offline-message-reconciliation"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["MESSAGING_RULES_V13"]
