"""V13 mobile and responsive continuity rules."""
from __future__ import annotations

from ._capabilities import interaction_caps


MOBILE_RESPONSIVE_RULES_V13 = [
    {
        "rule_id": "ui.mobile.safe-area-protects-primary-actions",
        "domain": "mobile", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Primary mobile actions must remain reachable outside unsafe display and system gesture regions",
        "statement": "Controls required to complete, cancel, navigate, submit, or recover a mobile task must account for device safe areas and system gesture zones so they are not clipped, obscured, or unreliable at supported screen configurations.",
        "intent": "Keep essential controls physically reachable on devices with cutouts, home indicators, rounded corners, transient bars, and other platform-reserved regions.",
        "applies_when": ["A mobile or tablet layout places persistent or bottom-edge controls near device insets, cutouts, home indicators, system bars, or gesture-sensitive screen edges."],
        "does_not_apply_when": ["The surface is rendered inside a platform container that already guarantees the documented safe content region and the product does not position controls outside it."],
        "failure_modes": ["A required action overlaps unsafe insets, is partially clipped, sits behind a system affordance, or requires repeated attempts because edge gestures intercept the intended tap."],
        "user_impacts": ["Users cannot reliably finish or leave a workflow on particular devices or orientations even though the same control works on a developer's reference viewport."],
        "observables": ["Rendering on representative safe-area geometries shows essential control bounds intersecting platform-reserved regions or system gestures capturing activation near the edge."],
        "falsifiers": ["Essential actions remain fully visible, tappable, and separated from unsafe insets and conflicting system gestures across supported devices, orientations, and transient system-bar states."],
        "repairs": ["Anchor essential controls to safe-area-aware containers, add appropriate inset spacing, and move high-value actions away from gesture conflict zones instead of compensating with arbitrary fixed padding."],
        "exceptions": ["Immersive media or game surfaces may intentionally draw into unsafe regions when essential controls move to a safe interactive layer or are recoverable through platform-standard gestures."],
        "verification": ["Test representative devices with different cutouts and home indicators in supported orientations, including transient system bars, and confirm every essential action remains visible and reliably activatable."],
        "owner_hints": ["designing-mobile-safe-area-integration"], "verifier_hints": ["critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.mobile.virtual-keyboard-keeps-active-field-visible",
        "domain": "mobile", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Opening the virtual keyboard must keep the active field and its required action visible or reachable",
        "statement": "When the virtual keyboard changes the usable viewport, the currently edited field, validation feedback, and the action required to continue must remain visible or become predictably reachable without dismissing input unexpectedly.",
        "intent": "Prevent mobile form completion from breaking when the keyboard covers the active control, error message, autocomplete list, or submit/next action.",
        "applies_when": ["Text, numeric, search, authentication, messaging, or other input on a mobile surface opens a virtual keyboard that resizes or overlays the application viewport."],
        "does_not_apply_when": ["The platform uses a separate full-screen input mode where the editing context and completion action are intentionally moved into the system input surface."],
        "failure_modes": ["The keyboard obscures the active field or required next action, scroll correction moves focus away, or fixed content prevents the user from bringing the editing context into view."],
        "user_impacts": ["Users type without seeing the field, miss validation, cannot submit, or must dismiss and reopen the keyboard repeatedly to complete a basic task."],
        "observables": ["Focus fields near viewport edges and inspect the post-keyboard layout; active input, error/help content, autocomplete, or progression control becomes covered or unreachable."],
        "falsifiers": ["Keyboard appearance preserves a stable editing context through resize, scroll, inset, or adaptive control placement and the user can complete the interaction without losing focus unexpectedly."],
        "repairs": ["Respond to keyboard insets/viewport changes, scroll the active field into a bounded visible region, and adapt sticky controls so input context and progression remain reachable together."],
        "exceptions": ["A deliberate full-screen composer may hide surrounding controls while the keyboard is active if it provides an explicit completion/cancel mechanism and restores prior context afterward."],
        "verification": ["Focus first, middle, and last fields across supported device sizes and orientations, trigger validation and autocomplete, and confirm active content plus the next required action remain reachable with the keyboard open."],
        "owner_hints": ["designing-virtual-keyboard-avoidance"], "verifier_hints": ["critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.mobile.orientation-preserves-task-state",
        "domain": "mobile", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Changing device orientation must preserve the user's logical task state",
        "statement": "Supported orientation changes must preserve route, draft, selection, playback position, editor state, and other logical task context unless a documented product rule intentionally resets a specific dimension.",
        "intent": "Treat orientation as a layout transition rather than a new session so users do not lose work simply because device geometry changes.",
        "applies_when": ["The application supports more than one device orientation or can be resized between materially different mobile/tablet geometries while a task is in progress."],
        "does_not_apply_when": ["The product explicitly locks the current workflow to one orientation and the platform prevents unsupported rotation before any task state is created."],
        "failure_modes": ["Rotation recreates the screen from defaults, loses draft text, closes nested workflow state, resets media position, or clears selection/history unrelated to the geometry change."],
        "user_impacts": ["Users lose work or their place when rotating a device, connecting a display, or moving between supported compact and expanded layouts."],
        "observables": ["Capture decision-relevant state before an orientation change and compare the logical state after relayout; unrelated fields or workflow position revert without product justification."],
        "falsifiers": ["The layout adapts while route, drafts, selection, progress, and other task state remain logically equivalent or intentionally transformed according to documented mode semantics."],
        "repairs": ["Separate persistent/task state from view geometry, restore transient view anchors after relayout, and avoid reinitializing feature state from default props during orientation reconstruction."],
        "exceptions": ["A spatial or camera feature may recompute viewport-specific coordinates on rotation when it preserves the underlying selected object, content, and user intent."],
        "verification": ["Create representative draft, selection, scroll, playback, and nested navigation state, rotate through supported orientations, and compare task semantics before and after each transition."],
        "owner_hints": ["designing-device-orientation-transitions"], "verifier_hints": ["critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.mobile.gesture-conflict-has-alternative",
        "domain": "mobile", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "App gestures that conflict with system navigation need a reliable alternative path",
        "statement": "When a custom edge swipe, drag, or other gesture competes with operating-system navigation or accessibility gestures, the product must provide a reliable non-conflicting way to perform the app action and must not require precision that the system routinely intercepts.",
        "intent": "Prevent feature reachability from depending on winning a gesture arbitration boundary the application does not fully control.",
        "applies_when": ["A mobile product maps app-specific actions to screen-edge swipes, back-like drags, multi-finger gestures, or regions reserved or commonly captured by platform navigation/accessibility behavior."],
        "does_not_apply_when": ["The platform explicitly grants the application exclusive control of the gesture region for the current mode and users retain a standard way to exit that mode."],
        "failure_modes": ["The app action has no visible/control alternative and users must repeatedly attempt a gesture that is intercepted by system back/home/navigation or an enabled accessibility gesture."],
        "user_impacts": ["Users cannot reliably invoke the feature, accidentally leave the screen, or lose state because platform navigation wins the same gesture the app requires."],
        "observables": ["Exercise the custom gesture with platform navigation and accessibility gestures enabled; the app action becomes unreliable and no equivalent button/menu/command is available."],
        "falsifiers": ["The gesture coexists reliably with platform behavior or an equivalent reachable control performs the same app operation without entering the conflict zone."],
        "repairs": ["Move the app gesture away from reserved edges, use platform-sanctioned gesture APIs, and expose an equivalent explicit control for users or configurations where conflict remains."],
        "exceptions": ["Immersive experiences may temporarily redefine gesture behavior when they visibly enter a mode with clear controls for exiting and restoring normal system navigation expectations."],
        "verification": ["Test the gesture with system navigation variants and relevant accessibility gestures enabled, then verify both the gesture and the explicit alternative complete the intended app action without unintended navigation."],
        "owner_hints": ["designing-mobile-gesture-navigation-conflicts"], "verifier_hints": ["critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.mobile.responsive-reflow-preserves-reading-order",
        "domain": "mobile", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Responsive visual reordering must preserve a coherent semantic reading and focus order",
        "statement": "When regions move, stack, collapse, or reorder across breakpoints, the semantic document and keyboard order must remain coherent with the rendered task flow instead of preserving a desktop source order that becomes confusing on smaller layouts.",
        "intent": "Keep responsive adaptation usable for assistive technology and keyboard navigation rather than solving only visual geometry.",
        "applies_when": ["A responsive layout materially changes the visible order or grouping of controls, content regions, summaries, actions, or navigation between supported viewport modes."],
        "does_not_apply_when": ["The visual order changes only for decorative regions that do not affect reading sequence, relationships, or interactive task progression."],
        "failure_modes": ["CSS/grid/flex reordering produces a visual sequence that conflicts with DOM reading or tab order, causing focus or screen-reader progression to jump through unrelated regions."],
        "user_impacts": ["Keyboard and screen-reader users experience a different task sequence from sighted users and can lose relationships between labels, content, and actions after responsive reflow."],
        "observables": ["Compare rendered region order with DOM/accessibility reading and tab order at each breakpoint and find transitions that cross unrelated visual groups or reverse the task sequence."],
        "falsifiers": ["At every supported responsive mode, semantic reading and focus order remain coherent with the visible task sequence even when the physical arrangement changes."],
        "repairs": ["Prefer source-order layouts that naturally reflow, restructure DOM when the semantic order truly changes, and avoid visual-order properties that create a separate inaccessible sequence."],
        "exceptions": ["Minor decorative or redundant summary placement may differ visually when semantic relationships and focus progression remain unambiguous."],
        "verification": ["Inspect DOM/accessibility order and keyboard progression across compact, intermediate, and wide layouts and compare them with the rendered sequence of task-relevant regions."],
        "owner_hints": ["designing-responsive-region-reordering"], "verifier_hints": ["critiquing-accessibility", "critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"accessibility-tree": "REQUIRED", "visual-render": "REQUIRED"}), "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.mobile.breakpoint-does-not-drop-active-controls",
        "domain": "mobile", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Crossing a responsive breakpoint must not silently discard an active control or unfinished interaction",
        "statement": "When a toolbar, sidebar, filter panel, editor inspector, or other interactive region collapses or moves at a breakpoint, active values, open edits, selected commands, and reachable completion paths must survive the mode transition.",
        "intent": "Prevent responsive layout mode changes from acting like hidden workflow resets when users resize, rotate, zoom, or move between device classes.",
        "applies_when": ["Responsive adaptation replaces a region with an overflow menu, drawer, compact control, tab, stacked panel, or other alternative representation while the region can contain active task state."],
        "does_not_apply_when": ["The disappearing region contains no task state and its functionality remains continuously represented elsewhere without a semantic transition."],
        "failure_modes": ["Crossing the breakpoint closes an unfinished edit without recovery, resets filters, drops selected tool state, or removes the only control needed to commit/cancel the active interaction."],
        "user_impacts": ["Users lose work or cannot finish the current operation when window/device geometry changes during a task."],
        "observables": ["Activate state inside a region near a breakpoint, cross the threshold, and observe whether the alternate representation preserves values, action availability, and the ability to continue or cancel."],
        "falsifiers": ["The responsive representation changes while active values and task semantics persist, with any unavoidable mode transition explicitly preserving or handing off the unfinished interaction."],
        "repairs": ["Store active state above layout-specific components, migrate focus and control representation across breakpoint modes, and provide overflow/drawer equivalents for actions that disappear visually."],
        "exceptions": ["A breakpoint may intentionally cancel a mode that cannot function in the new geometry when the product warns before cancellation or preserves the work in a recoverable draft."],
        "verification": ["Open and modify stateful toolbars, filters, inspectors, and dialogs, cross relevant breakpoints in both directions, and verify values plus commit/cancel paths survive each transition."],
        "owner_hints": ["preserving-responsive-state-continuity"], "verifier_hints": ["critiquing-responsive-behavior"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "visual-render": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["MOBILE_RESPONSIVE_RULES_V13"]
