"""V13 navigation, continuity, and recovery rules."""
from __future__ import annotations

from ._capabilities import interaction_caps


NAVIGATION_RESILIENCE_RULES_V13 = [
    {
        "rule_id": "ui.navigation.back-restores-context",
        "domain": "navigation", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Back navigation must restore the prior task context rather than a generic starting point",
        "statement": "When users navigate from a list, search, dashboard, document collection, or other stateful surface into detail and then go back, the product must restore the decision-relevant context that made the prior surface useful.",
        "intent": "Prevent navigation from destroying search, filter, selection, scroll, pagination, or workspace context and forcing users to reconstruct the task after every detail visit.",
        "applies_when": ["A user leaves a stateful collection or workspace through an in-product or platform navigation transition and later invokes back, close, or return to the previous context."],
        "does_not_apply_when": ["The previous surface intentionally represents a new session boundary and product requirements explicitly reset state after the completed transition."],
        "failure_modes": ["Returning reconstructs a default page, loses filters or selection, resets scroll/page position, or otherwise drops context necessary to continue where the user left off."],
        "user_impacts": ["Users repeatedly redo navigation and filtering work, can lose their place in long collections, and may inspect or act on the wrong item after context resets."],
        "observables": ["Capture the prior route and interaction state, navigate to detail, return, and observe that one or more decision-relevant state dimensions no longer match the prior context without an intentional reason."],
        "falsifiers": ["Returning restores the previous collection/workspace context or an explicitly documented equivalent that preserves the user's place, active constraints, and unfinished task state."],
        "repairs": ["Persist navigation context in route/history or state restoration mechanisms and distinguish deliberate workflow reset from ordinary return navigation."],
        "exceptions": ["Sensitive or volatile data may intentionally refresh on return when stale state would be unsafe, provided the interface preserves the user's logical place and explains material refresh effects."],
        "verification": ["Set filters, selection, scroll/page position, and other representative context, navigate into detail, return through supported back paths, and compare the restored state with the captured prior state."],
        "owner_hints": ["designing-navigation"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.navigation.deep-link-resolves-valid-state",
        "domain": "navigation", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "A deep link must resolve authentication and resource state before presenting a false destination",
        "statement": "Opening a deep link must preserve the intended destination across authentication, onboarding, permission, app-install, or state-rehydration boundaries and must not silently land on a generic home surface as though navigation succeeded.",
        "intent": "Keep externally shared and system-generated links trustworthy across the real lifecycle steps required before the target can be rendered.",
        "applies_when": ["The product accepts links that identify a specific record, conversation, document, notification target, route, or workflow state and access may require intermediate application state."],
        "does_not_apply_when": ["The link intentionally targets the product root or the referenced resource is permanently unavailable and the product explicitly communicates that condition."],
        "failure_modes": ["An intermediate authentication, permission, launch, or hydration step discards the target so the user reaches home, a stale page, or another unrelated surface without an explicit target failure."],
        "user_impacts": ["Users cannot reach shared or notified content, may believe the link was wrong, and can lose the context needed to understand why they opened the product."],
        "observables": ["Open the same target link from cold, signed-out, signed-in, and permission-limited states and observe one path losing target identity or rendering an unrelated destination without explanation."],
        "falsifiers": ["Every supported entry state either resolves to the intended accessible target or reaches an explicit unavailable/unauthorized recovery state that still preserves target identity for the next valid step."],
        "repairs": ["Persist the intended route and target through intermediate boundaries, validate it after state changes, and route unavailable resources to contextual recovery rather than generic home fallback."],
        "exceptions": ["Security policy may intentionally suppress sensitive target identity before authentication, but the system should still retain the destination internally and resume it after authorization when permitted."],
        "verification": ["Exercise representative deep links from cold launch, expired session, onboarding, denied permission, and normal states, then confirm the final route or recovery state remains tied to the original target."],
        "owner_hints": ["designing-mobile-deep-link-routing"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.navigation.retry-preserves-user-work",
        "domain": "navigation", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Retry after a recoverable failure must preserve valid user work and operation scope",
        "statement": "When a request, transition, upload, save, or other operation fails for a recoverable reason, retry must not discard valid user input or silently broaden, duplicate, or reset the operation the user intends to repeat.",
        "intent": "Make recovery cheap and trustworthy so transient failure does not turn into data loss or a second unintended action.",
        "applies_when": ["A user-visible operation can fail transiently and the interface offers retry, reconnect, resume, try again, or an equivalent recovery action."],
        "does_not_apply_when": ["The failed data is invalid, unsafe to retain, or security policy explicitly requires clearing it and the product communicates that reset before retry."],
        "failure_modes": ["Retry clears fields, loses attachments or selection, repeats already committed sub-operations, or uses a different target/scope than the failed attempt without showing that change."],
        "user_impacts": ["Users repeat work, submit duplicate effects, or retry against the wrong scope because the recovery action does not represent the original failed operation faithfully."],
        "observables": ["Force a recoverable failure after entering data or completing partial work, invoke retry, and compare the retained input and operation identity with the failed attempt."],
        "falsifiers": ["Retry preserves valid user work, reuses or reconstructs the intended operation scope safely, and distinguishes already committed portions from work that still needs execution."],
        "repairs": ["Persist recoverable draft state and stable operation identity, make retry idempotent where necessary, and expose partial completion instead of rebuilding a fresh default operation."],
        "exceptions": ["A fresh authorization or time-sensitive value may need to be reacquired on retry, but unrelated valid user work should remain intact and the required refresh should be explicit."],
        "verification": ["Inject transient failures at several operation stages, retry each case, and verify user-entered data, target identity, and committed versus uncommitted effects remain correct."],
        "owner_hints": ["designing-retry-and-recovery-actions"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.navigation.offline-state-not-empty-success",
        "domain": "navigation", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Offline or unavailable data must not be rendered as a legitimately empty result",
        "statement": "When required data cannot be loaded because connectivity, cache, authorization, or upstream availability is insufficient, the interface must distinguish that unknown or unavailable state from a valid zero-result or empty collection state.",
        "intent": "Prevent absence of evidence from being presented as evidence that no records, messages, tasks, files, or other items exist.",
        "applies_when": ["A collection, detail surface, search, dashboard, feed, or workflow depends on data that may be unavailable while the product remains partially operable."],
        "does_not_apply_when": ["The product has authoritative local data proving the collection is empty for the exact queried scope despite current network unavailability."],
        "failure_modes": ["A failed or unavailable fetch collapses into the same empty illustration, zero count, no-results copy, or success state used when the authoritative result is genuinely empty."],
        "user_impacts": ["Users may delete filters, assume work is gone, miss required actions, or make decisions based on a false belief that the requested data set contains nothing."],
        "observables": ["Disconnect or force the relevant data source unavailable and compare the rendered state with a confirmed zero-result response; the two states are indistinguishable or claim the same certainty."],
        "falsifiers": ["Unavailable, stale-cache, permission-limited, and authoritative-empty states are distinguishable and communicate what is known, what is missing, and how to recover when useful."],
        "repairs": ["Model data availability separately from collection cardinality, preserve stale data with freshness labeling when safe, and reserve empty-state semantics for confirmed empty results."],
        "exceptions": ["A deliberately offline-first dataset may use local authoritative state as the source of truth when product semantics explicitly define remote synchronization as secondary."],
        "verification": ["Compare confirmed-empty, network-offline, upstream-error, unauthorized, and stale-cache scenarios and verify only the confirmed-empty case communicates a definitive zero-result state."],
        "owner_hints": ["designing-offline-degraded-experiences"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.navigation.notification-continuation-preserves-target",
        "domain": "navigation", "class": "behavioral", "severity": "moderate", "enforcement": "warn",
        "title": "Opening a notification should preserve the event target and the action context it advertised",
        "statement": "A notification that names a conversation, task, alert, comment, delivery, approval, or other event should continue into the corresponding in-app object or contextual recovery state rather than merely opening the application shell.",
        "intent": "Honor the user's decision to act on a specific interruption by carrying its identity and actionable context into the product.",
        "applies_when": ["A system, push, email-linked, or in-product notification exposes a specific target or action and users can open it to continue in the application."],
        "does_not_apply_when": ["The notification is intentionally product-wide, contains no object/action target, and its purpose is simply to bring users back to the general application."],
        "failure_modes": ["Activation opens a generic home or unrelated screen, loses the referenced event after authentication, or lands near but not on the object/action the notification described."],
        "user_impacts": ["Users must rediscover the event manually, can act on stale adjacent content, or lose confidence that notifications correspond to real actionable state."],
        "observables": ["Activate representative notifications from foreground, background, cold-launch, and expired-session states and compare the eventual in-app target with the notification payload."],
        "falsifiers": ["Each notification either resolves to its intended accessible target/action or to a contextual unavailable/permission state that preserves what the user was trying to reach."],
        "repairs": ["Persist notification target identity through launch and authentication, resolve it against current application state, and provide contextual recovery when the event no longer exists."],
        "exceptions": ["Aggregated summary notifications may resolve to a filtered collection when no single target is primary, provided the aggregation context survives the transition."],
        "verification": ["Open object-specific and aggregate notifications across lifecycle states and verify the destination, filter, selection, and available action match the notification context."],
        "owner_hints": ["designing-notification-to-app-continuation"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.navigation.stale-route-resource-recovery",
        "domain": "navigation", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "A route to a moved or deleted resource needs contextual recovery instead of a dead end",
        "statement": "When a previously valid route points to a resource that was deleted, moved, archived, renamed, or made inaccessible, the interface should preserve enough context to explain the failure and offer the nearest safe continuation rather than an opaque generic error.",
        "intent": "Keep stale links and history entries useful without pretending the referenced object still exists or silently redirecting to unrelated content.",
        "applies_when": ["Routes or history entries can outlive mutable resources, permissions, folders, projects, conversations, documents, or other target identities."],
        "does_not_apply_when": ["Security or privacy policy requires suppressing whether the resource ever existed, in which case recovery must remain intentionally generic."],
        "failure_modes": ["The user sees a blank screen, generic 404, infinite loader, or silent home redirect without knowing whether the target moved, disappeared, lost permission, or can be recovered elsewhere."],
        "user_impacts": ["Users cannot distinguish a broken link from changed access, waste time searching, or unknowingly continue in the wrong resource after a silent redirect."],
        "observables": ["Navigate to stale routes representing deletion, move, archive, and permission loss and observe whether the rendered outcome preserves target context and a truthful recovery path."],
        "falsifiers": ["Each stale-resource condition reaches a bounded recovery state that communicates only allowed facts, preserves target context where safe, and offers an appropriate next action or parent location."],
        "repairs": ["Resolve route identity before rendering, map known resource lifecycle outcomes to contextual recovery states, and avoid silent redirects that erase the user's original intent."],
        "exceptions": ["Highly sensitive resources may deliberately collapse multiple states into one generic unavailable response to avoid existence disclosure."],
        "verification": ["Create links to resources, then delete, move, archive, and revoke them in turn; revisit each link and inspect whether the resulting recovery matches the current authoritative lifecycle state."],
        "owner_hints": ["designing-recent-items-navigation"], "verifier_hints": ["critiquing-functional-completeness"],
        "capabilities": interaction_caps(**{"semantic-product": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["NAVIGATION_RESILIENCE_RULES_V13"]
