"""V13 notification and background task rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


NOTIFICATION_BACKGROUND_RULES_V13 = [
    {
        "rule_id": 'ui.notifications.read-state-cross-device-consistent', "domain": 'notifications', "class": 'behavioral', "severity": 'moderate', "enforcement": 'warn',
        "title": 'Notification read state should reconcile consistently across devices and notification center surfaces',
        "statement": 'When notification read or seen state is account-synchronized, marking an item read on one device should reconcile to other active surfaces without recreating the notification as unread or losing newer unread events.',
        "intent": 'Keep notification attention state causal across devices so badges and centers represent what the user has actually acknowledged.',
        "applies_when": ['The product syncs notification inbox or unread counts across multiple devices or browser sessions for the same account.'], "does_not_apply_when": [],
        "failure_modes": ['A read event on one client is overwritten by stale unread state from another client, or a later synchronization inflates badge count with already acknowledged items.'],
        "user_impacts": ['Users repeatedly process the same alerts or miss genuinely new notifications because cross-device read state is inconsistent.'],
        "observables": ['Mark items read on one device while another is offline or delayed, reconnect it, and inspect item-level read state and aggregate badge counts.'],
        "falsifiers": ['Read acknowledgements reconcile according to stable notification identity and causal state, while genuinely newer notifications remain unread.'],
        "repairs": ['Synchronize read markers as monotonic or versioned per-notification state rather than replacing the whole inbox with a stale client snapshot.'],
        "exceptions": ['Products that deliberately maintain device-local read state must label that model and must not present the badge as account-global.'],
        "verification": ['Exercise read, mark-all-read, offline reconnect, and new-notification arrival across multiple clients and verify stable item and badge reconciliation.'],
        "owner_hints": ['designing-notification-centers'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.notifications.dismiss-does-not-mark-action-complete', "domain": 'notifications', "class": 'mechanical', "severity": 'major', "enforcement": 'block',
        "title": 'Dismissing a notification must not imply the underlying task or obligation is complete',
        "statement": 'Closing, swiping away, or dismissing a notification is an attention-state action unless the product explicitly defines it as the domain action itself; it must not silently approve, resolve, pay, acknowledge, or complete the underlying object.',
        "intent": 'Separate notification presentation lifecycle from the authoritative lifecycle of the task that generated it.',
        "applies_when": ['A notification references an approval, payment, incident, message, task, reminder, security event, or other domain object with its own completion state.'], "does_not_apply_when": [],
        "failure_modes": ['Dismissing the notification changes the underlying object to completed, acknowledged, approved, or resolved without an explicit domain action.'],
        "user_impacts": ['Users can accidentally complete obligations simply by clearing interruption UI and may later be unable to recover the original unresolved task.'],
        "observables": ['Dismiss representative notifications and inspect the authoritative domain object and audit state for unintended lifecycle changes.'],
        "falsifiers": ['Dismissal affects only notification attention or presentation state unless the control is explicitly labeled and confirmed as the actual domain action.'],
        "repairs": ['Maintain separate notification and domain-object state machines and bind quick actions to explicit verbs rather than treating generic dismissal as completion.'],
        "exceptions": ['A notification may include a clearly labeled domain action such as Approve or Mark done; that explicit action is distinct from dismissing the notification itself.'],
        "verification": ['Dismiss and separately invoke each notification action, then verify only explicit domain actions mutate the authoritative task lifecycle.'],
        "owner_hints": ['designing-notifications-and-interruptions'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.notifications.permission-denial-not-block-core', "domain": 'notifications', "class": 'contextual', "severity": 'major', "enforcement": 'block',
        "title": 'Notification permission denial must not block unrelated core product use',
        "statement": 'If push or system notification permission is optional to the product’s primary task, denying that permission must not trap users in onboarding, repeatedly block navigation, or falsely claim the product cannot function.',
        "intent": 'Respect platform notification authority without turning an optional interruption channel into coercive access to unrelated functionality.',
        "applies_when": ['The product requests notification permission for reminders, updates, marketing, collaboration, or convenience while core workflows can function without system notifications.'], "does_not_apply_when": [],
        "failure_modes": ['Denying permission prevents entry into unrelated product features, loops the permission prompt, or leaves the user with no normal path to continue without enabling notifications.'],
        "user_impacts": ['Users are coerced into granting an optional interruption channel or are effectively locked out of functionality that does not technically require it.'],
        "observables": ['Deny notification permission from first-run and later prompts and attempt core workflows while observing whether the product remains usable without repeated blocking.'],
        "falsifiers": ['Core tasks remain accessible, notification-dependent features explain their limitation when invoked, and settings provide a later opt-in path without coercive loops.'],
        "repairs": ['Decouple optional notification onboarding from core navigation, record denial state, and prompt again only at relevant user-initiated moments allowed by platform rules.'],
        "exceptions": ['Safety-critical products may require a notification channel for a narrowly defined feature when that requirement is intrinsic and disclosed before the user enters that feature.'],
        "verification": ['Test first denial, permanent denial, later enablement, and feature-specific reminder setup and verify unrelated core workflows remain available.'],
        "owner_hints": ['designing-permission-onboarding'], "verifier_hints": ['critiquing-user-experience'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.background.progress-survives-navigation', "domain": 'background', "class": 'behavioral', "severity": 'moderate', "enforcement": 'warn',
        "title": 'Background task progress should survive navigation without resetting to a new fake job',
        "statement": 'When a long-running task continues after users leave its initiating screen, returning or viewing global progress must reconnect to the same authoritative job rather than restart progress or create a duplicate visual task.',
        "intent": 'Preserve continuity for exports, imports, agent runs, indexing, uploads, conversions, and other work whose lifecycle outlives one route.',
        "applies_when": ['A task is designed to continue across route changes, app sections, minimized panels, or temporary loss of the initiating view.'], "does_not_apply_when": [],
        "failure_modes": ['Navigating away destroys the job identity so returning shows zero progress, starts a second job, or cannot distinguish the original active task from a new request.'],
        "user_impacts": ['Users may trigger duplicate expensive work, lose cancellation or recovery controls, or believe active processing stopped when only the view changed.'],
        "observables": ['Start a background task, navigate across routes, return, and compare job identifiers, progress, cancellation state, and terminal result with the original task.'],
        "falsifiers": ['Every surface reconnects to the same job identity and current authoritative state until the task reaches a terminal lifecycle or is intentionally detached.'],
        "repairs": ['Store background job identity outside route-local component state and rehydrate views from the task service rather than reconstructing progress from screen lifecycle.'],
        "exceptions": ['A route-scoped operation that is explicitly cancelled on navigation is not a background task and should communicate that cancellation contract before users leave.'],
        "verification": ['Start representative long tasks, navigate away and back repeatedly, refresh applicable views, and verify no duplicate job or progress reset appears.'],
        "owner_hints": ['designing-background-task-progress'], "verifier_hints": ['critiquing-performance-and-resilience'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.background.completion-notifies-correct-job', "domain": 'background', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Background completion feedback must remain bound to the exact job that finished',
        "statement": 'Late completion, error, or notification events from background work must identify the originating job so they cannot overwrite the UI state or result of a newer task started from the same surface.',
        "intent": 'Prevent asynchronous completion races from presenting stale output as the result of the user’s most recent request.',
        "applies_when": ['Users can start multiple exports, generations, searches, agent runs, conversions, or other background jobs from the same feature over time.'], "does_not_apply_when": [],
        "failure_modes": ['An older job completes after a newer one and its result is applied to the current view, toast, download action, or result panel because completion is keyed only by feature or route.'],
        "user_impacts": ['Users can act on stale output while believing it belongs to the latest task and may lose access to the actual newer job result.'],
        "observables": ['Start jobs A and B with controlled completion order B then A, and inspect which result each completion notification and result surface references.'],
        "falsifiers": ['Each terminal event names or resolves the exact job identity; old jobs remain separately accessible and cannot replace newer task state unless the user selects them.'],
        "repairs": ['Carry stable job IDs through transport, notification, result storage, and UI reconciliation and ignore stale completion for state slots owned by a newer job.'],
        "exceptions": ['A feature that enforces a strict single-job policy may cancel A before B starts; completion from cancelled A must still be ignored if it arrives later.'],
        "verification": ['Force out-of-order completion and cancellation races across multiple jobs and verify every message, result, and action remains bound to the correct identity.'],
        "owner_hints": ['designing-background-task-progress'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.background.cancel-state-terminal', "domain": 'background', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'A cancelled background task must not later transition to success from a stale completion event',
        "statement": 'Once cancellation becomes authoritative for a background task, delayed worker or network completion must not silently flip the same task to successful completion unless the product explicitly models cancellation as best-effort and reports the actual side effect separately.',
        "intent": 'Keep terminal task state monotonic so users can trust whether cancelled work still produced an external effect or result.',
        "applies_when": ['The product exposes cancellation for long-running background work whose worker may race with the cancellation request or finish concurrently.'], "does_not_apply_when": [],
        "failure_modes": ['The UI confirms cancellation and later marks the same job successful because a stale completion event arrives, without explaining that the external action had already committed.'],
        "user_impacts": ['Users can believe work was stopped when it actually completed or believe a cancelled task resumed on its own, undermining control over costly or consequential operations.'],
        "observables": ['Race cancellation against near-complete jobs and inspect authoritative task state, external side effects, and late events after cancellation confirmation.'],
        "falsifiers": ['Terminal cancellation remains terminal when it prevented commit; if work committed before cancellation, the UI reports that distinct outcome rather than rewriting cancelled history as ordinary success.'],
        "repairs": ['Use task-version or terminal-state guards, define commit and cancel ordering, and reconcile late events against authoritative lifecycle before updating user-visible state.'],
        "exceptions": ['Some remote systems provide best-effort cancellation only; the product must state when cancellation is pending and report if the operation completed before it could be stopped.'],
        "verification": ['Exercise cancellation before start, mid-run, at commit boundary, and after worker completion with delayed events and verify truthful terminal-state ordering.'],
        "owner_hints": ['designing-background-task-progress'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["NOTIFICATION_BACKGROUND_RULES_V13"]
