"""V13 performance feedback and media lifecycle rules."""
from __future__ import annotations

from ._capabilities import interaction_caps


PERFORMANCE_MEDIA_RULES_V13 = [
    {
        "rule_id": "ui.performance.loading-state-matches-progress",
        "domain": "performance", "class": "mechanical", "severity": "moderate", "enforcement": "warn",
        "title": "Loading feedback must not imply determinate progress that the system cannot actually measure",
        "statement": "A progress bar, percentage, step counter, or remaining-work representation must be based on meaningful measurable progress; unknown-duration work should use an indeterminate or stage-based status rather than fabricated precision.",
        "intent": "Keep wait feedback truthful so users can distinguish known completion progress from activity whose duration or remaining work is genuinely unknown.",
        "applies_when": ["The interface represents loading, upload, export, processing, generation, synchronization, indexing, migration, or another operation with a quantitative or stepwise progress indicator."],
        "does_not_apply_when": ["The displayed value is explicitly a local preparation phase or other bounded sub-operation whose progress is independently measurable even if later total duration remains unknown."],
        "failure_modes": ["The UI advances a smooth percentage or countdown using timers, animation, or guessed milestones unrelated to authoritative completed work and presents the value as real progress."],
        "user_impacts": ["Users form false expectations, abandon work at the wrong time, or distrust later status because the interface promises precision the operation cannot support."],
        "observables": ["Compare displayed progress with measurable completed units or authoritative stages and find the number can advance or reach near-complete without corresponding work completion."],
        "falsifiers": ["Determinate values are derived from measurable work or documented stages, while operations without such evidence use indeterminate activity and truthful qualitative status."],
        "repairs": ["Connect progress UI to real completed units/stages, or replace fabricated percentages with indeterminate feedback plus meaningful status changes and cancellation/recovery controls where appropriate."],
        "exceptions": ["A forecast may be displayed when clearly labeled as an estimate and derived from an explicit model, separate from the authoritative completed-work indicator."],
        "verification": ["Throttle or vary the operation and compare progress output against authoritative completed work, confirming determinate indicators track real progress rather than elapsed animation time."],
        "owner_hints": ["designing-empty-loading-error-states"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.performance.skeleton-does-not-fake-final-content",
        "domain": "performance", "class": "contextual", "severity": "moderate", "enforcement": "warn",
        "title": "Skeleton placeholders must represent loading structure without being mistaken for real loaded content",
        "statement": "Skeletons and placeholders should communicate that content is pending while approximating stable layout; they must not contain fabricated values, labels, rankings, avatars, or final-looking records that users can mistake for actual data.",
        "intent": "Reduce layout instability without crossing the truth boundary between structural placeholder and authoritative content.",
        "applies_when": ["A loading state renders skeletons, placeholder cards, provisional chart shapes, fake rows, shimmer blocks, or other pre-content visual structures."],
        "does_not_apply_when": ["The displayed content is a clearly labeled preview/demo dataset intentionally separate from the user's real data and not represented as a loading result."],
        "failure_modes": ["Placeholder UI includes realistic names, amounts, metrics, notifications, statuses, or other values that look authoritative before data has loaded."],
        "user_impacts": ["Users can briefly read or act on invented information, misinterpret the loading state, or lose trust when apparently real content changes abruptly after fetch completion."],
        "observables": ["Inspect the loading render independently of animation and determine whether a reasonable user could interpret placeholder text/values/records as the real data they requested."],
        "falsifiers": ["Placeholders communicate pending state, preserve approximate geometry, and avoid decision-relevant fabricated content while the final data replaces them cleanly."],
        "repairs": ["Use neutral structural shapes or explicit loading labels, reserve realistic values for actual or clearly marked demo data, and size placeholders from layout expectations rather than fake records."],
        "exceptions": ["Static educational examples may remain visible during background refresh when they are not presented as the user's live result and their example status is persistent."],
        "verification": ["Capture the product under delayed loading, hide animation cues, and review whether any placeholder could be mistaken for authoritative content or decision-relevant values."],
        "owner_hints": ["designing-skeleton-loading"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.performance.input-remains-responsive-under-background-work",
        "domain": "performance", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Background computation must not make essential input and cancellation controls unresponsive",
        "statement": "Long-running rendering, parsing, generation, filtering, synchronization, or computation must preserve responsiveness for essential input, stop/cancel, navigation, and recovery controls instead of monopolizing the interaction thread until work finishes.",
        "intent": "Ensure users retain practical control during expensive work and can interrupt, correct, or leave a task even when the background operation is slower than expected.",
        "applies_when": ["The interface can perform materially expensive client or application work while users may still need to type, scroll, navigate, cancel, or change the requested operation."],
        "does_not_apply_when": ["The platform executes a short atomic transition that must block interaction for correctness and its maximum duration remains below any perceptible control-loss boundary in supported conditions."],
        "failure_modes": ["Essential controls stop responding, keystrokes queue for long intervals, scrolling freezes, or cancel cannot be invoked because expensive work blocks the interaction/event loop."],
        "user_impacts": ["Users cannot stop runaway work, may repeat commands because feedback is frozen, or experience apparent crashes and lost input during heavy operations."],
        "observables": ["Run representative worst-case work and measure whether input events, cancel actions, navigation, or scrolling are delayed until the expensive task yields or completes."],
        "falsifiers": ["Essential interaction remains responsive under realistic heavy workloads, cancellation can preempt or cooperatively stop work, and queued results cannot overwrite newer user intent."],
        "repairs": ["Chunk or move expensive work off the critical interaction path, yield between batches, prioritize user input, and implement cancellation/version checks before applying delayed results."],
        "exceptions": ["A short explicitly modal commit may temporarily lock conflicting edits when partial interaction would corrupt state, but cancel/navigation expectations must match the product's declared transaction model."],
        "verification": ["Stress the largest supported workload while repeatedly typing, scrolling, navigating, and cancelling; measure event response and confirm stale background results do not apply after newer intent."],
        "owner_hints": ["designing-motion-performance-fallbacks"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "interaction": "REQUIRED"}), "provenance_ids": ["nui-v12-reality-catalog", "nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.media.buffering-distinct-from-paused",
        "domain": "media", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Buffering, paused, ended, and failed playback must remain distinct user-visible states",
        "statement": "Media controls and status feedback must distinguish a deliberate pause from buffering, terminal end, network stall, decode failure, and other playback states so the same play/pause affordance does not conceal why media stopped advancing.",
        "intent": "Let users choose the correct recovery action and understand whether playback stopped because of their command, temporary loading, completion, or failure.",
        "applies_when": ["Audio, video, live streams, remote playback, or other time-based media can pause, buffer, end, stall, or fail under different underlying player states."],
        "does_not_apply_when": ["The media is an intentionally non-interactive decorative loop whose playback state has no user task consequence."],
        "failure_modes": ["The UI shows paused or a generic play icon while the player is actually buffering/failing, or shows indefinite loading after media has ended or the user explicitly paused."],
        "user_impacts": ["Users repeatedly press controls that cannot fix the real condition, lose confidence in playback state, or miss that recovery/network action is required."],
        "observables": ["Force pause, buffering, end-of-media, network stall, and decode error and compare the visible state, available controls, and timeline behavior for semantic distinction."],
        "falsifiers": ["Each player state maps to truthful feedback and recovery controls, and user pause remains distinguishable from system inability to continue playback."],
        "repairs": ["Drive UI from authoritative player state, model buffering/error/end separately from paused, and expose retry or connection recovery only when those actions match the underlying condition."],
        "exceptions": ["Very brief buffering may be intentionally absorbed without a visible indicator when playback remains effectively continuous and no control semantics become misleading."],
        "verification": ["Simulate each terminal and transient playback state and compare the rendered control/status model with the underlying player state machine and available recovery."],
        "owner_hints": ["designing-media-buffering-recovery"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.media.quality-fallback-preserves-timeline",
        "domain": "media", "class": "behavioral", "severity": "moderate", "enforcement": "warn",
        "title": "Adaptive quality changes should preserve playback position and interaction continuity",
        "statement": "When media quality, rendition, proxy, bitrate, or source changes to recover from bandwidth or performance pressure, the transition should preserve logical playback time, active captions/audio intent, and user control unless the source itself lacks an equivalent timeline.",
        "intent": "Make adaptive quality a transport/rendering change rather than an unexpected restart or loss of the user's current media context.",
        "applies_when": ["The player can switch bitrate, resolution, source rendition, proxy, local/remote quality, or another media representation during an active playback session."],
        "does_not_apply_when": ["The fallback source is genuinely a different edit or timeline and the product explicitly communicates that the user's position cannot map exactly."],
        "failure_modes": ["Quality recovery restarts from zero, jumps to a different logical moment, drops active captions/audio choice, or disables controls as though a new unrelated media session began."],
        "user_impacts": ["Users lose their place, repeat content, miss material, or must reconstruct playback settings after a background adaptation they did not request."],
        "observables": ["Trigger quality changes at known timestamps with captions/audio selections and compare logical time plus selected playback settings before and after the transition."],
        "falsifiers": ["Adaptive transitions retain equivalent logical timeline position and user media preferences, or explicitly explain unavoidable mapping loss for non-equivalent sources."],
        "repairs": ["Map renditions to shared media time, persist user playback preferences above the rendition instance, and reapply state after transport/source replacement before resuming."],
        "exceptions": ["Live streams may rejoin the latest available live edge when the prior buffered position no longer exists, provided the player communicates the live-state transition rather than silently jumping."],
        "verification": ["Force multiple quality/rendition transitions during playback and compare timestamp, caption/audio state, play/pause intent, and control continuity across each switch."],
        "owner_hints": ["designing-adaptive-media-quality-control"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.media.download-retry-preserves-completed-work",
        "domain": "media", "class": "behavioral", "severity": "moderate", "enforcement": "warn",
        "title": "Retrying an interrupted media download should preserve completed valid work when resumability exists",
        "statement": "When the storage or transport layer supports resumable downloads, a retry should continue from verified completed ranges instead of silently discarding already downloaded valid data and restarting the entire transfer without need.",
        "intent": "Respect bandwidth, battery, time, and user expectations during recoverable offline-media failures while remaining honest when a restart is technically required.",
        "applies_when": ["The product downloads media or large files for offline use and the underlying protocol/storage model can validate and resume partial transfer state."],
        "does_not_apply_when": ["The source does not support resumption, the partial data failed integrity validation, or encryption/version changes make prior ranges unusable."],
        "failure_modes": ["Retry always resets progress to zero and redownloads valid completed content even though the application has a verified resumable partial transfer."],
        "user_impacts": ["Users waste bandwidth and battery, repeat long waits, and may fail to complete offline downloads on unstable connections despite resumable transport capability."],
        "observables": ["Interrupt a resumable transfer after substantial verified progress, retry, and compare network/storage behavior with the retained completed range metadata."],
        "falsifiers": ["Retry resumes from verified completed work when supported, or explicitly restarts only when integrity, source capability, or version state makes resumption invalid."],
        "repairs": ["Persist resumable transfer metadata, validate partial ranges before reuse, and distinguish resume from restart in the download state machine and user feedback."],
        "exceptions": ["Small transfers may intentionally restart when the implementation does not claim resumability and the cost is negligible, but the UI must not falsely represent preserved progress."],
        "verification": ["Interrupt downloads at different progress points, restore connectivity, retry, and inspect transferred bytes plus UI progress to confirm valid partial work is reused only when safe."],
        "owner_hints": ["designing-download-progress-and-retry"], "verifier_hints": ["critiquing-performance-and-resilience"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["PERFORMANCE_MEDIA_RULES_V13"]
