"""V13 privacy, permission, and security-state rules."""
from __future__ import annotations

from ._capabilities import interaction_caps


PRIVACY_SECURITY_RULES_V13 = [
    {
        "rule_id": "ui.privacy.permission-purpose-matches-use",
        "domain": "privacy", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "The stated permission purpose must match the capability the product actually uses after grant",
        "statement": "When the interface explains why sensitive access is requested, the granted data or device capability must be used within that described purpose and must not silently expand into unrelated collection, sharing, background use, or secondary features.",
        "intent": "Keep the consent explanation operationally truthful so users are not asked to approve one understandable purpose while the resulting permission powers materially different behavior.",
        "applies_when": ["The product presents a purpose, rationale, feature explanation, or consent copy before requesting sensitive device, account, workspace, or data access."],
        "does_not_apply_when": ["The permission scope and all materially different uses are already covered by an explicit standing policy that users can inspect and the current request accurately references that policy."],
        "failure_modes": ["The post-grant product uses the permission for a materially different purpose, broader data flow, background behavior, recipient set, or feature than the explanation users reviewed before granting access."],
        "user_impacts": ["Users can disclose data or device capability for uses they did not meaningfully understand because the permission rationale and actual behavior represent different authority boundaries."],
        "observables": ["Compare the rendered rationale with runtime use of the granted capability and find decision-relevant collection, sharing, background access, or secondary feature use absent from the stated purpose."],
        "falsifiers": ["Observed uses remain within the explained purpose or the product obtains an additional explicit authority decision before materially expanding how the granted capability is used."],
        "repairs": ["Bind permission rationale to a documented use contract, restrict downstream behavior to that scope, and trigger incremental consent or a new permission explanation when product use materially expands."],
        "exceptions": ["Incidental platform operations required to deliver the explained feature may remain implicit when they do not introduce a distinct data recipient, purpose, or user-relevant authority expansion."],
        "verification": ["Grant representative sensitive permissions, exercise foreground and background behavior, and trace each material use of the capability back to the purpose users were shown or to a later explicit expansion decision."],
        "owner_hints": ["designing-permissions-and-consent"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "semantic-product": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.privacy.denied-permission-recovery",
        "domain": "privacy", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "A denied permission state must offer truthful recovery without pretending access still exists",
        "statement": "When a required permission is denied, revoked, restricted, or unavailable, the interface must stop dependent behavior, explain the affected capability, and provide an appropriate recovery or alternative instead of looping requests or showing fake success.",
        "intent": "Keep permission state aligned with actual platform authority and prevent users from entering workflows that cannot complete under the current capability boundary.",
        "applies_when": ["A feature depends on permission that can be denied, revoked after grant, restricted by policy, or made unavailable by device/platform state."],
        "does_not_apply_when": ["The feature has a fully equivalent path that does not require the permission and the product transparently switches to that path without loss of user intent."],
        "failure_modes": ["The feature continues as if permission exists, repeatedly asks after a non-repromptable denial, or exposes controls whose promised action cannot succeed under current authority."],
        "user_impacts": ["Users encounter dead controls, misleading success, repeated coercive prompts, or unexplained failure because the product ignores the authoritative permission state."],
        "observables": ["Deny or revoke the permission and attempt the dependent task; the UI either continues into an impossible flow, loops the request, or fails to surface a valid settings/alternative recovery path."],
        "falsifiers": ["The denied/revoked state disables or adapts dependent behavior, communicates the capability boundary accurately, and offers only recovery actions that can actually restore or bypass access."],
        "repairs": ["Model permission state explicitly, branch dependent features before execution, and route users to settings, alternative inputs, or limited-mode behavior appropriate to the platform state."],
        "exceptions": ["A one-time educational retry may be appropriate when the platform still allows reprompting and the user initiated the blocked feature again after understanding the rationale."],
        "verification": ["Test first denial, permanent denial, later revocation, policy restriction, and restored permission; verify each state produces truthful controls and recovery without request loops."],
        "owner_hints": ["designing-location-permission-recovery"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.privacy.session-revocation-visible",
        "domain": "privacy", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Revoking a device or session must produce a verifiable change in that session's authority",
        "statement": "When users revoke a remembered device, browser, API session, or other login session, the interface must reflect the authoritative revocation result and must not leave the removed session presented as active or silently usable.",
        "intent": "Make security controls trustworthy by tying visible session management to real authorization state rather than a cosmetic list mutation.",
        "applies_when": ["The product exposes session or device management with revoke, sign out, remove device, terminate session, or equivalent authority-changing actions."],
        "does_not_apply_when": ["The listed item is historical audit data and the control clearly does not represent active authorization."],
        "failure_modes": ["The UI removes or marks a session revoked before the authorization backend commits the change, or the supposedly revoked session can continue privileged operations without a documented grace boundary."],
        "user_impacts": ["Users may believe a compromised or shared device is no longer authorized when it can still access the account or perform sensitive actions."],
        "observables": ["Revoke a live secondary session and compare the management UI, backend/authoritative state, and the secondary session's next privileged request for consistency."],
        "falsifiers": ["Successful revocation is confirmed by the authority source, the management list reflects the terminal state, and the targeted session loses access at the product's documented revocation boundary."],
        "repairs": ["Treat revocation as an asynchronous authority operation, distinguish pending from completed state, and invalidate or recheck the target session before reporting terminal success."],
        "exceptions": ["A bounded propagation delay may exist when explicitly documented by the system, but the interface must represent the session as pending revocation rather than already terminated during that interval."],
        "verification": ["Maintain two active sessions, revoke one from the other, and verify the targeted session's next privileged request is denied or reauthenticated at the same boundary the UI reports as complete."],
        "owner_hints": ["designing-device-session-management"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.privacy.shared-device-secret-redaction",
        "domain": "privacy", "class": "mechanical", "severity": "major", "enforcement": "block",
        "title": "Sensitive content must not remain exposed in shared-device previews after the protected context closes",
        "statement": "On shared or easily observable devices, sensitive account, message, payment, health, credential, or private workspace content must not remain unnecessarily visible in app-switcher snapshots, locked previews, background surfaces, or post-sign-out remnants.",
        "intent": "Prevent incidental disclosure after users leave the protected foreground context, especially where the operating system or shared-device surface can preserve recent visual state.",
        "applies_when": ["The product handles content that users reasonably expect to disappear from casual observation when the app backgrounds, locks, switches accounts, signs out, or leaves a private mode."],
        "does_not_apply_when": ["The product is explicitly designed for public display and the displayed information is not sensitive for the active user or organization."],
        "failure_modes": ["Sensitive rendered content remains readable in app-switcher snapshots, background views, lock previews, or after session/account teardown beyond the intended protected context."],
        "user_impacts": ["Nearby people or later users of the device can see private information without authenticating or reopening the protected product state."],
        "observables": ["Background, lock, switch accounts, or sign out from a sensitive screen and inspect platform previews and residual surfaces for readable protected content."],
        "falsifiers": ["Sensitive foreground content is redacted, replaced, or otherwise protected in exposed lifecycle surfaces and stale private state is cleared when the session boundary requires it."],
        "repairs": ["Use lifecycle-aware privacy covers or snapshot redaction, clear protected view state at session teardown, and scope notification/preview content to the user's configured privacy posture."],
        "exceptions": ["Users may explicitly opt into visible previews for particular content classes when the platform supports that choice and the privacy consequence is clear."],
        "verification": ["Open representative sensitive views, trigger background/app-switcher/lock/sign-out states on supported platforms, and inspect every exposed preview for residual readable private content."],
        "owner_hints": ["designing-mobile-app-switcher-privacy"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"visual-render": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.privacy.consent-revocation-propagates",
        "domain": "privacy", "class": "behavioral", "severity": "major", "enforcement": "block",
        "title": "Revoking a consent preference must propagate to the behavior that consent controls",
        "statement": "When a user disables an optional consent or privacy preference, the product must update the controlled collection, sharing, personalization, notification, or other behavior at the documented effective boundary instead of changing only the preference UI.",
        "intent": "Ensure preference centers are operational controls over product behavior rather than decorative representations of intent that downstream systems ignore.",
        "applies_when": ["The product exposes optional privacy, tracking, personalization, communication, data-sharing, or similar preferences whose state is represented as controlling ongoing behavior."],
        "does_not_apply_when": ["A setting is informational only and is not presented as changing product behavior or downstream processing."],
        "failure_modes": ["The preference toggles visually but the controlled behavior continues beyond the stated boundary, or dependent services retain the old state without a truthful pending/error representation."],
        "user_impacts": ["Users cannot rely on privacy controls and may continue receiving collection, sharing, messages, or personalization they explicitly disabled."],
        "observables": ["Change a consent preference, then observe the controlled behavior or downstream state after the documented effective point and compare it with the new preference."],
        "falsifiers": ["The preference update is committed, dependent behavior re-evaluates the new state, and any propagation delay or failure is represented rather than silently treated as complete."],
        "repairs": ["Bind preference UI to authoritative consent state, propagate changes transactionally or with explicit pending semantics, and gate dependent behavior on the current effective preference."],
        "exceptions": ["Some previously completed processing may be legally or operationally retained; the product must distinguish stopping future optional behavior from erasing historical records it cannot or should not delete."],
        "verification": ["Toggle each representative consent category off and on, then inspect the corresponding runtime behavior and downstream state to confirm effective propagation and truthful pending/error handling."],
        "owner_hints": ["designing-consent-preference-centers"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "human-review": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": "ui.privacy.permission-escalation-requires-new-consent",
        "domain": "privacy", "class": "mechanical", "severity": "critical", "enforcement": "block",
        "title": "Expanding previously granted permission scope requires a new explicit authority boundary",
        "statement": "A product must not treat consent for one resource, recipient set, data category, tool capability, or permission scope as authorization for a materially broader scope that becomes available later without a new explicit grant or standing policy covering it.",
        "intent": "Prevent silent permission creep when features, integrations, agent tools, workspace roles, or resource sets expand after the user approved a narrower authority.",
        "applies_when": ["A workflow can expand from previously granted permission into additional resources, data classes, recipients, tools, roles, destinations, or other materially broader authority."],
        "does_not_apply_when": ["The original grant explicitly and clearly covered the broader scope under a still-valid standing policy and the current action remains within that disclosed boundary."],
        "failure_modes": ["The system silently inherits an older narrow consent and executes with newly expanded scope without presenting or recording a new authority decision."],
        "user_impacts": ["Users can expose data, grant access, or authorize actions beyond what they intentionally approved because the UI collapses distinct permission scopes into one remembered grant."],
        "observables": ["Increase the available target/resource/tool scope after an initial grant and observe whether the workflow can use the broader authority without a new consent or policy evaluation."],
        "falsifiers": ["Material scope expansion triggers a new grant, admin/policy evaluation, or equivalent authority check whose visible scope matches the broadened capability before use."],
        "repairs": ["Version permission grants by scope, compare requested authority with the active grant at execution time, and require incremental consent whenever the requested set exceeds the existing boundary."],
        "exceptions": ["Organization administrators may pre-authorize bounded classes of expansion when that delegated policy is explicit, inspectable, and revocable for affected users."],
        "verification": ["Grant a narrow permission, later add a new resource or tool class, and verify the broader action remains blocked until an authority record explicitly covering the expanded scope is established."],
        "owner_hints": ["designing-agent-tool-permission-escalation"], "verifier_hints": ["critiquing-security-and-privacy"],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED", "semantic-product": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["PRIVACY_SECURITY_RULES_V13"]
