"""V13 scheduling and timezone rules authored as distinct failure contracts."""
from __future__ import annotations
from ._capabilities import interaction_caps

SCHEDULING_TIMEZONE_RULES_V13 = [
    {
        "rule_id":"ui.schedule.dst-gap-invalid-local-time","domain":"schedule","class":"mechanical","severity":"major","enforcement":"block",
        "title":"A local time that does not exist during a DST jump must not commit as a different instant silently",
        "statement":"When a timezone transition skips a range of local wall times, entering or generating one of those nonexistent times must produce an explicit correction or validation state instead of silently normalizing to another clock time.",
        "intent":"Keep scheduling input faithful to the wall time users selected when local civil time has a discontinuity.",
        "applies_when":["Users create or edit timezone-aware events in regions with daylight-saving or other civil-time jumps."],"does_not_apply_when":[],
        "failure_modes":["A nonexistent local time such as one inside a spring-forward gap is accepted and stored as a different local time or instant without disclosure."],
        "user_impacts":["Meetings, reminders, jobs, or deadlines can occur at a moment the user never selected."],
        "observables":["Enter local times immediately before, inside, and after a known forward clock transition and compare displayed confirmation with stored instant and zone."],
        "falsifiers":["Gap times are rejected or explicitly adjusted with the resulting valid local time visible before commit."],
        "repairs":["Resolve local date-time against the selected timezone before commit and surface nonexistent-time recovery rather than relying on implicit date-library normalization."],
        "exceptions":["Systems accepting only absolute instants may avoid local-gap input entirely if they never present wall-time editing semantics."],
        "verification":["Test representative forward transitions across supported zones and confirm no nonexistent wall time commits under a different clock label silently."],
        "owner_hints":["designing-timezone-aware-scheduling"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.schedule.dst-fold-disambiguates-repeated-time","domain":"schedule","class":"mechanical","severity":"major","enforcement":"block",
        "title":"A repeated local time during a DST fold must identify which instant is intended",
        "statement":"When a backward clock transition creates two distinct instants with the same local clock label, scheduling must preserve or expose the offset or occurrence needed to distinguish them.",
        "intent":"Prevent an apparently exact local time from mapping ambiguously to two real moments.",
        "applies_when":["Users schedule or audit events across zones with backward civil-time transitions."],"does_not_apply_when":[],
        "failure_modes":["A repeated local time commits to an arbitrary first or second occurrence while the confirmation exposes no offset or other disambiguation."],
        "user_impacts":["Events can happen an hour away from the intended instant even though the visible date and clock time appear correct."],
        "observables":["Create events in a repeated-hour window and inspect selected offset, stored instant, and rendered confirmation."],
        "falsifiers":["The product deterministically preserves the existing instant when editing or asks or exposes enough offset context when creating an ambiguous local time."],
        "repairs":["Carry timezone and offset or fold identity through the picker and storage contract, and disambiguate repeated wall times at the decision boundary."],
        "exceptions":["A documented domain rule may always choose one occurrence when users never choose between them, provided the rule is visible where consequence matters."],
        "verification":["Test both occurrences of repeated wall times in supported zones and verify round-trip editing preserves the intended instant."],
        "owner_hints":["designing-timezone-aware-scheduling"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.schedule.organizer-zone-change-explicit-semantics","domain":"schedule","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Changing an event timezone must explicitly preserve either the instant or the wall time",
        "statement":"When an organizer changes an event timezone, the product must define whether the real instant stays fixed or the local wall time stays fixed and must not switch between those semantics silently.",
        "intent":"Make timezone editing a deliberate temporal transformation rather than an accidental rescheduling operation.",
        "applies_when":["An existing event can be edited to use a different timezone."],"does_not_apply_when":[],
        "failure_modes":["Selecting another timezone unexpectedly moves the absolute event or unexpectedly changes the displayed local hour without indicating which property is preserved."],
        "user_impacts":["Attendees can be rescheduled unintentionally while the organizer believes they only changed display context."],
        "observables":["Change event zone while recording original instant and wall time and compare the preview, attendee view, and stored result."],
        "falsifiers":["The editing model consistently preserves the declared property and makes any resulting time shift visible before save."],
        "repairs":["Represent timezone change as an explicit transform with a documented preserve-instant or preserve-wall-time rule and preview the resulting event."],
        "exceptions":["Display-only timezone selectors that do not mutate the event are outside this rule when clearly separate from editing."],
        "verification":["Change zones in both directions around DST boundaries and confirm storage and attendee rendering follow the declared semantics."],
        "owner_hints":["designing-time-zone-selection"],"verifier_hints":["critiquing-user-experience"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.schedule.recurring-event-zone-semantics-stable","domain":"schedule","class":"behavioral","severity":"major","enforcement":"block",
        "title":"Recurring events must preserve their declared timezone semantics across offset changes",
        "statement":"A recurring schedule intended for a local wall time must remain at that local time when the zone offset changes, while an instant-based recurrence must remain instant-based; the implementation must not conflate the two models.",
        "intent":"Prevent recurring meetings and jobs from drifting by an hour when daylight or timezone rules change.",
        "applies_when":["The product creates recurring events or jobs spanning timezone offset changes."],"does_not_apply_when":[],
        "failure_modes":["A weekly 09:00 local event is generated by fixed UTC intervals and shifts local hour after DST, or an instant recurrence is reinterpreted as local wall time."],
        "user_impacts":["Repeated obligations occur at unexpected local times for organizers or participants."],
        "observables":["Generate recurrence instances before and after offset transitions and compare local wall time, zone, and absolute instant against recurrence intent."],
        "falsifiers":["Every occurrence follows the recurrence model explicitly chosen by the product and survives timezone rule changes consistently."],
        "repairs":["Store recurrence rule plus timezone semantics rather than materializing a naive fixed-duration series, and regenerate instances using timezone-aware recurrence logic."],
        "exceptions":["Fixed elapsed-interval timers are intentionally instant-based and need not preserve a civil clock label."],
        "verification":["Test recurring series across DST starts, ends, and timezone rule changes and verify expected wall-time or instant invariants."],
        "owner_hints":["designing-calendar-interfaces"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.schedule.availability-cross-zone-date-boundary","domain":"schedule","class":"contextual","severity":"major","enforcement":"warn",
        "title":"Cross-timezone availability must keep date boundaries tied to each participant’s local day",
        "statement":"Availability comparisons across timezones must not treat the organizer’s calendar date as though it were the same civil date for every participant when the candidate instant falls on another local day elsewhere.",
        "intent":"Keep meeting availability aligned with participants’ real local working days and constraints.",
        "applies_when":["Scheduling compares participants, rooms, or policies across timezones near midnight or large zone offsets."],"does_not_apply_when":[],
        "failure_modes":["A slot is shown as inside working hours or on an allowed weekday because date-based rules are evaluated in the wrong participant timezone."],
        "user_impacts":["Meetings can be proposed on another participant’s weekend, holiday, or wrong local day despite appearing valid to the organizer."],
        "observables":["Evaluate candidate instants spanning local midnight for distant zones and compare availability against each participant’s local calendar rules."],
        "falsifiers":["Date-scoped rules are evaluated in the timezone to which they belong and candidate slots expose cross-date context where needed."],
        "repairs":["Convert the candidate instant into each availability source timezone before evaluating weekday, holiday, and working-hour constraints."],
        "exceptions":["Organizations may define all availability in one explicit operational timezone; that policy must be clear and consistently applied."],
        "verification":["Test large positive and negative offsets around midnight, weekends, and local holidays and verify availability respects each declared timezone."],
        "owner_hints":["designing-timezone-aware-scheduling"],"verifier_hints":["critiquing-user-experience"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
    {
        "rule_id":"ui.schedule.all-day-event-not-shifted-by-zone","domain":"schedule","class":"mechanical","severity":"major","enforcement":"block",
        "title":"All-day events must remain date-scoped instead of shifting through timezone conversion",
        "statement":"An all-day event represented as a civil date or date range must not be converted as a midnight instant in a way that moves it to the previous or next date for users in another timezone.",
        "intent":"Preserve date-only semantics for holidays, birthdays, leave, and other events whose meaning is the calendar day rather than a moment at midnight.",
        "applies_when":["The calendar supports all-day or date-only events viewed across multiple timezones."],"does_not_apply_when":[],
        "failure_modes":["An all-day event stored as midnight UTC renders on another calendar day after timezone conversion."],
        "user_impacts":["Users see holidays, leave, birthdays, or deadlines on the wrong date."],
        "observables":["Create date-only events and view them from zones on both sides of UTC and the international date line."],
        "falsifiers":["Date-only events preserve their intended civil date or explicitly declared event-zone date semantics across viewers."],
        "repairs":["Model all-day values as date or date-range types separate from timestamp instants and convert only when the domain explicitly defines an event timezone."],
        "exceptions":["A 24-hour event defined by exact start and end instants is not an all-day date-only event and may shift local calendar dates legitimately."],
        "verification":["View all-day events across diverse zones and confirm no unintended previous or next-day shift occurs."],
        "owner_hints":["designing-calendar-interfaces"],"verifier_hints":["critiquing-functional-completeness"],"capabilities":interaction_caps(**{"browser-runtime":"REQUIRED"}),"provenance_ids":["nui-internal-product-truth-v13"],"status":"active",
    },
]
__all__=["SCHEDULING_TIMEZONE_RULES_V13"]
