"""V13 synchronization and freshness rules: independently authored failure contracts."""
from __future__ import annotations

from ._capabilities import interaction_caps


SYNC_FRESHNESS_RULES_V13 = [
    {
        "rule_id": 'ui.sync.stale-data-labeled-with-age', "domain": 'sync', "class": 'contextual', "severity": 'major', "enforcement": 'warn',
        "title": 'Stale decision-relevant data must expose its freshness boundary instead of looking current',
        "statement": 'When the product knowingly serves cached or delayed data whose age can affect a user decision, the surface must expose enough freshness context to distinguish that state from current authoritative data.',
        "intent": 'Prevent cached availability from being misread as live truth while still allowing degraded experiences to remain useful.',
        "applies_when": ['A screen can show cached, replicated, delayed, offline, or asynchronously refreshed data whose age matters to decisions, status, balances, availability, or operational action.'], "does_not_apply_when": [],
        "failure_modes": ['Known stale data is rendered with the same current-state semantics and timestamp treatment as freshly observed data, with no recoverable age or refresh status.'],
        "user_impacts": ['Users can act on outdated status, values, inventory, incidents, permissions, or other data because the interface conceals that the observation is old.'],
        "observables": ['Force delayed refresh or offline cache and compare displayed freshness metadata and action enablement against the last successful authoritative observation time.'],
        "falsifiers": ['Users can recover when the data was last confirmed or that it is stale, and actions whose safety depends on current state are revalidated or appropriately limited.'],
        "repairs": ['Track observation timestamp or source separately from display time, label stale states where consequential, and trigger fresh validation before current-state-dependent commits.'],
        "exceptions": ['Purely archival or historical views need not label data stale when old time is the intended subject and the recorded timestamp is already explicit.'],
        "verification": ['Simulate cache age, failed refresh, reconnect, and fresh reload and verify the surface transitions between current and stale states truthfully.'],
        "owner_hints": ['designing-data-freshness-communication'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.sync.optimistic-write-reconciles-server-rejection', "domain": 'sync', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'An optimistic UI write must visibly reconcile when the authoritative server rejects it',
        "statement": 'If the interface applies a mutation optimistically before server acceptance, rejection must restore or reconcile authoritative state and explain the failed change instead of leaving the optimistic value displayed as committed.',
        "intent": 'Keep low-latency interaction from crossing the truth boundary between provisional local intent and authoritative persisted state.',
        "applies_when": ['A mutation is rendered locally before the authoritative service confirms validation, permission, version, quota, or business-rule acceptance.'], "does_not_apply_when": [],
        "failure_modes": ['Server rejection arrives but the optimistic state remains visible, dependent UI continues from it, or a generic error appears without restoring the affected authoritative value.'],
        "user_impacts": ['Users can make follow-up decisions based on a change that never persisted and may lose track of which part of their work the server rejected.'],
        "observables": ['Force validation, permission, and conflict rejections after optimistic rendering and compare local state with the authoritative server result.'],
        "falsifiers": ['Rejected mutations reconcile to authoritative state or a clearly marked recoverable draft or conflict, and dependent controls no longer treat the failed optimistic value as committed.'],
        "repairs": ['Associate optimistic changes with mutation IDs and previous or base state, then reconcile success or rejection transactionally while preserving recoverable user input.'],
        "exceptions": ['For collaborative drafts the rejected change may remain locally editable, but it must be marked unsynced rather than presented as shared committed state.'],
        "verification": ['Inject several server-side rejection classes and verify rollback or recovery, user explanation, and subsequent edits all use authoritative state correctly.'],
        "owner_hints": ['designing-cloud-sync-status'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.sync.partial-sync-not-global-success', "domain": 'sync', "class": 'mechanical', "severity": 'major', "enforcement": 'block',
        "title": 'Partial synchronization success must not be summarized as globally synchronized',
        "statement": 'When only some records, folders, devices, accounts, or data classes synchronize successfully, a global success indicator must not hide remaining failures or pending partitions that matter to the user.',
        "intent": 'Preserve the difference between partial progress and complete convergence so users know which content still needs recovery.',
        "applies_when": ['A synchronization operation covers multiple independently failing objects, partitions, accounts, or data classes and the UI exposes aggregate sync status.'], "does_not_apply_when": [],
        "failure_modes": ['Any successful subset flips the aggregate indicator to synced or up to date while failed or pending items remain unresolved and decision-relevant.'],
        "user_impacts": ['Users can close the app or act on missing data believing synchronization completed everywhere when some content never converged.'],
        "observables": ['Force mixed success, failure, and pending outcomes and compare aggregate status with item or partition terminal states.'],
        "falsifiers": ['Aggregate success is shown only when all required partitions meet the completion contract; otherwise the UI exposes partial, pending, or failed scope and recovery.'],
        "repairs": ['Compute aggregate state from required child lifecycles, preserve per-scope failures, and define whether optional partitions affect the global status explicitly.'],
        "exceptions": ['Optional best-effort data may be excluded from the global completion contract when the product clearly identifies it as non-blocking supplemental sync.'],
        "verification": ['Run mixed-outcome syncs across required and optional partitions and verify aggregate status plus recovery accurately represent unresolved scope.'],
        "owner_hints": ['designing-cloud-sync-status'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.sync.cross-device-conflict-does-not-last-write-silently', "domain": 'sync', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Cross-device conflicting edits must follow an explicit merge policy rather than silent wall-clock last-write',
        "statement": 'When two devices modify the same logical field or object without a shared causal base, the product must apply a declared merge or conflict policy and must not silently choose whichever client timestamp appears latest when that can lose meaningful work.',
        "intent": 'Protect offline and multi-device edits from clock drift and arrival-order races that masquerade as user intent.',
        "applies_when": ['The same account can edit shared personal state from multiple devices while devices may be offline or updates may arrive out of order.'], "does_not_apply_when": [],
        "failure_modes": ['Conflicting values are silently resolved by client wall-clock timestamp or network arrival with no causal or version check and the losing edit becomes unrecoverable.'],
        "user_impacts": ['Users can lose valid changes because device clocks or transport timing, rather than product semantics, determine which edit wins.'],
        "observables": ['Create divergent edits from devices with skewed clocks and delayed delivery and inspect the resolution policy and recoverability of the losing value.'],
        "falsifiers": ['Conflicts resolve through causal or version-aware semantics, domain-specific merge, or an explicit conflict choice; timestamp-only arbitration is used only where it is a declared safe policy.'],
        "repairs": ['Use server versions, causal tokens, field-specific merge rules, or explicit conflict records and retain enough information to recover overwritten meaningful values.'],
        "exceptions": ['Ephemeral preferences may intentionally use last-write-wins when loss is low consequence and the product does not imply durable collaborative history.'],
        "verification": ['Vary device clock skew, offline duration, and arrival order for conflicting edits and verify outcome depends on declared merge semantics rather than accidental timing.'],
        "owner_hints": ['resolving-cross-device-state-conflicts'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.sync.clock-skew-not-order-authority', "domain": 'sync', "class": 'mechanical', "severity": 'major', "enforcement": 'block',
        "title": 'Client clock timestamps must not be the sole authority for ordering consequential synchronized events',
        "statement": 'Consequential event order, version precedence, deadlines, or conflict resolution must not rely solely on unsynchronized client clocks when clock skew can invert the real authoritative sequence.',
        "intent": 'Prevent device time errors from changing causal order or authority in distributed user interfaces.',
        "applies_when": ['Events originate on multiple clients and their relative order affects transactions, conflict resolution, audit, message sequencing, or other user-relevant state.'], "does_not_apply_when": [],
        "failure_modes": ['The product sorts or resolves authoritative sequence exclusively by client-provided wall-clock timestamps without server sequencing, causal tokens, or skew handling.'],
        "user_impacts": ['Users can see actions in the wrong order or have newer work rejected or overwritten because one device clock is ahead or behind reality.'],
        "observables": ['Generate events from clients with deliberate clock skew and compare rendered or authoritative order with server receipt, causal, or sequence metadata.'],
        "falsifiers": ['Authoritative ordering uses a trusted sequence or causal model; client time remains display metadata or bounded evidence rather than the sole precedence authority.'],
        "repairs": ['Introduce server or ledger sequencing or causal version identifiers and separate human-facing event time from the field used to resolve authoritative order.'],
        "exceptions": ['Offline journals may preserve local event time for display, but final conflict or order decisions must still follow the system’s declared reconciliation authority.'],
        "verification": ['Run skewed-clock and delayed-network scenarios and verify consequential ordering and conflict outcomes remain stable under the authoritative sequence model.'],
        "owner_hints": ['designing-cloud-sync-status'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
    {
        "rule_id": 'ui.sync.reconnect-does-not-duplicate-write', "domain": 'sync', "class": 'behavioral', "severity": 'major', "enforcement": 'block',
        "title": 'Reconnect replay must not duplicate a mutation that may already have committed before connection loss',
        "statement": 'When connectivity drops after a write is sent but before the client receives acknowledgement, retry or replay must use stable operation identity or reconciliation so the same logical mutation is not applied twice.',
        "intent": 'Protect users from duplicate messages, orders, transfers, tasks, or other side effects caused by ambiguous network completion.',
        "applies_when": ['A mutation can commit remotely while the client loses acknowledgement and later retries automatically or through user recovery.'], "does_not_apply_when": [],
        "failure_modes": ['The client replays the mutation as a new operation without idempotency or state reconciliation and the server applies the same logical effect more than once.'],
        "user_impacts": ['Users can create duplicate records, messages, charges, or other side effects simply because connectivity failed during acknowledgement.'],
        "observables": ['Drop the connection after server commit but before client acknowledgement, reconnect or retry, and inspect authoritative operation count and identifiers.'],
        "falsifiers": ['Replay recognizes the original operation or reconciles committed state so at most the intended logical mutation becomes authoritative.'],
        "repairs": ['Assign stable idempotency or operation IDs before send, persist them across reconnect, and check authoritative state before creating a replacement operation when completion is ambiguous.'],
        "exceptions": ['Pure read operations and naturally idempotent state replacements may not require explicit idempotency keys when replay cannot multiply side effects.'],
        "verification": ['Inject connection loss at pre-send, post-send or pre-commit, post-commit or pre-ack, and post-ack boundaries and verify recovery never duplicates the logical write.'],
        "owner_hints": ['designing-message-sync-gap-recovery'], "verifier_hints": ['critiquing-functional-completeness'],
        "capabilities": interaction_caps(**{"browser-runtime": "REQUIRED"}), "provenance_ids": ["nui-internal-product-truth-v13"], "status": "active",
    },
]

__all__ = ["SYNC_FRESHNESS_RULES_V13"]
